sparcs-kaist/clubs

- packages/web/src/app/clubs/page.tsx
- packages/web/src/common/components/Card.tsx
- packages/web/src/common/components/PageTitle.tsx
- packages/web/src/common/components/SectionTitle.tsx
- packages/web/src/common/components/Tag.tsx
- packages/web/src/styles/globals.css
- packages/web/src/styles/themes/colors.ts
- packages/web/src/styles/themes/fonts.ts
- packages/web/src/styles/themes/index.ts
- packages/web/src/styles/themes/round.ts
- packages/web/src/styles/themes/shadow.ts
> #2 Basic setup for onboarding task

- packages/web/src/common/components/Header/index.tsx
- packages/web/src/common/components/NavTools/NavItem.tsx
- packages/web/src/common/components/NavTools/NavList.tsx
- packages/web/src/common/components/NavTools/NavSubItem.tsx
- packages/web/src/common/components/NavTools/NavSubMenu.tsx
- packages/web/src/constants/paths.ts
- packages/web/src/styles/themes/colors.ts
> feat: create navsubmenu

- packages/web/src/common/components/Button.tsx
- packages/web/src/common/components/Checkbox.tsx
- packages/web/src/common/components/Radio/RadioButton.tsx
- packages/web/src/common/components/Radio/RadioOption.tsx
- packages/web/src/common/components/Radio/index.tsx
- packages/web/src/styles/themes/colors.ts
It closes #32 
```
const [value, setValue] = useState<"option1" | "option2" | "option3">(
"option1",
);
<Radio value={value} onChange={setValue}>
<Radio.Option value="option1">Option 1</Radio.Option>
<Radio.Option value="option2">Option 2</Radio.Option>
<Radio.Option value="option3">Option 3</Radio.Option>
</Radio>
```
typing은 선택
- 없음
> 32 impl button components

- .gitignore
- .vscode/typescriptreact.code-snippets
> feat: add template snippet

- package.json
- packages/web/src/common/components/Calendar/Calendar.tsx
- packages/web/src/common/components/Calendar/_atomic/CalendarDate.tsx
- packages/web/src/common/components/Calendar/_atomic/CalendarWeek.tsx
- packages/web/src/common/components/Calendar/_atomic/MonthNavigator.tsx
- packages/web/src/common/components/Icon.tsx
- packages/web/src/styles/themes/colors.ts
- packages/web/src/utils/Date/actualDate.ts
- pnpm-lock.yaml
It closes #82 
`data-fns `사용
`<CalendarDate date={1} exist={false} type="Past/Future" size="lg"/>
`
아래 `CalendarDateProps` 참고
```
interface CalendarDateProps {
date: number;
exist: boolean;
type?: "Default" | "Pass" | "Start" | "End" | "Selected" | "Past/Future";
size?: "lg" | "md" | "sm";
}
```
```
const weekData: Array<{
date: number;
exist: boolean;
type?: "Start" | "Default" | "End" | "Past/Future" | "Pass" | "Selected";
}> = [
{ date: 31, exist: true, type: "Past/Future" },
{ date: 1, exist: true, type: "Start" },
{ date: 2, exist: true, type: "Pass" },
{ date: 3, exist: true, type: "Pass" },
{ date: 4, exist: true, type: "End" },
{ date: 5, exist: true, type: "Default" },
{ date: 6, exist: false, type: "Selected" },
];
<CalendarWeek week={weekData} size="md" />
```
```
// actualDate …
```
> 82 impl common calendar component

- packages/web/src/common/components/TextButton.tsx
It closes #85 
```
<TextButton text="버튼"/>
<TextButton text="버튼" disabled onClick={onClick}/>
```
- 없음
> feat: impl textbutton

- packages/web/src/common/components/Calendar/Calendar.tsx
- packages/web/src/common/components/Calendar/_atomic/CalendarDate.tsx
- packages/web/src/common/components/Calendar/_atomic/CalendarWeek.tsx
- packages/web/src/common/components/Calendar/_atomic/MonthNavigator.tsx
- packages/web/src/common/components/TextButton.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/SelectRangeCalendar.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/RangeCalendar.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/SelectRange.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/SelectRangeInfo.tsx
- packages/web/src/styles/globals.css
- packages/web/src/utils/Date/actualDate.ts
It closes #65 
```
const [rentalDate, setRentalDate] = useState<Date | undefined>();
const [returnDate, setReturnDate] = useState<Date | undefined>();
const handleDatesChange = (rentalDatefromCal: Date | undefined, returnDatefromCal: Date | undefined) => {
setRentalDate(rentalDatefromCal);
setReturnDate(returnDatefromCal);
};
<SelectRangeCalendar onDatesChange={handleDatesChange} />
```
- #69
> impl calendar with selected range

- packages/web/src/features/rental-business/components/ItemButton.tsx
- packages/web/src/features/rental-business/components/ItemButtonList.tsx
- packages/web/src/features/rental-business/components/RentalList.tsx
- packages/web/src/features/rental-business/components/Rentals/Easel.tsx
- packages/web/src/features/rental-business/components/Rentals/HandCart.tsx
- packages/web/src/features/rental-business/components/Rentals/Mat.tsx
- packages/web/src/features/rental-business/components/Rentals/Tool.tsx
- packages/web/src/features/rental-business/components/Rentals/Vacuum.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/SelectRangeCalendar.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/RangeCalendar.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
- packages/web/src/features/rental-business/types/rental.ts
It closes #69 
- 대여 물품 목록 비었을 때 다음 버튼 비활성화
> 69 impl select page for rental

- packages/web/src/common/components/Calendar/Calendar.tsx
- packages/web/src/common/components/Calendar/_atomic/CalendarDate.tsx
- packages/web/src/common/components/Calendar/_atomic/CalendarWeek.tsx
- packages/web/src/common/components/Calendar/_atomic/CalendarWeekdays.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/SelectRangeCalendar.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/RangeCalendar.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/SelectRangeInfo.tsx
- packages/web/src/styles/themes/colors.ts
> 89 add calendar weekdays

- packages/web/src/common/components/Calendar/_atomic/CalendarWeek.tsx
- packages/web/src/common/components/Calendar/_atomic/CalendarWeekdays.tsx
It closes #89 
커밋 하나가 적용이 안 된 걸 뒤늦게 깨달아서 추가로 PR 열었습니다
- 없음
> fix: delete unused height css

- packages/web/src/common/components/Checkbox.tsx
- packages/web/src/common/components/Icon.tsx
> 104 fix disabled checkbox style

- packages/web/src/common/components/Table/TableButtonCell.tsx
- packages/web/src/common/components/Table/TableCell.tsx
- packages/web/src/common/components/Table/TableRowNone.tsx
- packages/web/src/common/components/Tag.tsx
It closes #111 
```
<TableCell type="Default">longlonglonglonglonglonglongtext</TableCell>
{/* width 기본 150px */}
<TableCell type="None" width="fill">
none
</TableCell>
<TableCell type="Tag" width={200}>
<Tag color="GREEN">Active</Tag>
</TableCell>
<TableButtonCell text={["button"]} width="100%" onClick={[() => {}]} />
<TableButtonCell
text={["button1", "button2"]}
width="200px"
onClick={[() => {}, () => {}]}
/>
<TableCell type="Header"  width="150px">header</TableCell>
<TableCell type="HeaderSort" width="150px">headersort</TableCell>
<TableRowNone />
<TableRowNone text="rowrowrow" />
```
- 페이지별 Table 구현
> 111 impl table components

- packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/TimeSlotList.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
- packages/web/src/features/printing-business/frame/PrintingBusinessMainFrame.tsx
It closes #137 
이전 PR #91 에서 마지막에 푸쉬하지 못한 커밋들입니다... 수정내용은 다음과 같습니다.
- 시각선택 버튼 반응형 적용 완료되었고, 디폴트로 가장 빨리 받을 수 있는 시간(당일 21:00)으로 설정했습니다.
- 인쇄 목적을 비워둘 경우 에러메세지가 발생하며, 신청 버튼이 비활성화 됩니다.
- 없음
> 137 impl printing business page - enhancement

- packages/web/src/common/components/Typography.tsx
It closes #141 
Typography.tsx에서 P_B가 중복으로 정의되어 있던 문제 해결
- 없음
> fix: delete duplicated P_B

- packages/web/src/app/manage-club/funding/page.tsx
- packages/web/src/common/components/Table/TableCell.tsx
- packages/web/src/constants/manageClubFunding.ts
- packages/web/src/features/manage-club/funding/component/NewFundingListSection.tsx
- packages/web/src/features/manage-club/funding/component/PastFundingListSection.tsx
- packages/web/src/features/manage-club/funding/component/_atomic/FoldableSectionTitle.tsx
- packages/web/src/features/manage-club/funding/component/_atomic/NewFundingListTable.tsx
- packages/web/src/features/manage-club/funding/component/_atomic/PastFundingListTable.tsx
- packages/web/src/features/manage-club/funding/component/_atomic/PastSingleSemesterFundingListSection.tsx
- packages/web/src/features/manage-club/funding/frame/ManageClubFundingMainFrame.tsx
It closes #117 
해당 과제에 대한 디자인 구현이 마무리되었습니다.
컴포넌트간 인터페이스는 API 나오고 구현하는게 좋을것 같아서 mock data도 전부 아무데나 뿌려진 상태에요...
데이터 전달하는 경로만 todo로 표기해둔 상태입니다.
> 117 Impl Manage Club > Funding List Page

- packages/api/src/common/util/exception.filter.ts
- packages/api/src/feature/club/club.exception.ts
- packages/api/src/main.ts
exceptionfilter를 작업한 브랜치가 너무 오래전 dev를 가져온 브랜치라서 conflict해결하기보다 새로 작업하는게 빠를 것 같아서 브랜치를 새로 만들었습니다.
It closes #46 
- 없음
> feat: re-impl-exceptionfilter

- packages/interface/src/api/club/endpoint/apiClb001.ts
- packages/interface/src/api/club/endpoint/apiClb002.ts
- packages/interface/src/api/club/endpoint/apiClb003.ts
- packages/interface/src/common/enum/club.enum.ts
- packages/web/src/common/components/Typography.tsx
- packages/web/src/features/clubDetails/components/ClubInfoCard.tsx
- packages/web/src/features/clubDetails/services/_mock/mockupClubDetail.ts
- packages/web/src/features/clubs/components/ClubCard.tsx
- packages/web/src/features/clubs/frames/ClubsPageMainFrame.tsx
- packages/web/src/features/clubs/services/_mock/mockupClubData.ts
- packages/web/src/features/clubs/services/clubTypeControl.ts
- packages/web/src/features/my/frames/MyPageMainFrame.tsx
- packages/web/src/features/my/service/_mock/mockMyClubList.ts
- packages/web/src/types/clubdetail.types.ts
CLB001, 002, 003 API의 response 수정에 따른 변화 적용입니다.
변경 이후 정상작동을 확인한 feature는 다음과 같습니다.
- clubs
- my
- clubDetails
만약 추가적으로 club API를 활용하는 feature가 있다면, 추가 수정하도록 하겠습니다.
It closes #139 
- 없음
> 139 fix ClubTypeEnum and add isPermanent

- packages/interface/src/api/activity-certificate/endpoint/apiAcf003.ts
- packages/interface/src/api/common-space/endpoint/apiCms006.ts
- packages/interface/src/api/promotional-printing/endpoint/apiPrt001.ts
- packages/interface/src/api/rental/endpoint/apiRnt003.ts
- packages/interface/src/common/enum/activityCertificate.enum.ts
- packages/interface/src/common/enum/commonSpace.enum.ts
- packages/interface/src/common/enum/promotionalPrinting.enum.ts
- packages/interface/src/common/enum/rental.enum.ts
위 API들에 관한 인터페이스 구현입니다.
지난 회의 이후 결정한 컨벤션에 맞추어 시트와 인터페이스에 변경점이 조금씩 있습니다.
유심히 검토가 필요한 부분은 주석으로 이견을 구하고 있습니다.
It closes #119 
- 없음
> 119 add RNT003, PRT001, ACF003, CMS006 and matched Enums

- packages/api/src/drizzle/schema/club.schema.ts
It closes #155 
- #121  수정사항에 맞추어 변경
> fix: datetime interface

- packages/interface/src/api/club/endpoint/apiClb009.ts
- packages/interface/src/api/club/endpoint/apiClb010.ts
- packages/interface/src/api/club/index.ts
interface를 짜보는게 처음이라서 맞게 짠건지 확인 부탁드립니다...
- 없음
> Impl api Clb009 Clb010 interface

- packages/interface/src/api/rental/endpoint/apiRnt002.ts
> fix: fix rnt002

- packages/web/src/common/components/Card.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
- packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
- packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
- packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
- packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoThirdFrame.tsx
- packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
#59 Card Component Refactoring
변경사항:
1. `Card Component`의 기존 속성 `type?: "default" | "outline"`를 `outline?: boolean"`으로 변경
2. 연관된 Card 컴포넌트 사용하는 곳 수정
- 클럽 상세페이지
- 클럽 페이지
- 마이페이지
1. 위의 스크린샷에 있는 카드 컴포넌트 사용되는 곳 shadow 잘 들어가 있는지 확인
2. 그 외에 다른 페이지에서도 에러가 없는지, 수정 안된 부분 있는지 확인
- 없음
> Card Component Refactoring

- .eslintrc
- .github/workflows/ci.yml
- .prettierignore
- package.json
- packages/interface/src/api/_example/_endpoints/apiTmp000.ts
- packages/web/src/features/notices/services/_mock/mockupNoticeList.ts
- pnpm-lock.yaml
> feat: add .github ci workflow

- packages/interface/src/api/promotional-printing/endpoint/apiPrt001.ts
It closes #170 
아직 front에 사용한 파트가 없어 인터페이스 수정 선에서 완료할 수 있을 것 같습니다.
- 없음
> 170 Fix PRT001 parameters and attributes

- packages/api/src/common/repository/club.repository.ts
- packages/api/src/drizzle/schema/club.schema.ts
- packages/api/src/drizzle/schema/user.schema.ts
- packages/api/src/feature/club/repository/club.club-room-t.repository.ts
- packages/api/src/feature/club/service/club.service.ts
> fix: db schema

- packages/api/src/app.module.ts
- packages/api/src/drizzle/schema/rental.schema.ts
- packages/api/src/feature/rental/controller/rental.controller.ts
- packages/api/src/feature/rental/rental.module.ts
- packages/api/src/feature/rental/repository/rental.rental-object.repository.ts
- packages/api/src/feature/rental/service/rental.service.ts
> feat:  impl Rental Schema and RNT-001

- packages/api/src/app.module.ts
- packages/api/src/drizzle/drizzle.provider.ts
- packages/api/src/drizzle/schema/promotional-printing.schema.ts
- packages/api/src/feature/promotional-printing/controller/promotional-printing.controller.ts
- packages/api/src/feature/promotional-printing/dto/promotional-printing.dto.ts
- packages/api/src/feature/promotional-printing/promotional-printing.module.ts
- packages/api/src/feature/promotional-printing/repository/promotional-printing-order-size.repository.ts
- packages/api/src/feature/promotional-printing/repository/promotional-printing-order.repository.ts
- packages/api/src/feature/promotional-printing/repository/promotional-printing.repository.ts
- packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
- packages/interface/src/api/promotional-printing/endpoint/apiPrt001.ts
It closes #162
아직 devDB 이용한 테스트가 이루어지지 않은 관계로 draft 상태입니다.
- 테스트 더 많이 하기
> 162 Implement PromotionalPrinting Schema and PRT-001

- packages/interface/src/api/activity-certificate/endpoint/apiAcf001.ts
> fix: fix acf001 phoneNumber

- packages/interface/src/common/enum/activityCertificate.enum.ts
- packages/interface/src/common/enum/promotionalPrinting.enum.ts
> fix: fix received enum

- packages/api/src/common/pipes/zod-pipe.ts
- packages/api/src/feature/rental/controller/rental.controller.ts
- packages/interface/src/api/rental/endpoint/apiRnt001.ts
- rnt-001 api를 예시로 구현했습니다.
It closes #178 
- 없음
> feat: zod pipe

- packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
> fix: typography error

- packages/web/src/common/components/ProgressCheckSection/_atomic/Progress.tsx
- packages/web/src/common/components/ProgressCheckSection/_atomic/ProgressDot.tsx
- packages/web/src/common/components/ProgressCheckSection/_atomic/ProgressLine.tsx
- packages/web/src/common/components/ProgressCheckSection/index.tsx
- packages/web/src/common/components/Typography.tsx
- packages/web/src/utils/Date/formateDate.ts
It closes #231 
```
<ProgressCheckSection
labels={["신청", "승인", "대여", "반납"]}
status={[Status.Approved, Status.Canceled, Status.NotYet, Status.NotYet]}
dates={[new Date(), new Date(), undefined, undefined]}
/>
```
- 없음
> impl progress state checker

- packages/api/src/common/repository/club.repository.ts
- packages/api/src/feature/club/controller/club.controller.ts
> 240-fix: clb-001 zod error

- packages/web/src/app/layout.tsx
- packages/web/src/common/components/Header/_atomic/Login.tsx
- packages/web/src/common/components/MyMenu/_atomic/Profile.tsx
- packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
- packages/web/src/common/components/MyMenu/index.tsx
- packages/web/src/common/components/NavTools/MobileNavMenu.tsx
- packages/web/src/common/providers/AuthContext.tsx
It closes #217 
`import { useAuth } from "@sparcs-clubs/web/common/providers/AuthContext";
`
`  
const { isLoggedIn, login, logout } = useAuth();
`
`isLoggedIn`이 로그인 여부, `login`, `logout`은 각각 로그인 로그아웃 함수입니다. layout 전체에 AuthContext를 넣어놔서 위에 코드만 가져다 쓰시면 돼요
- localStorage에 값 넣기
> impl login profile selection

- packages/web/src/common/components/NavTools/MobileNavMenu.tsx
> feat: impl nav close

- packages/api/src/common/repository/club.club-t.respository.ts
- packages/api/src/common/repository/club.repository.ts
- packages/api/src/drizzle/schema/club.schema.ts
- packages/api/src/env.ts
- packages/api/src/main.ts
- packages/interface/src/common/enum/club.enum.ts
- packages/web/src/features/clubDetails/services/_mock/mockupClubDetail.ts
- packages/web/src/features/clubs/services/_mock/mockupClubData.ts
- packages/web/src/features/my/service/_mock/mockMyClubList.ts
> 261 put dev db data and change schema

- packages/web/src/features/manage-club/activity-certificate/frame/ManageCertificateDetailFrame.tsx
- packages/web/src/features/manage-club/common-space/frame/ManageCommonSpaceDetailFrame.tsx
- packages/web/src/features/manage-club/component/ManageFrameWrapper.tsx
- packages/web/src/features/manage-club/printing/frame/ManagePringtingDetailFrame.tsx
- packages/web/src/features/manage-club/rental/frame/ManageRentalDetailFrame.tsx
> fix: fix frame gap

- packages/web/src/common/providers/AuthContext.tsx
> feat: impl login localstorage

- packages/api/src/common/repository/club.club-student-t.repository.ts
- packages/api/src/common/repository/club.repository.ts
- packages/api/src/common/util/exception.filter.ts
- packages/api/src/drizzle/schema/promotional-printing.schema.ts
- packages/api/src/drizzle/schema/user.schema.ts
- packages/api/src/feature/club/controller/club.controller.ts
- packages/api/src/feature/club/repository/club.club-representative-d.repository.ts
- packages/api/src/feature/club/repository/club.division-permanent-club-d.repository.ts
- packages/api/src/feature/club/service/club.service.ts
- packages/interface/src/api/club/endpoint/apiClb003.ts
- packages/web/src/features/clubDetails/components/ClubInfoCard.tsx
- pnpm-lock.yaml
clb-001, clb-002, clb-003의 TODO 및 사소한 버그 해결
- 없음
> 271 fix clb 001 clb 002 clb 003

- packages/web/src/common/components/Header/_atomic/Login.tsx
- packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
- packages/web/src/common/components/MyMenu/index.tsx
> feat: impl mymenu onclose

- packages/api/src/common/repository/club.club-student-t.repository.ts
- packages/api/src/common/repository/user.repository.ts
- packages/api/src/drizzle/drizzle.provider.ts
- packages/api/src/drizzle/schema/notice.schema.ts
- packages/api/src/drizzle/schema/user.schema.ts
- packages/api/src/feature/user/controller/user.controller.ts
- packages/api/src/feature/user/service/user.service.ts
- packages/api/src/feature/user/user.module.ts
- packages/interface/src/api/user/endpoint/apiUsr001.ts
> feat: api usr-001

- packages/web/src/features/landing/frames/MainPageMainFrame.tsx
- packages/web/src/features/landing/frames/ServiceSectionFrame.tsx
> feat: main page responsive

- packages/web/src/features/manage-club/component/ActivityCertificateTable.tsx
- packages/web/src/features/manage-club/component/ActivityReportTable.tsx
- packages/web/src/features/manage-club/component/CommonSpaceTable.tsx
- packages/web/src/features/manage-club/component/FundingTable.tsx
- packages/web/src/features/manage-club/component/MembersTable.tsx
- packages/web/src/features/manage-club/component/PrintingTable.tsx
- packages/web/src/features/manage-club/component/RentalTable.tsx
- packages/web/src/features/my/component/MyActivityCertificateTable.tsx
- packages/web/src/features/my/component/MyCommonSpaceTable.tsx
- packages/web/src/features/my/component/MyPrintingTable.tsx
- packages/web/src/features/my/component/MyRentalTable.tsx
- packages/web/src/utils/getTagDetail.ts
It closes #228 
```
const TagList: {
[key in ActivityStatusEnum]: StatusDetail;
} = {
[ActivityStatusEnum.Writing]: { text: "작성 중", color: "BLUE" },
[ActivityStatusEnum.Applied]: { text: "신청 완료", color: "PURPLE" },
[ActivityStatusEnum.Approved]: { text: "승인 완료", color: "GREEN" },
[ActivityStatusEnum.Rejected]: { text: "신청 반려", color: "RED" },
};
```
{fundingList.map((funding, index) => {
const { color, text } = getTagDetail(funding.status, TagList);
return (
<TableRow key={funding.name + String(index)} isBorder>
<TableCell type="Tag" width="10%" minWidth={116}>
<Tag color={color}>{text}</Tag>
</TableCell>
</TableRow>
);
})}
- 없음
> refactor tag color mapping

- packages/web/src/features/credits/credits.ts
- packages/web/src/features/credits/frames/CreditsMainFrame.tsx
> credits member sorting

- packages/interface/src/api/activity-certificate/endpoint/apiAcf005.ts
- packages/interface/src/api/activity-certificate/endpoint/apiAcf006.ts
It closes #300
- acf006의 정상 응답 코드가 명시되어 있지 않아 일단 200으로 작성했는데 확인 부탁드립니다. 
- 없음
> impl acf 005 006 interface

- packages/api/src/feature/promotional-printing/controller/promotional-printing.controller.ts
- packages/api/src/feature/promotional-printing/dto/promotional-printing.dto.ts
- packages/api/src/feature/promotional-printing/repository/promotional-printing-order-size.repository.ts
- packages/api/src/feature/promotional-printing/repository/promotional-printing-order.repository.ts
- packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
- packages/interface/src/api/promotional-printing/endpoint/apiPrt005.ts
- packages/interface/src/api/promotional-printing/index.ts
It closes #306 
url: http://localhost:8000/student/promotional-printings/orders/my?pageOffset=1&itemCount=2
```JSON
{
"items": [
{
"id": 4,
"studentName": "김택진",
"status": 1,
"desiredPickUpDate": "2024-05-16T08:00:00.000Z",
"pickUpTime": null,
"createdAt": "2024-06-26T20:45:03.000Z",
"orders": [
{
"promotionalPrintingSizeEnum": 1,
"numberOfPrints": 10
},
{
"promotionalPrintingSizeEnum": 2,
"numberOfPrints": 5
}
]
},
{
"id": 3,
"studentName": "김택진",
"status": 1,
"desiredPickUpDate": "2024-05-16T08:00:00.000Z",
"pickUpTime": null,
"createdAt": "2024-06-26T20:44:57.000Z",
"orders": [
{
"promotionalPrintingSizeEnum": 1,
"numberOfPrints": 10
},
{
"promotionalPrintingSizeEnum": 2,
"numberOfPrints": 5
}
]
}
],
"offset": 1,
"total": 4
}
```
url: …
> Implement PRT-005 interface and API

- packages/web/src/common/components/Pagination.tsx
- packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
- packages/web/src/features/manageClubTable/frames/ManageClubTableMainFrame.tsx
- packages/web/src/features/notices/frames/NoticeListAndPaginationFrame.tsx
> pagination component refactoring

- packages/web/src/app/my/activity-certificate/[id]/page.tsx
- packages/web/src/app/my/activity-certificate/page.tsx
- packages/web/src/app/my/common-space/[id]/page.tsx
- packages/web/src/app/my/common-space/page.tsx
- packages/web/src/app/my/printing-business/[id]/page.tsx
- packages/web/src/app/my/printing-business/page.tsx
- packages/web/src/app/my/rental-business/[id]/page.tsx
- packages/web/src/app/my/rental-business/page.tsx
- packages/web/src/common/components/Pagination.tsx
- packages/web/src/common/components/Table/TableCell.tsx
- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/manage-club/component/ActivityCertificateTable.tsx
- packages/web/src/features/manage-club/component/ActivityReportTable.tsx
- packages/web/src/features/manage-club/component/CommonSpaceTable.tsx
- packages/web/src/features/manage-club/component/FundingTable.tsx
- packages/web/src/features/manage-club/component/MembersTable.tsx
- packages/web/src/features/manage-club/component/PrintingTable.tsx
- packages/web/src/features/manage-club/component/RentalTable.tsx
- packages/web/src/features/my/activity-certificate/frame/MyCertificateDetailFrame.tsx
- packages/web/src/features/my/common-space/frame/MyCommonSpaceDetailFrame.tsx
- packages/web/src/features/my/component/MyActivityCertificateTable.tsx
- packages/web/src/features/my/component/MyCommonSpaceTable.tsx
- packages/web/src/features/my/component/MyPrintingTable.tsx
- packages/web/src/features/my/component/MyRentalTable.tsx
- packages/web/src/features/my/component/MyServiceTable.tsx
- packages/web/src/features/my/printing-business/frame/MyPrintingDetailFrame.tsx
- packages/web/src/features/my/rental-business/frame/MyRentalDetailFrame.tsx
> impl my page service pages

- packages/api/src/common/repository/club.repository.ts
- packages/api/src/feature/club/repository/club.club-representative-d.repository.ts
- packages/api/src/feature/promotional-printing/controller/promotional-printing.controller.ts
- packages/api/src/feature/promotional-printing/promotional-printing.module.ts
- packages/api/src/feature/promotional-printing/repository/promotional-printing-order.repository.ts
- packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
- packages/interface/src/api/promotional-printing/endpoint/apiPrt003.ts
- packages/interface/src/api/promotional-printing/index.ts
It closes #310 
작성자 ID: 605(clubId 57, 9, 23 소속)
URL: http://localhost:8000/student/promotional-printings/orders/order/5
```JSON
{
"order": {
"clubId": 1,
"studentId": 605,
"status": 1,
"orders": [
{
"promotionalPrintingSizeEnum": 1,
"numberOfPrints": 10
},
{
"promotionalPrintingSizeEnum": 2,
"numberOfPrints": 5
}
],
"isColorPrint": true,
"fitPrintSizeToPaper": false,
"requireMarginChopping": true,
"desiredPickUpDate": "2024-05-16T08:00:00.000Z",
"createdAt": "2024-06-29T10:54:20.000Z"
}
}
```
URL: http://localhost:8000/student/promotional-printings/orders/order/3
```JSON
{
"message": "permission denied",
"statusCode": 403,
"timestamp": "2024-06-29T12:10:45.870Z",
"path": "/student/promotional-printings/orders/order/3"
}
```
본인이 작성한 신청이나 신청에 대항하는 동아리의 현재 대표자가 아닌 경우
*대표에 조회에 대한 추가 테스트가 …
> feat: implement PRT-003

- packages/web/src/app/my/printing-business/page.tsx
- packages/web/src/features/manage-club/component/PrintingTable.tsx
- packages/web/src/features/my/component/MyPrintingTable.tsx
- packages/web/src/utils/getPrintSize.ts
> refactor getPrintSize

- packages/api/src/feature/club/club.module.ts
- packages/api/src/feature/club/repository/club.club-student-t.repository.ts
- packages/api/src/feature/club/repository/club.semester-d.repository.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/api/src/feature/club/service/club.service.ts
- packages/api/src/feature/common-space/common-space.module.ts
- packages/api/src/feature/common-space/service/common-space.service.ts
- packages/api/src/feature/user/service/user.service.ts
- packages/api/src/feature/user/user.module.ts
It closes #342 
- club 모듈 외부에서 studentT repository가 주입되는 케이스를 없애야 합니다.
> Remove studentT repository injection from common to club module

- packages/web/src/app/my/activity-certificate/page.tsx
- packages/web/src/app/my/common-space/page.tsx
- packages/web/src/app/my/printing-business/page.tsx
- packages/web/src/app/my/rental-business/page.tsx
- packages/web/src/features/my/component/MyServiceTable.tsx
It closes #333 
- contents length가 pageLimit의 배수일 경우 마지막 빈 페이지 생기는 문제 해결
- div로 th 감싸는 문제 해결
- my service 이외의 table에도 확장하여 사용 가능할 것으로 보임
> table component refactoring

- packages/web/src/common/components/ProgressCheckSection/index.tsx
- packages/web/src/common/components/ProgressStatus.tsx
- packages/web/src/features/manage-club/activity-certificate/frame/ManageCertificateDetailFrame.tsx
- packages/web/src/features/manage-club/common-space/frame/ManageCommonSpaceDetailFrame.tsx
- packages/web/src/features/manage-club/printing/frame/ManagePrintingDetailFrame.tsx
- packages/web/src/features/manage-club/rental/frame/ManageRentalDetailFrame.tsx
- packages/web/src/features/my/activity-certificate/frame/MyCertificateDetailFrame.tsx
- packages/web/src/features/my/common-space/frame/MyCommonSpaceDetailFrame.tsx
- packages/web/src/features/my/printing-business/frame/MyPrintingDetailFrame.tsx
- packages/web/src/features/my/rental-business/frame/MyRentalDetailFrame.tsx
It closes #335 
```
<ProgressStatus
labels={["신청 완료", "사용 대기"]} // 존재하는 label 목록
status={[Status.Approved]} // 완료된 label의 상태 목록
dates={[new Date()]} // 완료된 label의 날짜 목록
infoText="사용 일시가 지나기 전까지 신청을 취소할 수 있습니다"
/>
```
- 반려 사유 작성이 존재하는 신청 상태의 경우 어떻게 처리할지
> impl progressStatus

- packages/web/src/app/manage-club/activity-certificate/page.tsx
- packages/web/src/app/manage-club/common-space/page.tsx
- packages/web/src/app/manage-club/funding/page.tsx
- packages/web/src/app/manage-club/printing-business/page.tsx
- packages/web/src/app/manage-club/rental-business/page.tsx
- packages/web/src/features/manage-club/funding/frame/ManageClubFundingMainFrame.tsx
- packages/web/src/features/manageClubTable/frames/ManageClubTableMainFrame.tsx
It closes #331 
1. 수정사항 문제없는지
- 대표 동아리 관리 > 하위 4개의 페이지 
- (대여사업 신청내역, 홍보물 인쇄 내역, 활동확인서 발급 내역, 공용공간 비정기사용 내역)
2. 그 외에 더 수정이 필요한 페이지가 있는지
- 없음
> fix: move pagehead component into flexWrapper component

- packages/web/src/features/manage-club/funding/create/components/NonCorpEvidenceBlock.tsx
- packages/web/src/features/manage-club/funding/create/components/TransportEvidenceBlock.tsx
- packages/web/src/features/manage-club/funding/create/frame/AddEvidenceFrame.tsx
It closes #354 #218 
이슈 나누는 과정에서 비법인 증빙 관련 컴포넌트를 빠뜨려 이 이슈에서 함께 작업함.
- addEvidenceFrame 부분 state 관련 코드 refactoring
> impl transportation evidence block

- packages/web/package.json
- packages/web/src/common/components/Modal/ModalExample.tsx
- packages/web/src/common/components/Modal/index.tsx
- packages/web/src/common/providers/UseClientProvider.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/SelectRangeCalendar.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/RangeCalendar.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/SelectRange.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/index.tsx
- pnpm-lock.yaml
It closes #320 
- 공통 컴포넌트 사용문서에도 업그레이드 완료. 
-  https://www.notion.so/sparcs/Modal-tsx-a157ff9797684326b8d13c0bf7356e96
- 부족한 정보가 있다면 코멘트 부탁드립니다
- 없음
> 320 modal refactoring

- packages/web/src/constants/paths.ts
> feat: add link to credits page

- packages/web/src/features/credits/credits.ts
It closes #371 
Commit message 작성이나 PR Label 선택 등, Merge 전까지의 전반적인 흐름에 대한 피드백을 받고 싶습니다
- 없음
> feat: credit for daystar

- packages/web/src/features/register-club/components/RulesButton.tsx
- packages/web/src/features/register-club/components/SingleUploadWithTextAndTemplate.tsx
> impl register club subpage components

- packages/web/src/constants/changeRepresentative.ts
- packages/web/src/features/manage-club/component/ChangeRepresentative.tsx
- packages/web/src/features/manage-club/component/ChangeRepresentativeCard.tsx
- packages/web/src/features/manage-club/frame/_atomic/InfoManageFrame.tsx
- packages/web/src/features/my/component/ChangeRepresentativeModalContent.tsx
- packages/web/src/features/my/component/MyChangeRepresentative.tsx
- packages/web/src/styles/themes/colors.ts
It closes #315 
```
<ChangeRepresentativeCard
type="Default"
selectItems={selectItems}
representative={representative}
setRepresentative={setRepresentative}
delegate1={delegate1}
setDelegate1={setDelegate1}
delegate2={delegate2}
setDelegate2={setDelegate2}
/>
```
```
<MyChangeRepresentative
type="Requested"
clubName="술박스"
prevRepresentative="20210000 박병찬"
newRepresentative="20200000 이지윤"
/>
<MyChangeRepresentative
type="Finished"
clubName="술박스"
prevRepresentative="20210000 박병찬"
newRepresentative="20200000 이지윤"
/>
```
```
<Modal isOpen>
<ChangeRepresentativeModalContent
type="PhoneNumber"
clubName="술박스"
prevRepresentative="20210000 박병찬"
newRepresentative="20200000 이지윤"
phoneValue={phone}
onPhoneChange={setPhone}
/>
</Modal>
```
- 없음
> impl additional UI for changing representative delegate

- packages/interface/src/api/funding/endpoint/apiFnd004.ts
- packages/interface/src/api/funding/endpoint/apiFnd005.ts
- packages/interface/src/api/funding/endpoint/apiFnd006.ts
- packages/interface/src/api/funding/index.ts
- packages/interface/src/common/enum/funding.enum.ts
> impl fnd 004-006 interface

- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
It closes #393 
import slash 2개 문제 / useEffect render 관련 문제 수정
- 없음
> fix import for rental

- packages/web/src/features/credits/credits.ts
It closes #370 
코드 수정, commit, commit message convention, push, PR 올리는 것 등 전반적인 과정이 맞게 되었는지 피드백 해주시면 감사하겠습니다.
호버 시
- 없음
> feat: chacha's credit

- packages/interface/src/api/funding/endpoint/apiFnd001.ts
- packages/interface/src/api/funding/endpoint/apiFnd002.ts
- packages/interface/src/api/funding/endpoint/apiFnd003.ts
- packages/interface/src/api/funding/index.ts
- packages/interface/src/common/enum/funding.enum.ts
It closes #391 
apiFnd001 하단에 테스트 가능한 fndTest 만들어두었습니다
- 필요시 ZodIssueCode 설정
> impl fnd 001 002 003 interface

- packages/web/src/features/credits/components/MemberCard.tsx
> Implement credit links

- packages/api/src/drizzle/schema/activity.schema.ts
- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/repository/activity.repositroy.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct001.ts
- packages/interface/src/api/activity/endpoint/apiAct004.ts
It closes #405
기존 테스트 참고 부탁드립니다!
https://github.com/academic-relations/ar-002-clubs/pull/348
- 없음
> Patch ACT-001, 005 and implement ACT-004

- packages/web/src/features/credits/credits.ts
> Add credit (malloc)

- packages/api/src/drizzle/schema/activity.schema.ts
- packages/api/src/feature/activity/activity.module.ts
- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/interface/src/api/activity/endpoint/apiAct002.ts
- packages/interface/src/api/activity/endpoint/apiAct003.ts
It closes #432 
Student Id는 605를 이용했습니다.
URL: http://localhost:8000/student/activities/activity/1
```JSON
{
"clubId": 23,
"name": "2024 글로벌 창업 아이디어 경진대회",
"originalName": "11",
"activityTypeEnumId": 1,
"location": "서울 강남구 테헤란로 123 창업지원센터",
"purpose": "글로벌 시장을 겨냥한 혁신적인 창업 아이디어 발굴 및 지원",
"detail": "3일간의 아이디어 피칭, 멘토링 세션, 네트워킹 이벤트로 구성된 창업 경진대회입니다. 참가자들은 자신의 아이디어를 발표하고 전문가들의 피드백을 받게 됩니다.",
"evidence": "참가 확인서, 발표 자료, 수상 증명서 (해당되는 경우)",
"evidenceFiles": [
{
"uuid": "550e8400-e29b-41d4-a716-446655440000"
},
{
"uuid": "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
}
],
"participants": [
{
"studentId": 15
},
{
"studentId": 226
},
{
"studentId": 267
}
],
"durations": [
{
"startTerm": "2024-06-02T00:00:00.000Z",
"endTerm": "2024-06-15T00:00:00.000Z"
},
{
"startTerm": "2024-07-01T00:00:00.000Z",
"endTerm": …
```
> Implement ACT-002 and ACT-003

- packages/web/src/features/manageClubTable/types/ManageClubTable.ts
- packages/web/src/features/manageClubTable/types/ManageClubTableConst.ts
- packages/web/src/features/manageClubTable/types/mock.ts
It closes #412 
- 시간에 따라 자동으로 status 지정하도록 하는 것?
> #412: Add "Overdue" process state tag for rental business

- .github/workflows/ci.yml
- package.json
- packages/web/src/common/components/RejectReasonToast.tsx
- packages/web/src/features/landing/frames/MainPageMainFrame.tsx
- packages/web/src/styles/themes/zIndices.ts
It closes #442 
사용법
```typescript
<RejectReasonToast
title="활동확인서 발급 내역"
reasons={[
{ datetime: "2024-05-01", reason: "활동확인서 발급 신청" },
{ datetime: "2024-05-01", reason: "활동확인서 발급 신청" },
{ datetime: "2024-05-01", reason: "활동확인서 발급 신청" },
{ datetime: "2024-05-01", reason: "활동확인서 발급 신청" },
{ datetime: "2024-05-01", reason: "활동확인서 발급 신청" },
{ datetime: "2024-05-01", reason: "활동확인서 발급 신청" },
{ datetime: "2024-05-01", reason: "활동확인서 발급 신청" },
{ datetime: "2024-05-01", reason: "활동확인서 발급 신청" },
{ datetime: "2024-05-01", reason: "활동확인서 발급 신청" },
{ datetime: "2024-05-01", reason: "활동확인서 발급 신청" },
]}
/>
```
- 없음
> Add RejectReasonToast

- packages/api/src/feature/activity/activity.module.ts
- packages/api/src/feature/activity/controller/activity.activity-term.controller.ts
- packages/api/src/feature/activity/repository/activity.activity-term.repository.ts
- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.activity-term.service.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/api/src/feature/club/repository/club.semester-d.repository.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/interface/src/api/activity/endpoint/apiAct006.ts
- packages/interface/src/api/activity/endpoint/apiAct009.ts
- packages/interface/src/api/activity/index.ts
It closes #435 
2023년 3월부터 활동한 동아리(id 23)의 활동기간 조회를 시도했습니다.
인증은 학생 id 605로 대체했습니다.
URL: GET http://localhost:8000/student/activities/activity-terms
Body
```JSON
{
"clubId": 23
}
```
```JSON
{
"terms": [
{
"id": 2,
"year": 2024,
"name": "겨울-봄",
"startTerm": "2024-01-01T07:16:56.000Z",
"endTerm": "2024-06-01T07:16:55.000Z"
},
{
"id": 3,
"year": 2023,
"name": "전체-테스트용",
"startTerm": "2023-01-01T00:00:00.000Z",
"endTerm": "2024-01-01T07:16:55.000Z"
},
{
"id": 4,
"year": 2024,
"name": "가을-테스트",
"startTerm": "2024-07-04T07:16:57.000Z",
"endTerm": "2024-11-30T00:00:00.000Z"
}
]
}
```
URL: GET http://localhost:8000/student/activities/activity-terms/activity-term/1
Body
```JSON
{
"clubId": 23
}
```
```JSON
{
"activities": [
{
"id": 1,
"name": "2024 글로벌 창업 아이디어 경진대회",
"activityTypeEnumId": 1, …
```
> Implement ACT-006, ACT-009

- packages/web/src/features/manage-club/frames/ActivityManageFrame.tsx
- packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
- packages/web/src/features/manage-club/frames/ServiceManageFrame.tsx
> Fix gap in /manage-club page

- packages/web/src/common/components/Icon.tsx
- packages/web/src/common/components/Info.tsx
> fix: icon color

- packages/web/src/features/clubs/components/ClubListGrid.tsx
It closes #472 
https://github.com/user-attachments/assets/85687442-e0ec-44c8-bbd5-894a81186d6f
- 없음
> Fix responsive view on /clubs page

- packages/web/src/features/clubs/components/ClubCard.tsx
> Show clubcard differently based on login status

- packages/interface/src/api/registration/endpoint/apiReg004.ts
- packages/interface/src/api/registration/endpoint/apiReg005.ts
- packages/interface/src/api/registration/endpoint/apiReg006.ts
- packages/interface/src/api/registration/endpoint/apiReg007.ts
- packages/interface/src/api/registration/endpoint/apiReg008.ts
- packages/interface/src/common/enum/registration.enum.ts
reg 004,005,006,007,008 interface구현 완료.
It closes #480 
- 없음
> feat: interface

- packages/interface/src/api/club/endpoint/apiClb001.ts
- packages/interface/src/api/club/endpoint/apiClb002.ts
- packages/interface/src/api/club/endpoint/apiClb003.ts
- packages/interface/src/api/club/endpoint/apiClb004.ts
- packages/interface/src/api/club/endpoint/apiClb008.ts
- packages/interface/src/api/club/endpoint/apiClb009.ts
- packages/interface/src/api/club/endpoint/apiClb010.ts
- packages/interface/src/api/club/endpoint/apiClb011.ts
- packages/interface/src/api/club/endpoint/apiClb012.ts
- packages/interface/src/api/club/endpoint/apiClb013.ts
- packages/interface/src/api/club/endpoint/apiClb014.ts
- packages/web/src/features/clubDetails/services/_mock/mockupClubDetail.ts
- packages/web/src/features/clubs/services/_mock/mockupClubData.ts
It closes #477 
api list랑 동일하게 잘 구현되었는지 확인 부탁드립니다.
- 없음
> fix clb interface

- packages/web/src/app/clubs/[id]/page.tsx
- packages/web/src/common/components/PageHead/index.tsx
- packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
It closes #451 
(1) 회원등록 기간
- 해당 동아리에 회원 등록을 안했을 때
- 해당 동아리에 회원 등록이 이미 되어 있을 때
(2) 회원 등록 기간이 아닐때
> 451 add button on clubs detail page for member registration perio

- packages/web/src/common/components/Forms/TextInput.tsx
- packages/web/src/common/components/Forms/UnitInput.tsx
- packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
> Implement UnitInput

- packages/web/src/styles/globals.css
> FoldableSectionTitle Width Exceeds The Screen on Mobile View

- packages/web/src/common/services/_mock/mockAccessToken.ts
It closes #522 
- 프로필 선택 기능 수정
> add mock profile token

- packages/api/src/drizzle/schema/meeting.schema.ts
It closes #511 
- 소켓 관련 엔드포인트 구현
> feat: impl meeting schema

- packages/web/src/app/my/page.tsx
- packages/web/src/common/components/Buttons/TextButton.tsx
- packages/web/src/common/components/NotificationCard.tsx
- packages/web/src/constants/changeDivisionPresident.ts
- packages/web/src/features/manage-division/components/ChangeDivisionPresident.tsx
- packages/web/src/features/manage-division/components/ChangeDivisionPresidentCard.tsx
- packages/web/src/features/manage-division/components/DivisionInformationCard.tsx
- packages/web/src/features/manage-division/components/_atomic/DivisionCard.tsx
- packages/web/src/features/manage-division/frames/DivisionInfoFrame.tsx
- packages/web/src/features/my/component/ChangeDivisionPresidentModalContent.tsx
- packages/web/src/features/my/component/MyChangeDivisionPresident.tsx
- packages/web/src/features/my/frame/MyChangeDivisionPresidentFrame.tsx
It closes #534 
https://github.com/user-attachments/assets/8e8be762-dd44-4cdb-b135-96af17ef9c78
- Flow 맞춰서 구현
> Change division president ui

- packages/api/src/app.module.ts
- packages/api/src/feature/division/division.controller.ts
- packages/api/src/feature/division/division.module.ts
- packages/api/src/feature/division/division.repository.ts
- packages/api/src/feature/division/division.service.ts
- packages/interface/src/api/division/apiDiv001.ts
It closes #539 
URL: http://localhost:8000/divisions
```JSON
{
"divisions": [
{
"id": 1,
"name": "생활문화",
"presidentStudentId": 605
}
]
}
```
- 없음
> Implement Division module and DIV-001 interface + API

- packages/api/src/feature/club/service/club-delegate.service.ts
- packages/interface/src/api/club/endpoint/apiClb008.ts
- packages/interface/src/common/enum/club.enum.ts
- packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
- packages/web/src/features/manage-club/services/_mock/mockDelegate.ts
It closes #531 
President / Representative -> Representative / Delegate로 enum 용어 수정
- 없음
> modify clubdelegateenum

- packages/web/src/app/clubs/[id]/page.tsx
- packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
It closes #542 
로그인
로그인 X
- 없음
> impl login change for clubs/id

- packages/web/src/common/components/Responsive/index.tsx
- packages/web/src/styles/globals.css
> Update css variables

- packages/api/src/drizzle/schema/funding.schema.ts
- packages/api/src/drizzle/schema/meeting.schema.ts
- packages/api/src/feature/file/file.module.ts
> fix: nest error

- packages/api/src/drizzle/drizzle.provider.ts
- packages/api/src/feature/file/controller/file.controller.ts
- packages/api/src/feature/file/service/file.service.ts
- packages/interface/src/api/file/endpoint/apiFil001.ts
- packages/interface/src/api/file/endpoint/apiFil002.ts
It closes #558 
URL: http://localhost:8000/files/upload
Body
```JSON
{
"metadata": [
{
"name": "document1.pdf",
"type": "application/pdf",
"size": 1024
},
{
"name": "image1.jpg",
"type": "image/jpeg",
"size": 2048
},
{
"name": "spreadsheet.xlsx",
"type": "image/jpeg",
"size": 4096
}
]
}
```
```JSON
{
"urls": [
{
"uploadUrl": "혹시몰라가려둠",
"fileId": "afda1501-5a88-44c5-bf1b-42e781a11564"
},
{
"uploadUrl": "혹시몰라가려둠",
"fileId": "847c249a-667f-4b69-90e6-5e728622beea"
},
{
"uploadUrl": "혹시몰라가려둠",
"fileId": "0bc192f7-e4cd-4ac7-a7d5-82de02436c90"
}
]
}
```
이전에 셋중 하나에만 이미지 파일을 업로드해둔 상태입니다
URL: http://localhost:8000/files/metadata
Body
```JSON
{
"files": [
{
"fileId": "dc2f1f43-cfb1-425e-86a9-212e2489547f"
},
{
"fileId": "7bef4359-02f1-461c-8796-9e5cbc778191"
},
{
"fileId": …
```
> Implement new filed Upload & validation API

- packages/web/src/app/manage-division/page.tsx
- packages/web/src/app/my/page.tsx
- packages/web/src/features/manage-division/components/ChangeDivisionPresidentCard.tsx
It closes #544 
실수로 local change를 push 안하고 머지해버려서 다시 올릴게요 :sweat_smile: 
- 없음
> Add TODO comments

- packages/web/src/app/my/page.tsx
- packages/web/src/common/components/Buttons/FoldUnfoldButton.tsx
- packages/web/src/common/components/Buttons/TextButton.tsx
- packages/web/src/constants/changeDivisionPresident.ts
- packages/web/src/features/manage-club/frames/ActivityManageFrame.tsx
- packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
- packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
- packages/web/src/features/manage-club/frames/ServiceManageFrame.tsx
- packages/web/src/features/manage-club/funding/components/NewFundingListSection.tsx
- packages/web/src/features/manage-club/funding/components/PastFundingListSection.tsx
- packages/web/src/features/manage-club/funding/components/_atomic/PastSingleSemesterFundingListSection.tsx
- packages/web/src/features/manage-club/funding/frames/AddEvidenceFrame.tsx
- packages/web/src/features/manage-club/funding/frames/BasicEvidenceFrame.tsx
- packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
- packages/web/src/features/manage-club/members/components/AllMemberList.tsx
- packages/web/src/features/manage-club/members/frames/AllMemberListFrame.tsx
- packages/web/src/features/manage-club/members/frames/RegisterMemberListFrame.tsx
- packages/web/src/features/manage-division/components/ChangeDivisionPresident.tsx
- packages/web/src/features/manage-division/components/ChangeDivisionPresidentCard.tsx
- packages/web/src/features/my/components/ChangeDivisionPresidentModalContent.tsx
- packages/web/src/features/my/components/MyChangeDivisionPresident.tsx
- packages/web/src/features/my/frames/MyClubFrame.tsx
- packages/web/src/features/my/frames/MyInfoFrame.tsx
- packages/web/src/features/my/frames/MyServiceFrame.tsx
> Use Enum type for status && MoreInfo common component

- packages/web/src/common/components/Header/_atomic/Login.tsx
- packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
- packages/web/src/common/components/MyMenu/index.tsx
It closes #524 
프로필 전환 안 되던 문제 해결
mock 켜고 테스트 해주세요
- 없음
> fix profile list selection

- packages/interface/src/api/meeting/endpoint/apiMeet001.ts
- packages/interface/src/api/meeting/endpoint/apiMeet002.ts
- packages/interface/src/api/meeting/endpoint/apiMeet003.ts
- packages/interface/src/api/meeting/endpoint/apiMeet004.ts
- packages/interface/src/api/meeting/endpoint/apiMeet005.ts
- packages/interface/src/api/meeting/index.ts
- packages/interface/src/common/enum/meeting.enum.ts
MEET 001~005 인터페이스 구현
005 request body 확인 필요
It closes #575 
- 없음
> impl meet 001~005 interface

- packages/api/src/drizzle/schema/refresh-token.schema.ts
- packages/api/src/drizzle/schema/registration.schema.ts
- packages/api/src/feature/auth/repository/auth.repository.ts
- packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
- packages/api/src/feature/registration/repository/registration.repository.ts
- index를 foreign key로 변경
- registration deadline으로 변경
- refresh token테이블 이름 변경
It closes #565 
- 없음
> 565 fix dirzzle schema

- packages/interface/src/api/activity/endpoint/apiAct007.ts
- packages/interface/src/api/activity/endpoint/apiAct008.ts
우선 interface구현 완료했습니다.
It closes #581 
- 없음
> 581 impl act 007 008 interface

- packages/web/src/common/components/Forms/TextInput.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
- packages/web/src/features/common-space/service/getCommonSpaceUsageOrders.ts
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoThirdFrame.tsx
> fix: remove unnecessary useEffect dependency

- packages/api/src/feature/club/controller/club.controller.ts
- packages/api/src/feature/common-space/controller/common-space.controller.ts
It closes #611 
CLB 001, 002, CMS 001, 002에 public decorator 추가
- 없음
> add public decorator

- packages/interface/src/api/registration/endpoint/apiReg003.ts
> Fix reg-003 url typo

- packages/web/src/features/clubDetails/components/PersonInfoCard.tsx
- packages/web/src/features/clubDetails/services/getClubDetail.ts
- packages/web/src/features/clubs/components/ClubCard.tsx
- packages/web/src/features/clubs/services/useGetClubsList.ts
> fix: club detail page for no advisor

- packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
It closes #504
큰 화면(>lg)
작은 화면
- 없음
> impl responsive design at manage-club

- packages/web/src/app/executive/register-member/page.tsx
- packages/web/src/common/components/RegisterMemberTable.tsx
- packages/web/src/features/executive/_mock/mockMemberRegistration.ts
It closes #630 
동아리 이름을 클릭하면 executive/register-member/[id] page로 이동하도록 설정.
- connect BE
> feat: impl executive/register-member page

- packages/web/src/common/components/Table.tsx
- packages/web/src/features/my/components/MyClubTable.tsx
- packages/web/src/features/my/components/MyMemberTable.tsx
It closes #638 
- Table 공통 컴포넌트에 rowLink 속성 추가, 클릭 시 설정한 path로 이동시킴
- 해당 속성을 /my의 동아리 등록, 회원 등록 테이블에 추가
- 해당 속성이 있는 행에 마우스 올리면 포인터 모양 바뀜
- 없음
> Impl row link for Table component

- packages/api/src/feature/registration/member-registration/controller/member-registration.controller.ts
- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg006.ts
> fix: reg006

- packages/web/src/app/clubs/page.tsx
> Fix location regarding info and search in /clubs

- packages/web/src/common/components/RegisterMemberTable.tsx
It closes #680
외부로 보이는 변경사항 없음.
이전에 동아리 이름 클릭 시 /[id] page로 넘어가던 기능 -> 행 전체 클릭 시 넘어가도록 변경
- 없음
> feat: impl row link to register member table

- packages/web/src/app/my/page.tsx
- packages/web/src/features/my/components/MyClubProfTable.tsx
- packages/web/src/features/my/frames/MyRegisterFrame.tsx
- packages/web/src/features/my/services/_mock/mockMyRegister.ts
> Impl prof mypage (/my)

- packages/web/src/features/landing/components/NoticeCard.tsx
- packages/web/src/features/landing/components/ServiceCard.tsx
- packages/web/src/features/landing/frames/NoticeSectionFrame.tsx
- packages/web/src/features/landing/frames/ServiceSectionFrame.tsx
> Fix responsive design on main

- packages/web/src/app/manage-club/page.tsx
- packages/web/src/features/manage-club/components/ChangeClubInfoCard.tsx
- packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
It closes #691 
렌더링 자체는 잘 되는데 에러가 떠요 ㅜㅜ
- 없음
> Impl /manage-club for delegate

- packages/web/src/features/landing/frames/NoticeSectionFrame.tsx
- packages/web/src/features/notices/components/NoticeList.tsx
It closes #660 
아까 브랜치를 잘못 열어서 삭제하고 다시 만들었습니다
- 없음
> Open new link at notice click

- packages/web/src/app/clubs/page.tsx
It closes #664
input에 한 글자 쓸 때마다 focus 풀리는 문제 해결
styled component 써서 만든 Wrapper를 밖으로 빼니 해결 되었어요
- 없음
> Fix Bug for search on /clubs

- packages/web/src/app/my/page.tsx
It closes #707 
boolean false로 바꿔서 안보이게 했는데 이렇게 하는게 맞는거겠죠..?
- 없음
> Remove change division president display on /my

- packages/api/src/feature/club/controller/club-delegate.controller.ts
- packages/api/src/feature/club/controller/club.controller.ts
- packages/api/src/feature/user/controller/user.controller.ts
It closes #705 
mock student id로 되어있던 곳 student decorator 사용해서 수정 (이번 배포에 필요한 부분만 수정함)
- 없음
> add student decorator

- packages/api/src/drizzle/drizzle.provider.ts
- packages/api/src/feature/club/repository/club.repository.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg002.ts
- packages/interface/src/api/registration/endpoint/apiReg003.ts
- packages/interface/src/api/registration/endpoint/apiReg018.ts
> reg002,003,018

- packages/web/src/common/components/Select/Dropdown.tsx
> Add max height and scrollable to Select

- packages/web/src/app/my/register-club/[id]/page.tsx
It closes #649 
다른건 다 똑같길래 삭제/수정 되어있는 것만 승인으로 바꿔서 보여지게 했습니다
isStudent boolean 값 따라서 다르게 보임
- 없음
> Add register club detail for professor

- packages/api/src/feature/file/controller/file.controller.ts
- packages/api/src/feature/file/file.module.ts
- packages/api/src/feature/file/service/file.service.ts
- packages/interface/src/api/file/apiFil002.ts
- packages/interface/src/api/file/apiFil003.ts
- packages/interface/src/api/file/endpoint/apiFil003.ts
It closes #655 
Request
```
{
"files": [
{
"fileId": "7b08bce8-98db-4288-bd1a-3d81dea4e61d"
},
{
"fileId": "87fdafdb-f018-4932-9081-0ea6e7404e1c"
},
{
"fileId": "977f0d55-f841-4417-b96e-af7cbd7736f2"
}
]
}
```
- 없음
> Implement file download

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg001.ts
- packages/interface/src/api/registration/endpoint/apiReg009.ts
- packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
> fix: reg001,009 remove studentId

- packages/web/src/lib/_axios/axiosErrorInterceptor.ts
It closes #738 
refresh 실패 시 로그아웃하고 홈으로 이동
403 forbidden error 뜨면 이전 페이지 혹은 홈으로 이동
- 없음
> handling for refresh error and forbidden

- packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg001.ts
- packages/interface/src/api/registration/endpoint/apiReg009.ts
- packages/interface/src/api/registration/endpoint/apiReg011.ts
- packages/interface/src/api/registration/endpoint/apiReg014.ts
- packages/interface/src/api/registration/endpoint/apiReg015.ts
- packages/interface/src/api/registration/endpoint/apiReg016.ts
- packages/interface/src/api/registration/endpoint/apiReg017.ts
- packages/interface/src/api/registration/utils/registrationTypeEnumChecker.ts
- 15,16,17 아직 구현 안됐습니다. interface가 필요한 상황이라 interface들만 먼저 merge합니다. 
- 없음
> Impl reg14,15,16,17

- packages/web/src/features/clubDetails/components/ClubDetailCard.tsx
- packages/web/src/features/clubDetails/components/PersonInfoCard.tsx
- packages/web/src/features/clubDetails/components/PersonInfoItem.tsx
- packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
> Fix clubs detail layout to accept long name

- packages/web/src/features/clubs/components/ClubListGrid.tsx
> Impl responsive view for mobile in /clubs

- packages/interface/src/api/registration/endpoint/apiReg019.ts
- packages/interface/src/api/registration/endpoint/apiReg020.ts
> Implement REG-019 and 020 interface

- packages/web/src/app/manage-club/activity-report/[id]/page.tsx
- packages/web/src/common/components/File/ThumbnailPreviewList.tsx
- packages/web/src/common/components/File/attachment.ts
- packages/web/src/common/components/FileUpload.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/manage-club/funding/detail/components/BasicEvidenceList.tsx
- packages/web/src/features/manage-club/funding/detail/components/FixtureEvidenceList.tsx
- packages/web/src/features/manage-club/funding/detail/components/OtherEvidenceList.tsx
> Use ThumbnailPreviewList for all kind of file previews

- packages/web/src/app/executive/register-club/[id]/page.tsx
- packages/web/src/app/manage-club/activity-report/[id]/page.tsx
- packages/web/src/common/components/ProgressCheckSection/_atomic/Progress.tsx
- packages/web/src/common/components/ProgressCheckSection/_atomic/ProgressDot.tsx
- packages/web/src/common/components/ProgressCheckSection/_atomic/ProgressLine.tsx
- packages/web/src/common/components/ProgressCheckSection/index.tsx
- packages/web/src/common/components/ProgressCheckSection/progressCheckStationStatus.ts
- packages/web/src/constants/manageClubProgress.ts
- packages/web/src/features/executive/register-club/constants/registerClubType.ts
- packages/web/src/features/executive/register-club/frames/ClubRegisterApproveFrame.tsx
- packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
- packages/web/src/features/executive/register-club/services/_mock/mockActivityList.ts
- packages/web/src/features/executive/register-club/services/_mock/mockClubRegisterDetail.ts
- packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
> Impl /executive/register-club/[id]

- packages/web/src/features/landing/components/NoticeCard.tsx
- packages/web/src/features/notices/components/NoticeList.tsx
- packages/web/src/features/notices/components/NoticeListItem.tsx
- packages/web/src/features/notices/frames/NoticeListAndPaginationFrame.tsx
- packages/web/src/utils/Date/formatDate.ts
It closes #725 
피그마랑 폰트 크기 맞췄는데 묘하게 피그마보다 작아보이는건 기분탓일겁니다 아마..?
- 없음
> Impl notice page for mobile

- packages/web/src/app/clubs/page.tsx
- packages/web/src/features/clubs/services/_mock/mockupRegisTermData.ts
- packages/web/src/features/clubs/services/useGetRegisTerm.ts
It closes #753 
reg004 연결해서 등록기간인지 여부 확인하도록 했습니다
- 없음
> Update /club regis term info

- packages/web/src/features/clubDetails/services/unregisterClub.ts
- packages/web/src/features/clubs/components/ClubCard.tsx
It closes #755
등록, 등록 취소 api를 /clubs 등록 신청에도 연결했습니다
- 없음
> Connect registration api to /clubs

- packages/web/src/common/components/Footer/_atomic/SPARCSLogo.tsx
It closes #765 
footer의 로고를 클릭하면 창 너비가 >960px인 경우(만든 사람들이 footer에 있는 경우) 새 탭을 열어 sparcs.org로 이동하고 <960px인 경우 /credits로 이동합니다
- 없음
> Connect link to footer sparcs logo

- packages/api/src/drizzle/schema/registration.schema.ts
> fix: registration table remove not null

- packages/web/src/features/my/frames/MyInfoFrame.tsx
> Fix placeholder of phone number in /my

- packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
- packages/web/src/features/manage-club/members/frames/AllMemberListFrame.tsx
> Remove unnecessary stuff from /manage-club

- packages/web/src/common/components/Table.tsx
- packages/web/src/features/my/register-club/components/MyRegisterClubAcfTable.tsx
앞으로 내용물 잘리는 표가 있으면 이런 식으로 알아서 minWidth 강제로 먹여주기 
It closes #801 
- 없음
> add minWidth prop to Table

- packages/web/src/common/components/Button.tsx
- packages/web/src/common/components/Buttons/TextButton.tsx
- packages/web/src/common/components/Checkbox.tsx
- packages/web/src/common/components/CheckboxOption.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
- packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
- packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
It closes #668 
- checkbox layout 수정
- button layout 수정 (flex-shrink : 0)
- 없음
> fix: checkbox & button layout

- packages/web/src/app/register-club/page.tsx
- packages/web/src/features/register-club/components/ClubButton.tsx
It closes #770 
ClubButton 얘밖에 안쓰길래 이쁘게 하려고 buttonText 리스트로 받아서 불릿포인트 넣게 해놨어용
내일 와서 스타일 고칠게요~ --> 고쳤어요!
수정 후)
- 없음
> Add bullet points to /register-club explanation

- packages/web/src/app/manage-club/members/page.tsx
- packages/web/src/common/frames/NotRegistrationPeriod.tsx
- packages/web/src/features/manage-club/members/frames/ManageClubMembersFrame.tsx
> not registration period

- packages/web/src/common/components/Table.tsx
- packages/web/src/features/manage-club/activity-report/components/NewActivityReportList.tsx
- packages/web/src/features/manage-club/components/ActivityReportTable.tsx
- packages/web/src/features/manage-club/components/CommonSpaceTable.tsx
- packages/web/src/features/manage-club/components/FundingTable.tsx
- packages/web/src/features/manage-club/components/MembersTable.tsx
- packages/web/src/features/manage-club/components/RentalTable.tsx
- packages/web/src/features/my/components/MyCommonSpaceTable.tsx
- packages/web/src/features/my/components/MyRentalTable.tsx
- packages/web/src/features/my/register-club/components/MyRegisterClubAcfTable.tsx
> fix table cell percentage

- packages/web/src/common/components/Header/_atomic/Logo.tsx
- packages/web/src/common/components/Header/index.tsx
> mobile navmenu icon fix and close when logo click

- packages/web/src/app/my/clubs/page.tsx
- packages/web/src/app/my/register-club/[id]/page.tsx
- packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
- packages/web/src/common/frames/NotForExecutive.tsx
> redirect to home on profile change

- packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/interface/src/api/registration/endpoint/apiReg011.ts
> fix: reg011

- packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
- packages/interface/src/api/registration/endpoint/apiReg008.ts
> modify reg008 api

- packages/web/src/features/manage-club/components/MembersTable.tsx
- packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
- packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
It closes #844
승인 / 반려에 따른 모달 연결했습니다.
모달에 동아리 이름을 띄워야 해서 일단 이 이슈만 생각해서 API 연결을 해놓긴 했는데 
다음 이슈에서 API 연결 방식을 좀 깔끔하게 정리해야 할 것 같습니다
- 테이블 내용 불러오는 API 연결
- 승인 / 반려 로직 API 연결
> Impl Approve / Reject Modal for /manage-club/members

- .env.example
- packages/api/src/env.ts
- packages/api/src/feature/auth/service/auth.service.ts
- packages/api/src/feature/meeting/meeting.gateway.ts
- packages/api/src/main.ts
> fix: change default node_env from development to local

- packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg021.ts
It closes #858
테스트 내용은 chan에서 개별전달 하겠습니다.
- 없음
> Implement club-registration brief for professors(REG-021)

- packages/web/src/common/providers/AuthContext.tsx
> fix: fix logout

- packages/api/src/feature/club/controller/club.controller.ts
- packages/api/src/feature/club/repository/club.club-t.repository.ts
- packages/api/src/feature/club/service/club.service.ts
- packages/interface/src/api/club/endpoint/apiClb016.ts
> Impl professor clubs my

- packages/web/src/app/my/register-club/[id]/edit/page.tsx
- packages/web/src/app/register-club/provisional/page.tsx
- packages/web/src/app/register-club/renewal/page.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
- packages/web/src/features/my/services/useGetClubRegistration.ts
- packages/web/src/features/register-club/frames/RegisterClubAuthFrame.tsx
> page permission setting

- packages/web/src/common/components/Header/_atomic/Login.tsx
- packages/web/src/common/providers/AuthContext.tsx
- packages/web/src/common/services/getUserAgree.ts
- packages/web/src/common/services/postUserAgree.ts
> connect backend for privacy policy

- packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg012.ts
- packages/interface/src/api/registration/endpoint/apiReg021.ts
- packages/web/src/features/my/clubs/service/useGetMyClub.ts
- packages/web/src/features/my/components/MyClubProfTable.tsx
- packages/web/src/features/my/components/MyClubTable.tsx
- packages/web/src/features/my/frames/MyRegisterFrame.tsx
- packages/web/src/features/my/frames/_atomic/RegisterClubFrame.tsx
- packages/web/src/features/my/services/_mock/mockMyRegister.ts
- packages/web/src/features/register-club/services/_mocks/mockMyRegistration.ts
> connect backend for register frame in my

- packages/web/src/features/register-club/components/BasicInformFrame.tsx
- packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
- packages/web/src/features/register-club/components/_atomic/ClubNameSelect.tsx
- packages/web/src/features/register-club/components/_atomic/YearSelect.tsx
- packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
> 855 register club provisional test

- packages/api/src/feature/club/repository/club.repository.ts
> fix: reg002 reg003 duplication issue

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
> fix: reg001 when student already has club registration

- packages/web/src/common/components/File/ThumbnailPreview.tsx
- packages/web/src/common/components/File/ThumbnailPreviewList.tsx
- packages/web/src/common/components/File/_atomic/UnsupportedPreview.tsx
- packages/web/src/common/components/FileUpload.tsx
- packages/web/src/common/components/FlexWrapper.tsx
- packages/web/src/features/executive/register-club/services/_mock/mockClubRegisterDetail.ts
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
- packages/web/src/features/register-club/components/_atomic/CreateActivityReportModal.tsx
> a bunch of file stuff

- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
- packages/web/src/features/my/services/getMyClubRegistration.ts
- packages/web/src/features/register-club/components/_atomic/MonthSelect.tsx
- packages/web/src/features/register-club/components/_atomic/YearSelect.tsx
- packages/web/src/utils/Date/extractDate.ts
> feat: helper function for date issue

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg011.ts
- packages/interface/src/api/registration/endpoint/apiReg015.ts
- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
> fix: reg011 reg015

- packages/web/src/app/my/page.tsx
- packages/web/src/features/my/frames/MyInfoFrame.tsx
- packages/web/src/features/my/services/usePatchMyPhoneNumber.ts
> Connect be to phone number edit at /my

- packages/web/src/app/my/page.tsx
- packages/web/src/common/components/Forms/PhoneInput.tsx
- packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
- packages/web/src/features/my/frames/MyInfoFrame.tsx
- packages/web/src/features/register-club/components/BasicInformFrame.tsx
- packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
It closes #901 
010 시작 validation & 대표자 변경 비활성화 처리함
- 없음
> kr phonenumber validation

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
> fix: reg011, reg015 logic in club-registration repository

- packages/web/src/app/register-club/promotional/page.tsx
- packages/web/src/app/register-club/provisional/page.tsx
- packages/web/src/common/frames/HasClubRegistration.tsx
- packages/web/src/features/register-club/frames/RegisterClubAuthFrame.tsx
> feat: hasClubRegistration page

- packages/api/src/feature/activity/activity.module.ts
- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct007.ts
- packages/interface/src/api/activity/endpoint/apiAct008.ts
> feat: impl act007 act008

- packages/web/src/features/register-club/frames/RegisterClubAuthFrame.tsx
> fix: fix provisional access

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
> 911 newprovisional unavailable error

- packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
> feat: no professor

- packages/web/src/features/register-club/components/BasicInformFrame.tsx
- packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
> fix: phoneInput validation

- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct011.ts
- packages/interface/src/api/activity/endpoint/apiAct012.ts
- packages/interface/src/api/activity/endpoint/apiAct013.ts
It closes #922
셋다 200 잘나와유
- 없음
> Implement GET activity list for Promotional club registration(ACT-011)

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
> fix: reg012

- packages/web/src/app/clubs/page.tsx
- packages/web/src/app/register-club/page.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
- packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
It closes #925 
주석 처리 된 부분들은 등록기간 이후 페이지 권한 처리 할 때 정리할듯
- 없음
> feat: use registration date for info

- packages/web/src/features/register-club/components/BasicInformFrame.tsx
- packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
> comment out phoneNumber validation

- packages/web/src/app/my/clubs/page.tsx
- packages/web/src/features/my/clubs/frames/MyClubsProfessorFrame.tsx
- packages/web/src/features/my/clubs/service/getMyClubProfessor.ts
> impl my clubs for professor

- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
- packages/web/src/features/my/services/deleteMyClubRegistration.ts
> connect unlinked buttons

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg011.ts
- packages/interface/src/api/registration/endpoint/apiReg015.ts
- packages/interface/src/api/registration/endpoint/apiReg022.ts
> fix: several apis

- packages/web/src/common/components/PageHead/_atomic/BreadCrumb.tsx
- packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
> connect missing things for my register clubid

- packages/api/src/feature/activity/controller/activity.activity-term.controller.ts
슬랙으로 제보받은 컨트롤러 상의 오타 수정입니다.
타입이 완전히 똑같이 생겨서 에러가 없었던 거 같아요.
- 없음
> Fix REG-006 typo

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.public.service.ts
> Fix reg009 professor field error

- packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg023.ts
> Implement club-registration approval for professors

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/user/repository/user.repository.ts
- packages/api/src/feature/user/service/user.service.ts
- packages/interface/src/api/registration/endpoint/apiReg001.ts
- packages/interface/src/api/user/endpoint/apiUsr001.ts
- packages/web/src/common/services/_mock/mockupUserProfile.ts
> fix: reg001 usr001

- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
- packages/web/src/features/my/register-club/frames/ProfessorRegisterClubDetailFrame.tsx
- packages/web/src/features/my/register-club/frames/StudentRegisterClubDetailFrame.tsx
- packages/web/src/features/my/services/patchClubRegProfessorApprove.tsx
> feat: connect reg 023

- packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
> feat: executive register club acf table

- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
> Fix reg-022 professor sign check to check null

- packages/api/src/feature/club/controller/club-delegate.controller.ts
- packages/api/src/feature/club/repository/club.club-delegate-d.repository.ts
- packages/api/src/feature/club/service/club-delegate.service.ts
- packages/interface/src/api/club/endpoint/apiClb008.ts
> Implement GET club delegate cnadidates(REG-008)

- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct011.ts
- packages/web/src/features/my/register-club/components/MyRegisterClubAcfTable.tsx
> fix: act011

- packages/web/src/common/components/File/ThumbnailPreviewList.tsx
- packages/web/src/features/manage-club/activity-report/_mock/mock.ts
- packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
- packages/web/src/features/register-club/components/ActivityReportFrame.tsx
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
> feat: connect act002 act011

- packages/web/src/common/components/ListItem.tsx
- packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
> executive register club detail problems

- packages/web/src/common/components/Table.tsx
table count 0일 때 총 0개 대신 0으로 뜨는 문제 해결
- 없음
> fix: fix table count

- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct002.ts
- packages/interface/src/api/activity/endpoint/apiAct003.ts
- packages/interface/src/api/activity/endpoint/apiAct014.ts
- packages/interface/src/api/activity/endpoint/apiAct015.ts
- packages/web/src/app/manage-club/activity-report/[id]/page.tsx
- packages/web/src/features/manage-club/activity-report/_mock/mock.ts
- packages/web/src/features/manage-club/activity-report/services/useGetActivityReport.tsx
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
> fix: act002 act014 ac015 response type

- packages/api/src/feature/user/controller/user.controller.ts
- packages/interface/src/api/user/endpoint/apiUsr002.ts
> fix: usr002

- packages/web/src/app/clubs/page.tsx
> improve club search in english

- packages/web/src/app/my/page.tsx
- packages/web/src/common/services/getUserPhoneNumber.ts
- packages/web/src/features/my/frames/MyInfoFrame.tsx
- packages/web/src/features/my/frames/ProfessorMyClubFrame.tsx
> use usr002 to get phone number

- packages/web/src/common/components/MyMenu/_atomic/Profile.tsx
> fix: no student number or email

- packages/web/src/common/components/MyMenu/_atomic/Profile.tsx
> fix: profile text

- packages/api/src/feature/club/repository/club.club-delegate-d.repository.ts
- packages/api/src/feature/file/service/file.service.ts
- packages/interface/src/api/file/apiFil001.ts
- packages/interface/src/api/file/apiFil003.ts
- packages/interface/src/common/commonString.ts
> Add file name to every FIL APIs

- packages/web/src/common/components/Forms/DateRangeInput.tsx
- packages/web/src/features/register-club/components/_atomic/ActivityTermRow.tsx
> fix: used days for date range input

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
> Fix reg-014 total counting soft deletions

- packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
> fix: fix executive registration club table

- packages/web/src/common/providers/AuthContext.tsx
- packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
- packages/web/src/features/manage-club/activity-report/services/useGetActivityReport.tsx
- packages/web/src/features/my/register-club/components/MyRegisterClubAcfTable.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubAcfFrame.tsx
- packages/web/src/features/register-club/components/ActivityReportFrame.tsx
- packages/web/src/features/register-club/components/_atomic/EditActivityReportModal.tsx
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
- packages/web/src/features/register-club/services/_atomic/actApiList.ts
- packages/web/src/features/register-club/services/getProvisionalActivities.ts
> modify act detail for registration

- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
> fix: listItem layout

- packages/web/src/features/landing/components/Banner.tsx
- packages/web/src/features/landing/frames/MainPageMainFrame.tsx
> feat: impl banner

- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/api/src/feature/club/repository/club.club-student-t.repository.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/interface/src/api/activity/endpoint/apiAct010.ts
> Implement participants selection list generation (ACT-010)

- packages/api/src/feature/activity/activity.module.ts
> fix: file import

- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct002.ts
- packages/web/src/features/manage-club/activity-report/_mock/mock.ts
- packages/web/src/features/manage-club/activity-report/services/useGetActivityReport.tsx
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
> add file url and name for act 002 014 015

- packages/api/src/feature/auth/repository/auth.repository.ts
> fix: professor login logic

- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
- packages/web/src/features/register-club/components/ActivityReportFrame.tsx
- packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
- packages/web/src/features/register-club/components/_atomic/CreateActivityReportModal.tsx
> 1001 fix reload issue

- packages/interface/src/api/club/endpoint/apiClb004.ts
- packages/web/src/app/register-club/page.tsx
- packages/web/src/common/frames/NoRegisterClubForProfessor.tsx
- packages/web/src/features/manage-club/components/ChangeClubInfoCard.tsx
- packages/web/src/features/manage-club/services/getClubInfo.ts
- packages/web/src/features/my/frames/MyClubFrame.tsx
- packages/web/src/features/my/frames/ProfessorMyClubFrame.tsx
- packages/web/src/features/register-club/frames/RegisterClubFrame.tsx
It closes #1009
로그인 문제는 수정 안 됨
대표 동아리 관리 null 문제
지도교수 동아리 등록 페이지 권한 막기
마이페이지 동아리 없을 때 에러 수정
- 없음
> fix several issues

- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct002.ts
- packages/web/src/features/activity-report/services/useGetParticipants.ts
- packages/web/src/features/manage-club/activity-report/_mock/mock.ts
- packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
- packages/web/src/features/manage-club/activity-report/services/useGetActivityReport.tsx
- packages/web/src/features/manage-club/activity-report/types/activityReport.ts
- packages/web/src/features/manage-club/funding/components/TransportEvidenceBlock.tsx
- packages/web/src/features/register-club/components/_atomic/ClubNameField.tsx
- packages/web/src/features/register-club/components/_atomic/CreateActivityReportModal.tsx
- packages/web/src/features/register-club/components/_atomic/ParticipantSection.tsx
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
- packages/web/src/features/register-club/model/CreateRegisterClub.ts
> feat: connect participant select

- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct016.ts
> Implement act-016 interface and api

- packages/interface/src/api/registration/endpoint/apiReg019.ts
> fix: reg019 interface

- packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
- packages/web/src/features/my/register-club/components/MyRegisterClubActTable.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubActFrame.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
> fix: fix table scroll

- package.json
- packages/api/package.json
- packages/web/package.json
- packages/web/src/common/providers/AuthContext.tsx
> fix: fix login issue

- packages/web/src/features/executive/register-club/frames/ClubRegisterApproveFrame.tsx
- packages/web/src/features/executive/register-club/services/patchActivityExecutive.ts
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
> connect act016

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
> fix: reg001 reg003

- packages/web/src/common/components/ListItem.tsx
- packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
- packages/web/src/features/register-club/components/_atomic/ClubNameField.tsx
- packages/web/src/features/register-club/components/_atomic/MonthSelect.tsx
- packages/web/src/features/register-club/components/_atomic/YearSelect.tsx
> fix: renewal done

- packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
- packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
- packages/web/src/features/register-club/utils/registrationType.ts
> fix: promotional register

- packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
- packages/web/src/features/manage-club/activity-report/services/useDeleteActivityReportProvisional.tsx
- packages/web/src/features/register-club/components/ActivityReportFrame.tsx
- packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
> Act reg test

- packages/web/src/app/manage-club/page.tsx
- packages/web/src/common/frames/NoManageClubForProfessor.tsx
- packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
It closes #1041 
es hangul 사용하는 추가 필터링 로직 제거해서 수정함
추후 todo로 남겨둠
지도교수가 대표 동아리 관리 페이지 접근했을 때 에러 페이지도 한 pr에서 해결함
- 없음
> fix: fix selectParticipant search

- packages/api/src/drizzle/schema/division.schema.ts
- packages/api/src/feature/club/repository/club.repository.ts
- packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
> fix: db schema and club permannent logic

- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/my/register-club/components/MyRegisterClubActTable.tsx
> feat: add status tag for activity

- packages/api/src/feature/club/controller/club-delegate.controller.ts
- packages/api/src/feature/registration/member-registration/controller/member-registration.controller.ts
- packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg019.ts
> Implement reg-019 interface and api

- packages/api/src/feature/registration/member-registration/controller/member-registration.controller.ts
- packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg020.ts
> Implement Club member-registraiton dashboard for executives (REG-020)

- packages/interface/src/api/registration/utils/registrationTypeEnumChecker.ts
- packages/web/src/common/components/FileUpload.tsx
- packages/web/src/features/register-club/components/AdvancedInformFrame.tsx
- packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
> feat: add file error message

- packages/api/src/drizzle/schema/user.schema.ts
- packages/api/src/feature/auth/repository/auth.repository.ts
- packages/api/src/feature/auth/service/auth.service.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
> 1059 fix professor login

- packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
- packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
- packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
- packages/web/src/features/register-club/utils/computeErrorMessage.ts
> fix: isValid error

- packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
- packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
> Disable register button when error message exists

- packages/web/src/common/components/File/ThumbnailPreview.tsx
- packages/web/src/common/components/File/ThumbnailPreviewList.tsx
- packages/web/src/common/components/File/_atomic/UnsupportedPreview.tsx
- packages/web/src/common/components/File/attachment.ts
- packages/web/src/common/components/FileUpload.tsx
- packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/manage-club/funding/detail/components/BasicEvidenceList.tsx
- packages/web/src/features/manage-club/funding/detail/components/FixtureEvidenceList.tsx
- packages/web/src/features/manage-club/funding/detail/components/OtherEvidenceList.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
- packages/web/src/features/register-club/components/SingleUploadWithTextAndTemplate.tsx
- packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
> fix: refactor file upload

- packages/web/src/common/components/FormController.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
- packages/web/src/features/register-club/components/BasicInformFrame.tsx
- packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
- packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
- packages/web/src/utils/validator.ts
> fix: register errors

- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct002.ts
- packages/web/src/features/manage-club/activity-report/_mock/mock.ts
- packages/web/src/features/manage-club/activity-report/services/useGetActivityReport.tsx
> Add commets to activities (REG-002, 014, 015)

- packages/web/src/common/components/FileUpload.tsx
> feat: file upload fail modal

- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/web/src/common/components/RejectReasonToast.tsx
- packages/web/src/features/manage-club/activity-report/_mock/mock.ts
- packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
- packages/web/src/features/register-club/components/_atomic/EditActivityReportModal.tsx
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
> feat: show reject comments for act

- packages/api/src/feature/activity/repository/activity.repository.ts
> fix: purpose overwritten by location

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/interface/src/api/file/apiFil001.ts
> fix: file upload error and professorT upsert logic

- packages/web/src/common/services/getUserProfile.ts
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
> Merge dev into main

- packages/api/src/feature/club/club.module.ts
- packages/api/src/feature/club/delegate/delegate.controller.ts
- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/api/src/feature/club/repository/club.club-delegate-d.repository.ts
> Check delegate and representative change logic

- packages/web/src/app/executive/register-member/[id]/page.tsx
- packages/web/src/app/executive/register-member/page.tsx
- packages/web/src/features/executive/register-member/services/getMemberRegistration.ts
It closes #1070 
!Registration Period
Registration Period
> feat: display executive pages for member registration period

- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
> Fix duplicate breif on member-registration executive dashboard

- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
> Open REG-015 always

- packages/web/src/features/credits/credits.ts
> Add new member to contributor page

- packages/web/src/app/meeting/[id]/edit/page.tsx
- packages/web/src/features/meeting/components/MeetingAnnouncementFrame.tsx
- packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
- packages/web/src/features/meeting/services/_mock/mockupMeetingDetail.ts
- packages/web/src/features/meeting/services/useUpdateMeeting.ts
> impl meeting edit page

- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/interface/src/api/club/endpoint/apiClb007.ts
- packages/interface/src/api/club/endpoint/apiClb008.ts
- packages/web/src/features/manage-club/services/_mock/mockDelegate.ts
> Add representative filter and studnet number field to 008 (REG-008, 007)

- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/api/src/feature/club/repository/club.club-delegate-d.repository.ts
> Check delegate change logic and add option to remove delegate(REG-007)

- packages/web/src/features/credits/credits.ts
It closes #1124
크레딧 페이지에 차차 올립니다
https://github.com/user-attachments/assets/e861f6f1-6ed8-487f-ad5c-15803d182d65
- 없음
> Add chacha credit

- packages/web/src/features/credits/credits.ts
> feat: add 2024fall credit for daystar

- packages/web/src/features/credits/credits.ts
> Add somato credit

- packages/web/src/common/components/PageContent.tsx
- packages/web/src/constants/paths.ts
> production ready paths bug

- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg024.ts
- packages/web/src/app/manage-club/permanent/register-club/[id]/page.tsx
- packages/web/src/app/manage-club/permanent/register-club/page.tsx
- packages/web/src/constants/paths.ts
- packages/web/src/features/permanent/register-club/components/ClubRegistrationTable.tsx
- packages/web/src/features/permanent/register-club/frames/ClubRegisterApproveFrame.tsx
- packages/web/src/features/permanent/register-club/frames/ClubRegisterDetailFrame.tsx
- packages/web/src/features/permanent/register-club/frames/RegistrationClubFrame.tsx
- packages/web/src/features/permanent/register-club/services/getRegisterClubDetail.ts
- packages/web/src/features/permanent/register-club/services/useGetRegisterClub.ts
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
> [Temporary] Permanent club representative register club and detail page

- packages/api/src/feature/club/delegate/delegate.service.ts
> Remove filter of CLB-008

- packages/web/src/common/components/CheckboxOption.tsx
- packages/web/src/common/components/Radio/RadioOption.tsx
It closes #97
체크박스나 radio 버튼 옆의 텍스트(라벨)을 클릭해도 작동하도록 수정
참고) https://github.com/academic-relations/ar-007-students/pull/16 
- 없음
> Add clickable label

- packages/web/src/features/credits/credits.ts
> add fall semester credit for ava

- packages/web/package.json
- packages/web/src/app/meeting/[id]/edit/page.tsx
- packages/web/src/app/meeting/announcement/create/page.tsx
- packages/web/src/common/components/Buttons/TextButton.tsx
- packages/web/src/common/components/FormController.tsx
- packages/web/src/common/components/Forms/DateInput.tsx
- packages/web/src/common/components/NavTools/MobileNavMenu.tsx
- packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
- packages/web/src/utils/Date/formatDate.ts
- pnpm-lock.yaml
> 1116 edit dateinput component

- packages/api/src/feature/club/repository/club.club-delegate-d.repository.ts
> Chagne clb 008 filter

- packages/web/src/common/components/MultiFilter/Index.tsx
- packages/web/src/common/components/MultiFilter/_atomic/DetailFilter.tsx
- packages/web/src/common/components/MultiFilter/_atomic/DetailFilterButton.tsx
- packages/web/src/common/components/MultiFilter/_atomic/DetailFilterDropdown.tsx
- packages/web/src/common/components/MultiFilter/_atomic/MultiFilterButton.tsx
- packages/web/src/common/components/MultiFilter/_atomic/MultiFilterDropdown.tsx
- packages/web/src/common/components/MultiFilter/types/FilterCategories.ts
- packages/web/src/common/components/Select/Dropdown.tsx
- packages/web/src/common/components/SelectedItem.tsx
It closes #1148
클릭하면 드롭다운이 생기고, 다양한 기준으로 필터링 가능한 컴포넌트를 만들었습니다.
**categories: 필터 이름과 함께 필터 안에 들어가는 선택지들, 선택된 선택지들을 담고 있음!**
**사용 예시**
직접 확인해보시기 좋으시라구 app/my/page.tsx 코드 올려드립니다. 마이 페이지에 들어가시면 확인 가능합니다!
```
"use client";
import React, { useEffect, useState } from "react";
import styled from "styled-components";
import AsyncBoundary from "@sparcs-clubs/web/common/components/AsyncBoundary";
import FlexWrapper from "@sparcs-clubs/web/common/components/FlexWrapper";
import MultiFilter from "@sparcs-clubs/web/common/components/MultiFilter/Index";
import { CategoryProps } from "@sparcs-clubs/web/common/components/MultiFilter/types/FilterCategories";
import PageHead from "@sparcs-clubs/web/common/components/PageHead";
import LoginRequired from "@sparcs-clubs/web/common/frames/LoginRequired";
import …
```
> Impl multiselect filter

- packages/api/src/feature/auth/controller/auth.controller.ts
- packages/api/src/feature/auth/service/auth.service.ts
> fix: add annotations

- packages/web/src/common/components/Forms/ItemNumberInput.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
- packages/web/src/features/rental-business/components/Rentals/Easel.tsx
- packages/web/src/features/rental-business/components/Rentals/HandCart.tsx
- packages/web/src/features/rental-business/components/Rentals/Mat.tsx
- packages/web/src/features/rental-business/components/Rentals/Tool.tsx
It closes #1190 
ItemNumberInput의 value type을 number로 수정하여 react-hook-form에서 사용할 수 있도록 수정
- 없음
> modify itemnumberinput

- packages/api/src/feature/club/delegate/delegate.controller.ts
- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/api/src/feature/club/repository/club.club-delegate-d.repository.ts
- packages/interface/src/api/club/endpoint/apiClb014.ts
- packages/web/src/features/my/components/ChangeDivisionPresidentModalContent.tsx
- packages/web/src/features/my/components/ChangeRepresentativeModalContent.tsx
> Implement club delegate change request check and modification (CLB-011, 012, 013, 014)

- packages/web/src/features/credits/credits.ts
> Add 2024F credit - hama

- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateMainFrame.tsx
It closes #1209 
- 전화번호 유효성 XXX-XXXX-XXXX 에서 010-XXXX-XXXX 으로 변경
- 없음
> update ActivityCertificateInfoFirstFrame phoneNumber validation

- packages/api/src/feature/club/delegate/delegate.service.ts
> Fix representative change bugs

- packages/api/src/feature/club/club.module.ts
- packages/api/src/feature/club/delegate/delegate.module.ts
> Resolve circular dependecy on club-delegate module

- packages/web/src/features/manage-club/components/ChangeClubInfoCard.tsx
- packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
> fix layout for change representative

- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/api/src/feature/user/controller/user.controller.ts
- packages/api/src/feature/user/repository/student.repository.ts
- packages/api/src/feature/user/service/user.public.service.ts
- packages/api/src/feature/user/service/user.service.ts
- packages/interface/src/api/club/endpoint/apiClb011.ts
- packages/interface/src/api/club/endpoint/apiClb013.ts
- packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
- packages/web/src/features/manage-club/services/_mock/mockDelegate.ts
- packages/web/src/features/my/frames/MyChangesFrame.tsx
- packages/web/src/features/my/services/_mock/mockMyDelegateChange.ts
It closes #1253 
- clb011, 013 response에 studentNumber 추가
- clb014에 phoneNumber 변경 추가
- updateStudentPhoneNumber를 userPublicService로 이동 (delegateService에서 사용 위함)
updateStudentPhoneNumber의 userId -> id 변경 후 정상 작동 확인
~~updateStudentPhoneNumber 옮기고 나서 clb014 실행하면 아래와 같은 에러메시지가 뜨는데 확인 부탁드립니다.
usr003 (phoneNumber만 변경)은 문제없이 작동하는데, clb014에서 실행할 때만 에러메시지 발생
phoneNumber 변경하는 것 추가했을 때 에러메시지~~
clb013 테스트
clb011 테스트
- 없음
> modify delegate change logic

- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
- packages/web/src/features/manage-club/activity-report/components/_atomic/ActivityReportEditForm.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
- packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
It closes #1219 
+ PastActivityReportModal에서 ActivityReportForm 사용 예시 보는 방법:
아래 사진처럼 117(Sparcs Test 동아리)로 임의값 수정한 뒤 register club 페이지로 가서 동아리 신청 클릭 후 Sparcs Test 선택하면 하단에 활동보고서 관련 섹션이 만들어짐
- 현재 PR은 "edit" activity report에 한해서만 migration을 진행했기 때문에 "create" activity report에 대해서도 비슷한 작업이 필요. 추후 다른 issue 만들어서 진행 예정
> 1219 use react hook form for activity report

- packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
- packages/web/src/features/manage-club/activity-report/services/usePostActivityReport.tsx
> 활동보고서 생성 API 연결

- packages/web/src/app/manage-club/activity-report/[id]/edit/page.tsx
- packages/web/src/app/manage-club/activity-report/[id]/page.tsx
- packages/web/src/app/manage-club/activity-report/create/page.tsx
- packages/web/src/app/manage-club/activity-report/page.tsx
- packages/web/src/constants/paths.ts
> 활동보고서 작성 기능 & 대표자 변경 기능 배포

- packages/web/src/app/manage-club/activity-report/[id]/edit/page.tsx
- packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
- packages/web/src/features/manage-club/activity-report/components/_atomic/ActivityReportEditForm.tsx
- packages/web/src/features/manage-club/activity-report/constants/activityReportProgress.ts
- packages/web/src/features/manage-club/activity-report/constants/index.ts
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
- packages/web/src/features/register-club/components/SelectActivityTerm.tsx
- packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
- packages/web/src/features/register-club/components/_atomic/EditActivityTermModal.tsx
- packages/web/src/utils/Date/extractDate.ts
> 활동 보고서 활동 기간 <-> 활동 인원 연동, 각종 UTC 오류

- packages/web/src/common/components/FileUpload.tsx
- packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/manage-club/frames/ActivityManageFrame.tsx
> 파일 업로드 시 미리보기 안 보이는 이슈 수정

- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct018.ts
현재 활보 관련 데드라인을 확인하는 ACT018에 데드라인이 작성기한으로 표기될 떄 현재 어떤 활동기간에 대한 작성기간인지 힌트를 추가
- 없음
> Add target term to ACT018

- packages/web/src/app/manage-club/activity-report/page.tsx
- packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/activity-report/services/useGetActivityTerms.tsx
- packages/web/src/features/activity-report/services/useGetNewActivityReportList.tsx
- packages/web/src/features/activity-report/services/useGetParticipants.ts
- packages/web/src/features/activity-report/services/useGetPastActivityReportList.tsx
- packages/web/src/features/activity-report/services/useGetProfessorCurrentActivityReportList.ts
- packages/web/src/features/manage-club/frames/ProfessorManageClubFrame/index.tsx
- packages/web/src/hooks/getManageClubList.ts
> 활동 보고서 RQ 무한로딩 이슈

- packages/api/src/feature/activity/service/activity.activity-term.service.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct005.ts
- packages/interface/src/api/activity/endpoint/apiAct006.ts
- packages/web/src/features/activity-report/_mock/activityReportList.ts
- packages/web/src/features/activity-report/components/CurrentActivityReportTable.tsx
- packages/web/src/features/activity-report/components/PastActivityReportTable.tsx
- packages/web/src/features/activity-report/components/tables/ProfessorActivityReportTable.tsx
- packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/activity-report/frames/ActivityReportMainFrame.tsx
- packages/web/src/features/activity-report/hooks/useGetActivityTerm.ts
- packages/web/src/features/activity-report/hooks/useGetCurrentActivityReportList.ts
- packages/web/src/features/activity-report/hooks/useGetPastActivityReportList.ts
- packages/web/src/features/activity-report/hooks/useProfessorApproveSingleActivityReport.ts
- packages/web/src/features/activity-report/services/useGetNewActivityReportList.tsx
- packages/web/src/features/activity-report/services/useGetProfessorCurrentActivityReportList.ts
- packages/web/src/features/activity-report/services/useGetTermActivityReportList.tsx
- packages/web/src/features/activity-report/services/useProfessorApproveActivityReport.ts
- packages/web/src/features/activity-report/types/activityReport.ts
- packages/web/src/features/activity-report/types/activityTerm.ts
- packages/web/src/features/activity-report/types/table.ts
- packages/web/src/features/manage-club/frames/ActivityManageFrame.tsx
> 활동 보고서 페이지에 지도교수 승인 여부 정보 추가

- packages/api/src/drizzle/schema/activity.schema.ts
- packages/api/src/feature/activity/activity.module.ts
- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/repository/activity.activity-club-charged-executive.repository.ts
- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct024.ts
- packages/interface/src/common/type/id.type.ts
> Implement activity check features for executives (ACT-024, ACT-025)

- packages/web/src/features/activity-report/components/CurrentActivityReportTable.tsx
- packages/web/src/features/activity-report/components/tables/ProfessorActivityReportTable.tsx
- packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/activity-report/hooks/useGetActivityReportDetail.ts
- packages/web/src/features/activity-report/hooks/useGetCurrentActivityReportList.ts
- packages/web/src/features/activity-report/hooks/useGetProfessorActivityReportList.ts
- packages/web/src/features/activity-report/types/activityReport.ts
- packages/web/src/features/activity-report/types/table.ts
- packages/web/src/features/clubs/hooks/useHasAdvisor.ts
- packages/web/src/features/clubs/hooks/useHasProfessor.ts
> 지도교수 없을 경우 승인 여부 UI

- packages/api/src/drizzle/schema/activity.schema.ts
- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/repository/activity.activity-club-charged-executive.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct026.ts
> Implement act 026

- packages/interface/src/api/file/type/file.type.ts
variablename이 type으로 되어 있는 걸 발견해서 extension으로 수정하여 CI 오류를 해결합니다.
- 없음
> fix: bad variable name type

- packages/api/src/drizzle/schema/club.schema.ts
- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/api/src/feature/user/repository/executive.repository.ts
- packages/api/src/feature/user/service/user.public.service.ts
- packages/interface/src/api/activity/endpoint/apiAct023.ts
- packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportFrame.tsx
> Add more information on act023

- packages/api/src/feature/funding/repository/funding.repository.ts
- packages/api/src/feature/funding/service/funding.service.ts
- packages/interface/src/api/funding/type/funding.type.ts
> fix: change type of IFundingRequest

- packages/web/src/features/executive/activity-report/components/ChargedActivityModalTable.tsx
- packages/web/src/features/executive/activity-report/components/ExecutiveActivityChargedTable.tsx
- packages/web/src/features/executive/activity-report/components/ExecutiveActivityClubTable.tsx
- packages/web/src/features/executive/activity-report/components/ExecutiveClubActivitiesTable.tsx
- packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportFrame.tsx
It closes #1310 
확인 필요한 내용
- 모달 width: 화면 좁을 때 깨지는거 방지하려고 600px로 해놨는데 표 다 보이게 하려면 1000px 정도로 해야함 - 어떻게 할지?
https://github.com/user-attachments/assets/bf361be4-78b4-480c-8b02-9b806a7d6170
- 없음
> impl ExecutiveActivityChargedTable

- packages/api/src/feature/activity/service/activity.activity-term.service.ts
- packages/api/src/feature/activity/service/activity.service.ts
> refactor: improve sorting of activity durations and terms

- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/api/src/feature/club/repository/club.club-student-t.repository.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/api/src/feature/user/model/executive.model.ts
- packages/api/src/feature/user/model/executive.summary.model.ts
- packages/api/src/feature/user/model/student.model.ts
- packages/api/src/feature/user/repository/executive.repository.ts
- packages/api/src/feature/user/service/user.public.service.ts
- packages/interface/src/api/activity/endpoint/apiAct027.ts
- packages/interface/src/api/club/type/club.type.ts
- packages/interface/src/api/user/type/user.type.ts
- packages/interface/src/common/zodUtil.ts
It closes #1319 
7번 (Khartes)를 입력하니 15번 권혁원이 안나오는 것을 확인 가능합니다.
그러면서도 다양한 컨벤션을 적용해봤습니다.
- entity I나 M을 return 하는 public service & repository (user, club)
- pick으로 가져오는 interface 정의
- back에서 쓸 url을 interface endpoint 에서 정의
- public service 메서드명 컨벤션
- publicService에서 던지는 예외 ( club.public.service)
- 
- 예외 체크 (404라던가...)
- Entity zod에서 한 element 쉽게 가져오기 (pickElement 가 dev 구동 시에 오류를 뱉는데, 왜인지 수정 필요)
> 1319 impl act027 for charge available executives

- packages/web/src/features/manage-club/components/ChangeClubInfoCard.tsx
> 동아리방 비밀번호 필드 주서처리

- packages/api/src/feature/club/repository/club.club-student-t.repository.ts
It closes #1330 
packages/api dev: Query: select student_id, start_term, end_term, ?, TIMESTAMPDIFF(SECOND, end_term, ?), club_student_t.end_term < ? from club_student_t where (club_student_t.club_id = ? and not club_student_t.start_term > ? and club_student_t.deleted_at is null) -- params: ["2024-09-01T00:00:00.000Z", "2024-09-01T00:00:00.000Z", "2024-09-01T00:00:00.000Z", 112, "2024-09-01T00:00:00.000Z"]
packages/api dev: 2025-01-15 02:59:43(UTC+09:00) [info]: 2024-09-01T00:00:00.000Z 
packages/api dev: 2025-01-15 02:59:43(UTC+09:00) [info]: 2024-09-01T00:00:00.000Z 
packages/api dev: 2025-01-15 02:59:43(UTC+09:00) [info]: [
packages/api dev:   {
packages/api dev:     studentId: 770,
packages/api dev:     startTerm: 2024-02-26T00:00:00.000Z,
packages/api dev:     endTerm: …
> fix: utc timezone value to kst

- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct026.ts
> Change act-026 to get muptile clubs

- packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
It closes #1329 
프론트 단에서 막혀 있어서 괜찮긴한데 에러 발생할 수 있는 케이스가 있어서 일단 조치합니다
기존엔 
- 기존 대표자 임기 종료
- 원래 맡고 있던 대의원 임기 종료
를 동시에 처리 후 affectedRow > 1 일때 에러여서 대의원 맡고 있던 사람을 넣으면 2로 오류가납니다.
(근데 프론트 단에서 자기 동아리 대의원도 대표자로 못바꾸게 해둬서 문제는 발생하지 않음)
아무튼 찾았으니 고쳐야죠.
- 없음
> chore: divide error case for change delegate accept

- packages/web/src/common/components/Select/SelectOption.tsx
- packages/web/src/common/components/Select/index.tsx
- packages/web/src/common/components/Table/CheckboxCenterPlacerStopPropagation.tsx
- packages/web/src/features/executive/activity-report/components/ChargedChangeActivityModalContent.tsx
- packages/web/src/features/executive/activity-report/components/ChargedChangeActivityModalTable.tsx
- packages/web/src/features/executive/activity-report/components/ChargedChangeClubModalContent.tsx
- packages/web/src/features/executive/activity-report/components/ChargedChangeClubModalTable.tsx
- packages/web/src/features/executive/activity-report/components/ExecutiveActivityChargedTable.tsx
- packages/web/src/features/executive/activity-report/components/ExecutiveActivityClubTable.tsx
- packages/web/src/features/executive/activity-report/components/ExecutiveClubActivitiesTable.tsx
- packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportClubFrame.tsx
- packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportFrame.tsx
- packages/web/src/features/executive/activity-report/services/patchActivityChargedExecutive.tsx
- packages/web/src/features/executive/activity-report/services/putClubActivitiesChargedExecutive.tsx
- packages/web/src/features/executive/activity-report/services/useGetActivityClubChargeAvailableExecutives.tsx
- packages/web/src/utils/getChargedExecutiveContent.tsx
It closes #1314 
- 담당자 변경 후 활보 내역 다시 불러오는데 시간이 좀 걸림 -> 혹시 loading 따로 넣어야 할까요?
- 담당자 변경 후 동아리/개별 활보 선택 내역 초기화 (table에서) 해야할지
https://github.com/user-attachments/assets/bb45cb80-a60d-4d9d-a25b-929ad899f7e5
https://github.com/user-attachments/assets/2da35526-b79f-419c-8485-fbb44fccf131
- 없음
> impl change charged executive

- packages/api/src/feature/auth/repository/auth.repository.ts
- packages/api/src/feature/auth/service/auth.service.ts
- user의 email을 불러올 때 sparcs sso의 email이 아니라, iam의 email로 불러오도록 수정
- 지도교수 로그인 시 user id 기준으로 로그인하도록 수정
- 없음
> refactor: update auth repository and service for improved professor handling

- packages/api/src/feature/activity/repository/activity.repository.ts
> refactor: simplify activity status query in ActivityRepository

- packages/api/src/feature/activity/service/activity.service.ts
ACT-024에서 최종 검토 집행부원이 보이지 않는 에러 해결입니다
- 없음
> Act-024 finalReviewedExecutive error

- packages/web/src/features/credits/credits.ts
> Add hama's 24w credit

- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.public.service.ts
- packages/api/src/feature/funding/funding.module.ts
- packages/api/src/feature/funding/model/funding.comment.ts
- packages/api/src/feature/funding/repository/funding.comment.repository.ts
- packages/api/src/feature/funding/repository/funding.repository.ts
- packages/api/src/feature/funding/service/funding.service.ts
- packages/api/src/feature/user/repository/executive.repository.ts
- packages/api/src/feature/user/repository/student.repository.ts
- packages/api/src/feature/user/service/user.public.service.ts
- packages/interface/src/api/funding/type/funding.type.ts
> 1351 fix bug in add funding and get funding summary

- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.public.service.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/api/src/feature/club/repository/club.semester-d.repository.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/api/src/feature/funding/controller/funding.controller.ts
- packages/api/src/feature/funding/service/funding.service.ts
- packages/api/src/feature/user/model/student.summary.model.ts
- packages/interface/src/api/activity/type/activity.type.ts
- packages/interface/src/api/club/type/semester.type.ts
- packages/interface/src/api/funding/apiFnd007.ts
- packages/interface/src/api/funding/apiFnd008.ts
- packages/interface/src/common/enum/activity.enum.ts
- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/activity-report/constants/activityReportProgress.ts
- packages/web/src/features/executive/activity-report/components/ExecutiveClubActivitiesTable.tsx
It closes #1360 
ApiFnd007: 활동 목록
ApiFnd008: 활동 참여자 목록
007
원래는 이렇게 다 나오다가
승인 or 운위만 나오게 수정
008
- 없음
> 1360 impl funding api for writing funding docs

- packages/api/src/drizzle/schema/funding.schema.ts
- packages/api/src/feature/activity/service/activity.public.service.ts
- packages/api/src/feature/funding/controller/funding.controller.ts
- packages/api/src/feature/funding/model/funding.model.ts
- packages/api/src/feature/funding/repository/funding.repository.ts
- packages/api/src/feature/funding/service/funding.service.ts
- packages/interface/src/api/activity/type/activity.type.ts
- packages/interface/src/api/funding/apiFnd006.ts
- packages/interface/src/api/funding/type/funding.type.ts
> refactor: update funding schema and related services to use activityDId instead of semesterId

- packages/api/src/feature/activity/service/activity.service.ts
활동보고서 승인시에도 최종 검수자가 표기되도록 피드백을 임의로 추가했어요
- 없음
> fix: add literal comment to approval

- packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/register-club/components/_atomic/EditActivityReportModal.tsx
승인 코멘트("활동이 승인되었습니다") 필터링
- 없음
> fix: add filter for comments

- packages/api/src/feature/funding/service/funding.service.ts
- packages/web/src/app/manage-club/funding/[id]/page.tsx
- packages/web/src/features/manage-club/funding/components/FixtureEvidenceBlock.tsx
- packages/web/src/features/manage-club/funding/components/_atomic/NewFundingListTable.tsx
- packages/web/src/features/manage-club/funding/components/_atomic/PastFundingListTable.tsx
- packages/web/src/features/manage-club/funding/constants/fundingProgressStatus.ts
- packages/web/src/features/manage-club/funding/detail/components/BasicEvidenceList.tsx
- packages/web/src/features/manage-club/funding/detail/components/FixtureEvidenceList.tsx
- packages/web/src/features/manage-club/funding/detail/components/FundingInfoList.tsx
- packages/web/src/features/manage-club/funding/detail/components/NonCorpEvidenceList.tsx
- packages/web/src/features/manage-club/funding/detail/components/OtherEvidenceList.tsx
- packages/web/src/features/manage-club/funding/detail/components/TransportationEvidenceList.tsx
- packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
- packages/web/src/features/manage-club/funding/frames/FundingForm.tsx
- packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
- packages/web/src/features/manage-club/funding/hooks/useCreateFunding.ts
- packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
- packages/web/src/features/manage-club/funding/services/useDeleteFunding.ts
- packages/web/src/utils/Date/getKSTDate.ts
It closes #1331 
변경 사항:
- 상세조회 api 연결
- 삭제 api 연결
특이사항:
- 현재 백엔드 이슈로 신청 내역 리스트가 비어있으면 에러가 납니다 병찬이한테 말함
https://github.com/user-attachments/assets/ac2c4ba2-6be2-4d36-97e6-f90fa0869c64
- 없음
> 1331 connect apifnd002 apifnd004

- packages/api/src/drizzle/schema/activity.schema.ts
- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/model/activity.summary.model.ts
- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.public.service.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/api/src/feature/club/model/club.summary.model.ts
- packages/api/src/feature/club/repository/club.repository.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/api/src/feature/funding/service/funding.service.ts
- packages/api/src/feature/user/model/executive.summary.model.ts
- packages/api/src/feature/user/repository/executive.repository.ts
- packages/api/src/feature/user/service/user.public.service.ts
- packages/interface/src/api/activity/endpoint/apiAct028.ts
- packages/interface/src/api/activity/type/activity.type.ts
> 1378 feat act028

- packages/api/src/feature/activity/service/activity.activity-term.service.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct028.ts
- packages/interface/src/api/activity/type/activity.type.ts
> refactor: update activity summary type and response handling

- packages/web/src/utils/Date/getKSTDate.ts
> update frontend getKSTDate logic

- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/interface/src/api/activity/endpoint/apiAct024.ts
- packages/web/src/features/executive/activity-report/components/ExecutiveClubActivitiesTable.tsx
> feat: update activity API response with commentedAt and editedAt fields

- packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
> update check clubId logic in FudningDetailFrame

- packages/api/src/feature/club/service/club.public.service.ts
- packages/api/src/feature/funding/service/funding.service.ts
> feat: add club delegate check and funding deadline validation methods

- packages/api/src/feature/club/service/club.service.ts
> feat: filter out specific club IDs from club list

- packages/api/src/drizzle/schema/funding.schema.ts
- packages/api/src/feature/club/model/club.summary.model.ts
- packages/api/src/feature/club/repository/club.repository.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/api/src/feature/funding/controller/funding.controller.ts
- packages/api/src/feature/funding/model/funding.comment.model.ts
- packages/api/src/feature/funding/model/funding.summary.model.ts
- packages/api/src/feature/funding/repository/funding.comment.repository.ts
- packages/api/src/feature/funding/repository/funding.repository.ts
- packages/api/src/feature/funding/service/funding.service.ts
- packages/api/src/feature/user/repository/executive.repository.ts
- packages/api/src/feature/user/repository/professor.repository.ts
- packages/api/src/feature/user/service/user.public.service.ts
- packages/interface/src/api/club/type/club.type.ts
- packages/interface/src/api/funding/endpoint/apiFnd005.ts
- packages/interface/src/api/funding/endpoint/apiFnd006.ts
- packages/interface/src/api/funding/endpoint/apiFnd008.ts
- packages/interface/src/api/funding/endpoint/apiFnd009.ts
- packages/interface/src/api/funding/endpoint/apiFnd010.ts
- packages/interface/src/api/funding/type/funding.comment.type.ts
- packages/interface/src/api/funding/type/funding.type.ts
- packages/interface/src/api/user/type/user.type.ts
> 1420 feat api fnd008 fnd009 fnd010

- packages/api/src/feature/funding/controller/funding.controller.ts
- packages/api/src/feature/funding/repository/funding.repository.ts
- packages/api/src/feature/funding/service/funding.service.ts
- packages/interface/src/api/funding/endpoint/apiFnd014.ts
- packages/interface/src/api/funding/endpoint/apiFnd015.ts
- packages/interface/src/api/funding/endpoint/apiFnd016.ts
> 1431 feat api014 015 016

- packages/api/src/feature/funding/service/funding.service.ts
- packages/interface/src/api/funding/endpoint/apiFnd013.ts
- packages/web/src/app/executive/funding/[id]/page.tsx
- packages/web/src/app/manage-club/funding/[id]/page.tsx
- packages/web/src/common/components/FlexWrapper.tsx
- packages/web/src/common/components/Forms/UnitInput.tsx
- packages/web/src/features/manage-club/funding/detail/components/ExecutiveFundingReviewSection.tsx
- packages/web/src/features/manage-club/funding/detail/components/FundingStatusSection.tsx
- packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
- packages/web/src/features/manage-club/funding/hooks/useGetInitialFundingForm.ts
- packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
- packages/web/src/features/manage-club/funding/services/_atomic/fndApiList.ts
- packages/web/src/features/manage-club/funding/services/useExecutiveReviewFunding.ts
- packages/web/src/features/manage-club/funding/services/useGetFunding.ts
- packages/web/src/features/manage-club/funding/services/usePostFundingReview.ts
It closes #1395 
/executive/funding/[id] 구현
+ 2/7 추가: unit을 누르면 전체 금액이 입력돼요
https://github.com/user-attachments/assets/88f3d471-a9c9-4654-a173-08e022715729
- 없음
> impl funding detail page for executive

- packages/web/src/constants/manageClubFunding.ts
- packages/web/src/features/manage-club/funding/components/NonCorpEvidenceBlock.tsx
- packages/web/src/features/manage-club/funding/hooks/useCreateFunding.ts
- packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
- packages/web/src/utils/Date/formatDate.ts
It closes #1436 
지원금 신청 시 비법인 거래 증빙 파일 업로드 필드가 없어서 신청 에러 나는 이슈 해결함
- 없음
> add file upload field in NonCorpEvidenceBlock

- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/api/src/feature/funding/controller/funding.controller.ts
- packages/api/src/feature/funding/service/funding.service.ts
- packages/web/src/features/manage-club/funding/detail/components/NonCorpEvidenceList.tsx
> add nonCorporateTransaction file data in NonCorpevidenceList

- packages/api/src/feature/funding/repository/funding.repository.ts
- packages/web/src/features/manage-club/funding/detail/components/ExecutiveFundingReviewSection.tsx
It closes #1449 
- 작업요약1 : https://www.notion.so/sparcs/e35c2932f9a740c4835896e2dd2d78dc?pvs=4
- 작업요약2 : https://www.notion.so/sparcs/2fdb861f91ad40948a09d2bfa3465a1b?pvs=4
1. API sheet: 
2. Figma: 
- 없음
- 없음
> 1449 fix api fnd 003 for put noncorp

- packages/web/src/features/credits/credits.ts
It closes #1460
- 겨울학기 크레딧을 추가했습니다.
- 없음
- 없음
1. 크레딧 페이지: http://localhost:3000/credits
> Add winter credits chacha

- packages/web/src/features/credits/credits.ts
- packages/web/src/features/my/frames/MyClubFrame.tsx
It closes #1462 
2025 겨울 크레딧에 ava 추가
1. API sheet: 
2. Figma: 
- 없음
- 없음
1. 크레딧 페이지: http://localhost:3000/credits
> add ava credit to 2025 winter

- packages/web/src/features/credits/credits.ts
<Kanban에 올려뒀어요>
- daystar의 credit 추가
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-20] feat: add daystar's credit

- packages/interface/src/api/registration/endpoint/apiReg014.ts
- packages/interface/src/api/registration/endpoint/apiReg021.ts
- packages/interface/src/api/registration/endpoint/apiReg024.ts
- packages/web/src/common/components/ExecutiveRegistrationTable.tsx
- packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
- 프로덕션 버그에 있는 https://www.notion.so/sparcs/b185d36ff2db464d8f347d286d9d48e6?pvs=4 수정 (테이블 동아리 이름)
- 테이블에 검색 로직쪽도 동아리 이름 수정
- 오타 수정
1. API sheet: 
2. Figma: 
- 없음
- 없음
1. 동아리 등록 신청 내역: http://localhost:3000/executive/register-club
2. 신청 내역 상세페이지: http://localhost:3000/executive/register-club/171
3. 집행 부원 대시보드: http://localhost:3000/executive
> [TU-27] refactoring executive > register-club code

- packages/api/src/feature/club/club.module.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/api/src/feature/division/service/division.public.service.ts
- packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg012.ts
- packages/interface/src/api/registration/endpoint/apiReg025.ts
- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/my/components/MyClubTable.tsx
- packages/web/src/features/my/services/_mock/mockMyClubRegisterDetail.ts
- packages/web/src/features/register-club/services/_mocks/mockMyRegistration.ts
https://www.notion.so/sparcs/1a1c25603b0b808181a0c160df26e86f?pvs=4
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-65] api reg 025 for club registration availability

- packages/web/src/features/credits/credits.ts
It closes [TU-6]
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-6] feat: add credits for chan in multiple semesters

- packages/api/src/feature/club/club.module.ts
- packages/api/src/feature/club/repository/club.club-student-t.repository.ts
- packages/api/src/feature/club/service/club.service.ts
- packages/api/src/feature/file/file.module.ts
- packages/api/src/feature/registration/club-registration/club-registration.module.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/web/src/features/credits/credits.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> 2025-02-24 15:52 지원금 조회 버그 수정

- packages/web/src/features/credits/credits.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-79] gb credit

- .gitignore
- packages/web/src/features/credits/credits.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-51] hama credit

- .vscode/settings.json
- eslint.config.mjs
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-81] Add eslint rule for windows developers

- packages/api/src/feature/user/repository/professor.repository.ts
https://www.notion.so/sparcs/1abc25603b0b80ef9cedc93fea0832a3?pvs=4
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-84] fix find professor

- packages/api/src/feature/activity/service/activity.service.ts
- packages/api/src/feature/user/repository/professor.repository.ts
재등록 버그 수정 : 지도교수 find  로직 수정
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> 2025-03-03 19:30 지도교수 find 로직 버그 수정

- packages/web/src/features/credits/credits.ts
> [TU-58] default credit 추가

- packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
- packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberFrame.tsx
- 동아리 등록, 회원 등록 신청 내역 테이블 페이지네이션 수정
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-93] 동아리 등록, 회원 등록 신청 내역 테이블 pagination 수정

- packages/web/src/features/credits/credits.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-57] gb credit

- packages/api/src/drizzle/schema/registration.schema.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-112] add semester id for registration member

- packages/api/src/feature/club/repository/club.repository.ts
- packages/api/src/feature/club/service/club.service.ts
[회원등록 관련 분과 정렬 수정](https://www.notion.so/sparcs/1acc25603b0b80c2a21be0f6aa9a45d4?pvs=4)
1. 동아리 조회 페이지: http://localhost:3000/clubs
> [TU-92] 회원등록 관련 분과 정렬 수정

- packages/web/src/features/credits/credits.ts
> [TU-109] ms credit

- packages/api/src/feature/division/service/division.public.service.ts
- packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
- packages/api/src/feature/user/repository/student.repository.ts
- packages/api/src/feature/user/service/user.public.service.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> fix: exeuctive dashboard for member registration and query faster

- packages/api/src/feature/registration/member-registration/controller/member-registration.controller.ts
- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg026.ts
- packages/interface/tsconfig.json
https://sparcs.slack.com/archives/C06SM9MN25C/p1741991699640489
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-131] api 026 for member registration count 

- packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
- packages/api/src/feature/registration/member-registration/controller/member-registration.controller.ts
- packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
- packages/interface/src/api/registration/endpoint/apiReg027.ts
- packages/interface/src/api/registration/endpoint/apiReg028.ts
https://www.notion.so/sparcs/Registration-Deadline-api-1b9c25603b0b804a9e22d1e627a46d1f?pvs=4 
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-132] new Registration Deadline get APIs

- packages/web/src/features/clubs/components/ClubInfoCard/ClubInfoItem.tsx
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 성격을 너무 길게 쓰지 않도록 권장하는 것이 좋을듯 합니다
1. 동아리 상세조회 페이지: http://localhost:3000/clubs/127
> [TU-138] 동아리 상세 페이지 성격 정렬 개선

- packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
- packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberFrame.tsx
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> Version 0.0.57

- packages/api/src/feature/club/service/club.service.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> Versoin 0.0.58

- packages/api/src/feature/club/service/club.service.ts
- packages/web/src/common/frames/NoSemesterInfo.tsx
- packages/web/src/features/manage-club/frames/ManageClubFrame.tsx
- packages/web/src/features/manage-club/frames/MemberManageFrame.tsx
- 동아리 관리 페이지 "회원 명단" 에 "24 가을" 멤버들이 나오는 이슈 해결
- 동아리 등록 취소 시 이미 승인된 경우 회원 명단에서 삭제
> Version 0.0.59

- packages/api/src/common/model/entity.model.ts
- packages/api/src/common/repository/base.repository.ts
- packages/api/src/feature/funding/model/funding.comment.model.ts
- packages/api/src/feature/funding/repository/funding.comment.repository.ts
- packages/api/src/feature/funding/service/funding.service.ts
- packages/api/src/feature/registration/member-registration/model/member.registration.model.ts
- packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
- packages/interface/src/api/funding/endpoint/apiFnd013.ts
- packages/interface/src/api/funding/type/funding.comment.type.ts
- packages/interface/src/api/registration/type/member.registration.type.ts
- packages/interface/src/common/utils/field-operations.ts
It closes [TU-153]
- application level에서 런타임중 검증 가능한 exclude 데코레이터 추가
- 모델에 to 메서드를 추가하여, exclude 하고 남은 필드가 모두 존재하는지 런타임에서 검증한후, 디비 필드에 맞게 변환하여 반환.
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-153] refactor create and put interface using model decorator

- packages/api/src/feature/auth/service/auth.service.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> Version 0.0.61

- packages/api/src/feature/auth/repository/auth.repository.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> Version 0.0.62

- packages/api/src/feature/auth/controller/auth.controller.ts
- packages/api/src/feature/auth/service/auth.service.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> fix: dsafjkdsfajkdfsaj;fdsa;jdfasjkl;adsf;lk

- packages/web/src/constants/paths.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> Version 0.0.66

- packages/api/src/feature/auth/service/auth.service.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> Version 0.0.67

- packages/api/src/common/repository/base.repository.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> TU-164 fix: gb. executive member register 오류 수정

- packages/api/src/common/repository/base.repository.ts
nested query (and, or, not) 처리하는 make where clause 에서 약간의 문제가 보여서 처리했슴다.
+ 쿼리가 아닌 것을 넣었을 때 어떻게 에러를 발생시킬 지에 대해 좀더 고민중
일단은 추가 처리를 해야 하는 Date 같은 것들에 대해서 추가 처리를 하지 않고 넘긴 경우에는 throw error를 하게 해뒀슴다
> [TU-165] base repository fix for nested query

- packages/api/src/feature/club/service/club.service.ts
- packages/api/src/feature/notice/model/notice.model.ts
- packages/api/src/feature/notice/repository/notice.repository.ts
- packages/api/src/feature/notice/service/notice.service.ts
- packages/interface/src/api/notice/type/notice.type.ts
공지사항 Notice 엔티티 정의 및 레포지토리 작성
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-101] 공지사항 Notice 엔티티 정의 및 레포지토리 작성

- packages/web/package.json
- pnpm-lock.yaml
- next js 취약점 관련 문제가 해결된 14.2.25로 버전을 올립니다. 
- breaking change 없음
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-161] next js 취약점 대응 버전 업

- packages/api/src/common/util/decorators/time-decorator.ts
- packages/api/src/common/util/util.ts
- packages/api/src/feature/semester/model/semester.model.ts
- packages/interface/src/common/utils/field-operations.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> TU-176 fix timezone in db

- packages/api/src/drizzle/schema/notice.schema.ts
- packages/api/src/feature/notice/model/notice.model.ts
- packages/interface/src/api/notice/type/notice.type.ts
공지사항을 orderby하기 위한 articleId 추가
크롤링을 할 때 글 링크에 딸려오는 articleId=...... 을 의미함
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-187] feat: add articleId column to notice

- packages/api/src/common/base/base.multi.repository.ts
- packages/api/src/common/base/base.single.repository.ts
- packages/api/src/feature/funding/repository/funding.comment.repository.ts
- packages/api/src/feature/notice/repository/notice.repository.ts
- packages/api/src/feature/registration/repository/member-registration.repository.ts
- packages/api/src/feature/semester/repository/activity.deadline.repository.ts
- packages/api/src/feature/semester/repository/activity.duration.repository.ts
- packages/api/src/feature/semester/repository/funding.deadline.repository.ts
- packages/api/src/feature/semester/repository/registration.deadline.repository.ts
- packages/api/src/feature/semester/repository/semester.repository.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-189] AS base repository

- packages/api/src/feature/funding/service/funding.service.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-204] 집행부의 이전 2학기 지원금 데이터 조회 요청 처리

- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/registration/controller/registration.controller.ts
- packages/web/src/app/club-registration/[id]/page.tsx
- packages/web/src/app/club-registration/page.tsx
- packages/web/src/app/executive/register-club/page.tsx
- packages/web/src/common/components/ExecutiveRegistrationTable.tsx
- packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
- 임시로 집행부원쪽 코드로 동아리등록 신청내역 전체공개 링크 추가함 
- 현재 메인페이지에서 진입경로 없음 -> 추후에 리아랑 논의하여 추가해야 함
1. API sheet: 
2. Figma: 
- 없음
- 없음
1. 동아리 등록신청 내역 페이지: http://localhost:3000/club-registration
2. 동아리 등록신청 내역 페이지: http://localhost:3000/club-registration/{id}
> [TU-205] 동아리 등록 신청내역 전체 공개 

- packages/web/src/constants/paths.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> Version 0.0.72

- packages/api/package.json
- packages/api/src/main.ts
- packages/api/tsconfig.json
- turbo.json
- nestJS 핫리로드 기능 활성화
- nestJS 실행 시 기존 터미널 삭제되던 현상 방지.
- `turbo.json`에 필수적인 옵션만 남김.
> [TU-206] 바로 터보레포 정상화! OUT!! 역시 정상화는 김 현 수

- packages/web/src/common/components/Forms/SearchSelect.tsx
- packages/web/src/features/activity-report/components/executive/ChargedChangeActivityModalContent.tsx
- packages/web/src/features/activity-report/components/executive/ChargedChangeClubModalContent.tsx
- packages/web/src/features/activity-report/components/executive/ExecutiveCurrentActivityReportSection.tsx
- packages/web/src/features/activity-report/frames/executive/ExecutiveActivityReportFrame.tsx
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-209] 담당자 변경 기능에 검색기능 추가 및 요청 완료 후 체크박스 해제 기능 추가

- packages/api/src/feature/semester/service/semester.service.ts
- packages/interface/src/api/activity/endpoint/apiAct018.ts
- packages/web/src/app/manage-club/activity-report/[id]/edit/page.tsx
- packages/web/src/app/manage-club/activity-report/create/page.tsx
- packages/web/src/features/activity-report/constants/index.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-208] Activity Deadline Optional화

- packages/web/src/features/activity-report/constants/index.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-216] 활보 마감 기한 텍스트 표시 버그 수정

- packages/api/src/common/base/base.multi.repository.ts
- packages/api/src/common/base/base.repository.ts
- packages/api/src/common/base/base.single.repository.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-220] Base Repository timezone for create

- packages/api/src/drizzle/schema/activity.schema.ts
- packages/api/src/feature/activity/activity.module.ts
- packages/api/src/feature/activity/model/activity-comment.model.ts
- packages/api/src/feature/activity/model/activity.model.new.ts
- packages/api/src/feature/activity/repository/activity-comment.repository.ts
- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/domain/src/activity/activity-comment.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-221] Activity Comment 모델 레포 서비스

- packages/api/src/common/base/base.multi.repository.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-223] Base Multi table find add isnull

- packages/api/src/feature/notice/controller/notice.controller.ts
- packages/api/src/feature/notice/repository/notice.repository.ts
- packages/api/src/feature/notice/service/notice.service.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 최종업데이트시간띄우기
정상화
> [TU-231] fix: notice sort bug

- packages/web/src/constants/localStorage.ts
- packages/web/src/features/manage-club/funding/constants/fundingDeadlineEnumToString.ts
- packages/web/src/features/manage-club/funding/frames/CreateFundingFrame.tsx
- packages/web/src/features/manage-club/funding/frames/EditFundingFrame.tsx
- packages/web/src/features/manage-club/funding/frames/FundingForm.tsx
- packages/web/src/utils/index.ts
- 지원금 작성 시 임시저장 기능 추가.
1. API sheet: 
2. Figma: 
- 없음
- 없음
1. 지원금 신청: http://localhost:3000/manage-club/funding/create
> [TU-17] 지원금 임시저장 기능

- packages/web/src/common/components/Modal/PatchNoteModal.tsx
- packages/web/src/common/providers/AuthContext.tsx
- packages/web/src/constants/localStorage.ts
- packages/web/src/constants/patchNote.ts
Add PatchNoteModal.tsx
This feature records in localstorage the version of the latest patch note a user has seen from this computer. New patch note pops up depending on whether an unseen (new, latest) patch note is published.
It closes TU-225
1. API sheet: X
2. Figma: https://www.figma.com/design/gm0BeqvuY5dsA86XyRgEc3/Clubs?node-id=15930-52225&t=z8U0PskRsr1WoJJF-4
- 없음
@Engineer-HaMa 패치노트 추가해주세요!
앞으로 패치노트를 실제로 적을 때, packages/web/src/constants/patchNote.ts를 수정해주시면 됩니다!
1. 메인 페이지: http://localhost:3000/
> [TU-225] Add PatchNoteModal.tsx

- package.json
- packages/api/package.json
- packages/api/src/feature/auth/service/auth.service.ts
- packages/web/src/constants/patchNote.ts
- turbo.json
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> Version 0.0.76

- packages/web/src/features/credits/credits.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-257] summer credit - eel

- packages/web/src/common/components/Modal/index.tsx
- 작업요약1
- 작업요약2
반응형 breakpoint와 maxWidth가 맞지 않아 breakpoint 부근에서 표가 튀어나오던 문제 해결
1. API sheet: 
2. Figma: 
- 없음
- 없음
AS-IS
TO-BE
https://github.com/user-attachments/assets/49b27a6c-237d-4686-8e7c-e4425eb5593d
1. 집행부 활보 조회 페이지: http://localhost:3000/executive/activity-report
> [TU-245] modal maxwidth 삭제

- packages/web/src/features/credits/credits.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-260] summer credit

- packages/web/src/features/credits/credits.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-254] HaMa credit

- packages/interface/src/api/activity/endpoint/apiAct027.ts
- packages/interface/src/common/zodUtil.ts
- packages/web/src/constants/patchNote.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-191] 길이가 1인 배열 인식 안되는 버그 수정

- packages/web/src/i18n/README.md
- i18n readme를 추가합니다
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-271] i18n readme

- packages/web/src/common/providers/AuthContext.tsx
- packages/web/src/utils/localStorage.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-276] Next가 500과 함께 서빙하는 문제 해결하기

- .zed/settings.json
- packages/api/src/feature/club/controller/club.controller.ts
- packages/api/src/feature/club/delegate/delegate.controller.ts
- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/domain/package.json
- packages/domain/src/club/club-delegate.ts
- packages/domain/src/club/club.ts
- packages/interface/package.json
- packages/interface/src/api/club/endpoint/apiClb001.ts
- packages/interface/src/api/club/endpoint/apiClb002.ts
- packages/interface/src/api/club/endpoint/apiClb003.ts
- packages/interface/src/api/club/endpoint/apiClb004.ts
- packages/interface/src/api/club/endpoint/apiClb005.ts
- packages/interface/src/api/club/endpoint/apiClb006.ts
- packages/interface/src/api/club/endpoint/apiClb007.ts
- packages/interface/src/api/club/endpoint/apiClb008.ts
- packages/interface/src/api/club/endpoint/apiClb009.ts
- packages/interface/src/api/club/endpoint/apiClb010.ts
- packages/interface/src/api/club/endpoint/apiClb011.ts
- packages/interface/src/api/club/endpoint/apiClb012.ts
- packages/interface/src/api/club/endpoint/apiClb013.ts
- packages/interface/src/api/club/endpoint/apiClb014.ts
- packages/interface/src/api/club/endpoint/apiClb015.ts
- packages/interface/src/api/club/endpoint/apiClb016.ts
- packages/interface/src/api/club/index.ts
- packages/web/src/features/manage-club/services/_mock/mockDelegate.ts
- packages/web/src/features/manage-club/services/getChangeDelegateRequests.ts
- pnpm-lock.yaml
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-277] Add club interface doc

- packages/api/src/drizzle/schema/user.schema.ts
- packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/api/src/feature/club/repository-old/club.club-student-t.repository.ts
- packages/api/src/feature/overview/repository/overview.repository.ts
- packages/api/src/feature/registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/service/registration.service.ts
- packages/api/src/feature/user/repository/executive.repository.ts
- packages/api/src/feature/user/repository/old.professor.repository.ts
- packages/api/src/feature/user/repository/old.student.repository.ts
- packages/api/src/feature/user/repository/professor.repository.ts
- packages/api/src/feature/user/repository/student.repository.ts
- packages/api/src/feature/user/repository/user.repository.ts
- Student, Executive, Professor, Employee 테이블에 각각 존재하였던 전화번호를 User 테이블로 통일
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-270] 유저 전화번호 통일

- packages/api/src/drizzle/schema/funding.schema.ts
- packages/api/src/feature/funding/repository/funding.repository.ts
- funding.schema 수정: student를 사용해야 할 곳에 studentT가 사용되고 있어서 hot fix 되었으나 변수명은 바뀌지 않아 수정
- funding.repository 수정: 현재 유효한 학생인지 확인 (불필요한 로직일 경우 revert 예정)
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-281] 교통비 지원금 studentT 혼용

- packages/api/src/feature/user/repository/old.student.repository.ts
- 잘못된 인자값을 수정 
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-270] 전화번호 수정이 안되는 오류 수정

- packages/api/src/feature/semester/controller/semester.controller.ts
- packages/api/src/feature/semester/service/semester.service.ts
- packages/interface/src/api/semester/apiSem005.ts
- packages/interface/src/api/semester/index.ts
- packages/web/src/common/services/getSemesters.ts
- packages/web/src/features/executive/components/SemesterFormModal.tsx
- packages/web/src/features/executive/frames/ExecutiveDashboardFrame.tsx
- packages/web/src/features/executive/frames/ManageSemeterFrame.tsx
- packages/web/src/features/executive/services/deleteSemester.ts
- packages/web/src/features/executive/services/postSemester.ts
- packages/web/src/features/executive/services/putSemester.ts
- packages/web/src/utils/getSemesterNow.ts
https://github.com/user-attachments/assets/9dfda27f-9a15-4107-a243-792883886497
- sem001 api가 학기 목록 받아오도록 수정
- 현재 학기 가져오는 sem005 api 구현
- 학기 추가 / 수정 가능한 모달 구현
- 학기 보여주는 표 집행부원 대시보드에 추가
- 학기 수정 / 삭제 / 생성 실패 시 에러 메시지 노출
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-288] 학기 추가/삭제 페이지

- packages/web/src/features/manage-club/funding/detail/components/FundingInfoList.tsx
- packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-296] Add link from funding to activity-report

- package.json
- packages/api/src/app.module.ts
- packages/api/src/drizzle/schema/operation-committee.schema.ts
- packages/api/src/feature/activity/activity.module.ts
- packages/api/src/feature/activity/service/activity.service.new.ts
- packages/api/src/feature/operation-committee/controller/operation-committee.controller.ts
- packages/api/src/feature/operation-committee/operation-committee.module.ts
- packages/api/src/feature/operation-committee/repository/operation-committee.repository.ts
- packages/api/src/feature/operation-committee/service/operation-committee.service.ts
- packages/domain/src/operation-committee/operation-committeekey.ts
- packages/interface/src/api/operation-committee/apiOpC001.ts
- packages/interface/src/api/operation-committee/apiOpC002.ts
- packages/interface/src/api/operation-committee/apiOpC003.ts
- packages/interface/src/api/operation-committee/index.ts
- 시크릿키 생성 CRD (/executive/operation-committees/secret-key)
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-289] operation committee secret key CRD

- .env.example
- packages/api/package.json
- packages/api/src/common/util/logger.ts
- packages/api/src/env.ts
- pnpm-lock.yaml
- 기존 Winston 로거에 Sentry Transport 추가
- .env에 SENTRY_DSN 필드 추가
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-280] Clubs 로그 정리하기 

- packages/api/src/feature/semester/service/activity-duration.service.ts
- packages/interface/src/api/semester/apiSem007.ts
- packages/web/src/app/executive/activity-report/deadline/page.tsx
- packages/web/src/features/executive/components/ActivityDeadlineFormModal.tsx
- packages/web/src/features/executive/components/ActivityDeadlineSection.tsx
- packages/web/src/features/executive/components/ActivityDeadlineTable.tsx
- packages/web/src/features/executive/frames/ExecutiveDashboardFrame.tsx
- packages/web/src/features/executive/frames/ManageActivityDeadlineFrame.tsx
- packages/web/src/features/executive/hooks/useGroupActivityDeadlines.ts
- packages/web/src/features/executive/services/getActivityDeadlines.ts
- packages/web/src/features/executive/services/useCreateActivityDeadline.ts
- packages/web/src/features/executive/services/useDeleteActivityDeadline.ts
https://github.com/user-attachments/assets/153ca4e4-d2fd-43ce-9a25-5ef463f0d5a1
질문 - 원래 겨울-봄이랑 봄 활동기간의 활동보고서 기간이 동기화 되는게 맞나요?
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-292] 활동보고서 신청 기간 조회/추가/제거 기능 구현하기

- packages/api/src/feature/auth/dto/sparcs-sso.dto.ts
- packages/api/src/feature/auth/repository/auth.repository.ts
- packages/api/src/feature/auth/service/auth.service.ts
- packages/api/src/feature/auth/util/user-info-extractor.ts
- packages/api/test/unit/auth/user-info-extractor.spec.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-310] 교수님 로그인 안되는 에러 해결

- packages/web/src/features/credits/credits.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-320] amet 2025F credit

- packages/web/src/features/credits/credits.ts
add edge credit
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-315] edge credit

- packages/web/src/common/providers/store/useFeatureFlagStore.ts
- 새로고침 때마가 로컬스토리지를 검사하고 갱신
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-324] 동아리/회원 등록기간에만 상단바 메뉴 보이게 만들기

- packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/api/src/feature/club/repository-old/club-old.repository.ts
- packages/api/src/feature/user/repository/old.student.repository.ts
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-325] 대표자 변경 문제 해결

- packages/web/src/app/my/page.tsx
- packages/web/src/features/my/components/ProfessorRegistrationBanner.tsx
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-337] 교수님 마이페이지 상단 배너 추가
