- packages/web/src/common/components/Forms/ItemNumberInput.tsx
- packages/web/src/common/components/Forms/PhoneInput.tsx
- packages/web/src/common/components/Forms/Select.tsx
- packages/web/src/common/components/Forms/TextInput.tsx
It closes #71 
#31 에서 개발한 Forms에 상태 주입을 추가함
```
import { useState } from "react";
import Select, { SelectItem } from "../common/components/Forms/Select";
const SelectTest = () => {
const [selectedValue, setSelectedValue] = useState("");
const items: SelectItem[] = [
{ label: "옵션 1", value: "1", selectable: true },
{ label: "옵션 2", value: "2", selectable: false },
];
return (
<>
<Select
items={items}
selectedValue={selectedValue}
onSelect={setSelectedValue}
label="select에 들어갈 제목 입력"
disabled // disabled 아닐 경우 이 줄 삭제
/>
<p>선택된 값: {selectedValue}</p>{" "}
</>
);
};
export default SelectTest;
```
```
import { useState } from "react";
import TextInput from "../common/components/Forms/TextInput";
const TextInputTest = () => {
const [inputValue, setInputValue] = useState('');
return (
<div> …
```
> #71 Fix Form components

- packages/web/src/common/components/Forms/ItemNumberInput.tsx
- packages/web/src/common/components/Forms/Select.tsx
- packages/web/src/common/components/Forms/TextInput.tsx
It closes #74 
#31 참고
```
import { useState } from "react";
import Select, { SelectItem } from "../common/components/Forms/Select";
const SelectTest = () => {
const [selectedValue, setSelectedValue] = useState("");
const [hasSelectError, setHasSelectError] = useState(false);
const items: SelectItem[] = [
{ label: "옵션 1", value: "1", selectable: true },
{ label: "옵션 2", value: "2", selectable: false },
];
return (
<div>
<Select
items={items}
selectedValue={selectedValue}
onSelect={setSelectedValue}
label="select에 들어갈 제목 입력"
disabled // disabled 아닐 경우 이 줄 삭제
setErrorStatus={setHasSelectError}
/>
<p>선택된 값: {selectedValue}</p>
{hasSelectError && <div>Error in input</div>}
</div>
);
};
export default SelectTest;
```
```
import { useState } from "react";
import TextInput from …
```
> 74 fix forms components

- packages/web/src/common/components/StepProcess/StepProcess.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/index.tsx
- packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
It closes #67 
- RentalNoticeFrame에서 체크가 되지 않아도 다음으로 넘어가는 문제가 있어서 함께 해결함
- 이름, 연락처, 동아리 목록 받아오는 API와 연결
> 67 impl basic info for rental page

- packages/interface/src/api/user/endpoint/apiUsr001.ts
- packages/interface/src/api/user/index.ts
It closes #80 
신청 관련 feature에서 활용하기 위한 유저 프로필(유저명, 연락처, 활동중인 동아리 등)을
가져올 수 있는 user/my API의 인터페이스 구현입니다.
- 없음
> feat: impl user/my interface

- packages/web/src/common/components/Checkbox.tsx
It closes #96 
기존 checkbox 사용 방식이랑 동일. disabled 되어야 하면 disabled를 prop으로 넣어주면 됨. 
- (필요시) disabled 체크박스 디자인 수정
> feat: change cursor hovering

- packages/web/src/common/components/Modal/Modal.tsx
- packages/web/src/common/components/Modal/ModalExample.tsx
- packages/web/src/common/components/Modal/index.tsx
#57 Modal Component 추가
1. Modal 열고 닫는 상태관리는 Modal 밖에서 조정 가능하게 구현하였습니다. Modal을 사용하려는 컴포넌트(ex.ModalExample)에서 상태 관리 해주시면 될 것 같습니다.
2. max-height 300px 로 되어 있고 overflow시 스크롤 됩니다.
3. 컴포넌트 사용예시: `ModalExample`
common > components > Modal 폴더 하위에 `ModalExample` 라는 예제 파일 추가하였습니다.
테스트 시 notice 페이지에 `ModalExample` 컴포넌트를 추가하여 테스트 하면 될 것 같습니다.
`const Notice = () => (
<>
<ModalExample />
<NoticePageMainFrame />
</>
);`
- 없음
> feat: add Modal component

- packages/web/src/common/components/Typography.tsx
…ed colors
The `color` prop accepts either a top-level color key from `Theme["colors"]` or a nested color key in the format `"ColorKey.NestedColorKey"`.
The available color keys are defined in the `ThemeColors` type, which is generated based on the structure of `Theme["colors"]`.
It closes #125 
- 없음
> Typography support custom styles and awesome types

- packages/web/src/common/components/Modal/CancellableModalContent.tsx
- packages/web/src/common/components/Modal/ConfirmModalContent.tsx
- packages/web/src/common/components/Typography.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/SelectRangeCalendar.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/RangeCalendar.tsx
- packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/SelectRange.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/index.tsx
- packages/web/src/features/rental-business/service/_mock/mockAvailableRental.ts
- packages/web/src/features/rental-business/service/getAvailableRentals.ts
It closes #52 
CancellableModalContent: modal에 확인/취소 등 두 개의 버튼 있을 때
```
<Modal>
<CancellableModalContent
onConfirm={handleConfirm}
onClose={() => setShowPeriodModal("none")}
closeButtonText = "취소"
confirmButtonText = "확인"
>
대여 기간을 변경하면 입력한 대여 물품 정보가 모두 초기화됩니다.
<br />
ㄱㅊ?
</CancellableModalContent>
</Modal>
```
ConfirmModalContent: 확인만 있는 modal
```
<Modal>
<ConfirmModalContent onConfirm={onConfirm} confirmButtonText = "확인">
신청이 완료되었습니다.
<br />
확인을 누르면 신청 내역 화면으로 이동합니다.
</ConfirmModalContent>
</Modal>
```
- api 마저 연결 (usr001, rnt001, rnt002) #144
> add modal and interface for rental business page

- packages/api/src/common/util/logger.ts
- packages/api/src/feature/notice/controller/notice.controller.ts
It closes #124
비서 세팅 가져오면서 winston이 포함되어 있는것을 확인했고,
"development", "test" 환경에서 사용 가능한 로그 레벨만 debug까지 올려 로그 출력까지 확인한 상태입니다.
사용예시는 notice controller에서 확인할 수 있습니다.
- [] 배포시 로거 설정 확인하기
> 124 Add log level into backend

- packages/web/src/common/components/Card.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
- packages/web/src/features/clubDetails/components/ClubDetailCard.tsx
- packages/web/src/features/clubDetails/components/ClubInfoCard.tsx
- packages/web/src/features/clubDetails/components/PersonInfoCard.tsx
- packages/web/src/features/clubs/components/ClubCard.tsx
- packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
- packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
- packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
- packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
- packages/web/src/features/landing/components/ServiceCard.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoThirdFrame.tsx
- packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
#169 StyledCard Refactoring
1. 기존의 StyledCard 만들어서 사용하는 부분 대부분 삭제하고 Card 컴포넌트에 optinal props padding, gap 추가 함
2. Card 컴포넌트 'align-self: stretch' 추가 함 (모든 Card 사용하는 곳에서 다 넣어서 사용하고 있었음)
예시 페이지 
그 외 파일 수정이 들어간 모든 페이지 기존과 스타일이 같은지 확인 부탁드립니다.
- 없음
> StyledCard Refactoring

- packages/web/next.config.mjs
- packages/web/package.json
- packages/web/src/common/components/Calendar/_atomic/CalendarDate.tsx
- packages/web/src/common/components/Card.tsx
- packages/web/src/common/components/Filter/_atomic/FilterButton.tsx
- packages/web/src/common/components/FoldableSection.tsx
- packages/web/src/common/components/Forms/ItemNumberInput.tsx
- packages/web/src/common/components/Forms/Select.tsx
- packages/web/src/common/components/Icon.tsx
- packages/web/src/common/components/NavTools/NavItem.tsx
- packages/web/src/common/components/Radio/index.tsx
- packages/web/src/common/components/Timetable/_atomic/TimetableDateList.tsx
- packages/web/src/common/components/Timetable/_atomic/TimetableTable.tsx
- packages/web/src/common/components/Toggle.tsx
- packages/web/src/common/components/Typography.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
- packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/DesiredPickUpTimeSelection.tsx
- packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/TimeSlotList.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/_atomic/BinaryRadio.tsx
- packages/web/src/features/rental-business/components/ItemButton.tsx
- packages/web/src/features/rental-business/components/RentalList.tsx
- pnpm-lock.yaml
It closes #224 
브라우저에서 확인되는 자잘한 에러들에 관한 수정이 포함되어 있습니다.
- 반복되는 컴포넌트에 key가 포함되어 있지 않은 경우
- typography로 변경해야 하는 컴포넌트
- https://stackoverflow.com/questions/51791163/warning-prop-classname-did-not-match-when-using-styled-components-with-seman
위와 유사한 에러를 겪에서 SWC 옵션을 추가했습니다.
- styled-component prop 관련 에러
아래 공지를 확인해주세요
styled-component 관련하여 확인해야할 사항이 하나 정리되어서 올려봅니다!
먼저 문제상황은 styled componenet에 아래와 같이 속성을 추가할 때 발생하는데요,
```js
styled.div<{ have: boolean; selected: boolean }>
```
이렇게 속성을 추가하게되면 `have` attribute가 DOM을 통해 전달되며 리액트 경고가 발생하게 됩니다. 이와 유사한 방법으로 구현된 컴포넌트들에 대해 해결책으로 두가지 정도의 방법이 있습니다.
1. transent-prop으로 prop을 변경한다.
2. `shouldForwardProp` 을 해당 컴포넌트들에 추가한다
1번 방법이 가장 정석적인 방법으로, 위 예시에선 `have` 대신 `$have` 를 propName으로 이용하는 것이 해결책입니다. 다만 그렇게 되면 해당 common 컴포넌트를 사용하는 모든 코드들에 대해 propName을 변경해야 하는 불편함이 …
> Fix dom element prop console error

- packages/web/src/features/activity-certificate/frames/ActivityCertificateMainFrame.tsx
- packages/web/src/features/common-space/frames/CommonSpaceMainFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
- packages/web/src/features/notices/frames/NoticePageMainFrame.tsx
- packages/web/src/features/printing-business/frame/PrintingBusinessMainFrame.tsx
- packages/web/src/features/rental-business/frames/RentalMainFrame.tsx
It closes #219 
변경사항:
1. notice 페이지 BreadCrumb 추가
2. 활동보고서 작성 페이지의 BreadCrumb에 enableLast가 빠진 것 같아 추가하였습니다
아직 구현되지 않은 페이지인 것 같아요: 
1. /notice/[id] -> 공지사항 상세페이지 
3. 활동보고서 수정
4. 지원금 신청
5. 지원금 수정
> feat: add bread crumb to notice page

- packages/web/src/common/components/Header/index.tsx
It closes #286 
사파리에서 헤더의 블러 속성이 적용되지 않는 이슈입니다.
-webkit-backdrop-filter 속성을 추가하여 해결했습니다.
https://www.reddit.com/r/css/comments/12jhh10/solution_backdrop_filter_blur_doesnt_work_in/?rdt=55566
- before
- after
- 없음
> fix: fix blur error in safari

- packages/web/src/app/clubs/page.tsx
- packages/web/src/features/clubs/components/ClubListGrid.tsx
- packages/web/src/features/clubs/frames/ClubsPageMainFrame.tsx
It closes #311 
- 동아리 목록 페이지 반응형 디자인 추가
- 관련 피그마: https://www.figma.com/design/gm0BeqvuY5dsA86XyRgEc3/%ED%95%99%EC%88%A0%ED%98%91%EB%A0%A5-02.-%5B%EB%8F%99%EC%97%B0%ED%98%91%EB%A0%A5%EC%82%AC%EC%97%85%5D?node-id=3973-64092&m=dev
- 없음
> add responsive design to clubs page

- packages/web/src/features/manage-club/funding/create/components/EvidenceBlockTitle.tsx
- packages/web/src/features/manage-club/funding/create/components/OtherEvidenceBlock.tsx
- packages/web/src/features/manage-club/funding/create/frame/AddEvidenceFrame.tsx
- packages/web/src/features/manage-club/funding/create/frame/BasicEvidenceFrame.tsx
- packages/web/src/features/manage-club/funding/create/frame/FundingInfoFrame.tsx
It closes #352 
추가로 `FoldableSectionTitle` 사용에 있어 지금까지 children으로 넣어주면 되는 것을 불필요하게` {toggle && {들어갈 컴포넌트}}`를 사용하고 있어 수정함
- 없음
> impl evidence block for create funding

- packages/web/src/common/components/FileUpload.tsx
- packages/web/src/common/components/Select/index.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
- packages/web/src/features/manage-club/funding/create/components/FixtureEvidenceBlock.tsx
- packages/web/src/features/manage-club/funding/create/components/OtherEvidenceBlock.tsx
- packages/web/src/features/manage-club/funding/create/frame/AddEvidenceFrame.tsx
- packages/web/src/features/manage-club/funding/create/frame/BasicEvidenceFrame.tsx
- packages/web/src/features/manage-club/funding/create/frame/FundingInfoFrame.tsx
It closes #353
`Select`의 placeholder 설정을 위해 `Select` 코드 변경 있습니다
- (필요시) EvidenceUploadWithText 컴포넌트 분리
> impl fixture evidence block

- packages/web/src/styles/globals.css
It closes #150
Background Gradient 높이 설정이 상대적으로(%) 되어있어 피그마를 참고하여 px 단위로 바꾸었습니다.
피그마를 보면서 개발해본 게 처음이라 제가 맞게 했는지 확인해주시면 감사하겠습니다.
상: 피그마 / 하: 개발
- 없음
> fix background gradient uniform

- packages/api/src/feature/auth/controller/auth.controller.ts
- packages/api/src/feature/auth/repository/auth.repository.ts
- packages/api/src/feature/auth/service/auth.service.ts
- packages/interface/src/api/auth/endpoint/apiAut001.ts
- packages/interface/src/api/auth/endpoint/apiAut002.ts
- packages/interface/src/api/auth/endpoint/apiAut003.ts
- aut-001, aut-002, aut-003 구현
- postRefresh method 작동하도록 수정 구현
- POST /auth/sign-in으로 요청을 보내 로그인한다
- POST /auth/refresh로 요청을 보내 access token을 재발급한다
- "Authorization":"Bearer [accessToken]"을 헤더에 포함시킨 후 GET /auth/test에 요청을 보내 인증에 문제 없는지 확인한다
@Jiuuung 
@wjeongchoi
> 369 impl auth moudle interface and detail

- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/manage-club/activity-report/_mock/mock.ts
- packages/web/src/features/manage-club/activity-report/components/NewActivityReportList.tsx
- packages/web/src/features/manage-club/activity-report/types/activityReport.ts
- packages/web/src/features/manage-club/component/ActivityReportTable.tsx
- packages/web/src/features/manage-club/service/_mock/mockManageClub.ts
It closes #322 
- /manage-club 페이지도 /manage-club/activity-report와 똑같이 고치면 되겠다 생각했는데 통일이 안되어 있네요.. 같은 내용은 통일하면 좋을 것 같아요!
세부 설명: /manage-club 페이지에는 status가 숫자와 enum으로 구현되어 있고 /manage-club/activity-report 페이지에는 문자열로 구현되어 있음. 일단은 각자 방식에 맞춰서 professor approval 구현해 넣었습니당
> Add advisory professor approval column

- packages/web/src/app/register-club/page.tsx
- packages/web/src/features/register-club/components/ClubButton.tsx
It closes #497
- page.tsx 반응형 및 등록 신청 버튼 위치 구현 완료
- ClubButton이 화면 사이즈에 따라 동적으로 움직여서 ClubButton끼리의 gap이 20px이 되도록 유지되어야 하는데, 그러지 못하여 gap이 달라지는 문제가 있었습니다. 이는 ClubButton.tsx의 Card 컴포넌트에 `style={{flex: 1 0 0}} `을 추가하여 해결했습니다.
xs
sm
md
lg
- 없음
> Impl /register-club responsive design

- packages/web/src/app/register-club/provisional/page.tsx
- packages/web/src/features/register-club/components/AdvancedInformFrame.tsx
- packages/web/src/features/register-club/components/BasicInformFrame.tsx
- packages/web/src/features/register-club/frame/RegisterClubMainFrame.tsx
빌드 에러에 따른 긴급 수정
프론트의 RegistrationTypeEnum.provisional -> RegistrationTypeEnum.NewProvisional로 전부 변경
- 없음
> Change provisional -> newProvisional

- packages/web/src/app/manage-club/activity-report/[id]/page.tsx
- packages/web/src/features/manage-club/activity-report/components/AdvisorProfessorApprovalTag.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailedFrame.tsx
It closes #321 
- 정말 UI만 디자인했습니다 (Mock data도 아닌 raw 값이 return문에 끼어 있는 형태)
- File Thumbnail 부분의 component가 아직 없어서, 해당 부분을 제외하고 Figma와 동일한 화면을 만들었습니다
- `manage-club/activity-report/{아무 값이나}` 경로에서 확인 가능합니다
- 없음
> [UI] impl: manage-club/activity-report detailed page

- packages/api/src/app.module.ts
- packages/api/src/drizzle/schema/meeting.schema.ts
- packages/api/src/feature/meeting/meeting.controller.ts
- packages/api/src/feature/meeting/meeting.module.ts
- packages/api/src/feature/meeting/meeting.repository.ts
- packages/api/src/feature/meeting/meeting.service.ts
- packages/api/src/feature/user/repository/executive.repository.ts
- packages/api/src/feature/user/service/user.public.service.ts
- packages/interface/src/api/meeting/endpoint/apiMee001.ts
- packages/interface/src/api/meeting/endpoint/apiMee002.ts
- packages/interface/src/api/meeting/endpoint/apiMee003.ts
- packages/interface/src/api/meeting/endpoint/apiMee004.ts
- packages/interface/src/api/meeting/endpoint/apiMee005.ts
- packages/interface/src/api/meeting/endpoint/apiMeet005.ts
- packages/interface/src/api/meeting/index.ts
It closes #577 
- MEET001에서 request body에 빠진 내용 있을 때 그 field가 string일 경우 validation에서 걸리지 않고 undefined로 들어감
- query param은 string으로만 들어갈 수 있어서 MEET005의 query param의 타입을 string으로 받은 후 controller에서 MeetingEnum으로 바꿔서 사용했는데 이렇게 해도 되는지
- 머지 후 스키마 변경사항 전파
> impl meet 001 005 api

- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/manage-club/activity-report/_mock/mock.ts
- packages/web/src/features/manage-club/activity-report/components/NewActivityReportList.tsx
- packages/web/src/features/manage-club/services/_mock/mockManageClub.ts
manage-club 페이지와 manage-club/activity-report 페이지에 운위 태그 추가.
It closes #418 
manage-club페이지의 활동 보고서 테이블과 manage-club/activity-report의 신규활동보고서 테이블이 전체 개수 표시만을 제외하면 동일한것 같아서 추후 신규활동보고서 테이블을 manage-club페이지의 활동보고서 테이블과 동일하도록 코드 수정이 필요할듯합니다.
- 이유: 신규활동보고서 테이블에서 사용하는 NewActivity interface에서는 enum대신 string으로 상태와 타입등을 받아오고있어서 수정이 필요함.
> feat: add committe tag

- packages/web/src/common/components/Table.tsx
It closes #603
테이블이 가로로 길어짐에 따라 가로로 scroll 하여 볼 수 있도록 하기 위해 Table.tsx를 수정합니다.
바뀐 부분은 아래와 같습니다.
- TableInnerWrapper 추가: 가로 scroll 시에도 Table이 안 잘리려면 공백을 포함한 커다란 Wrapper가 필요하다고 판단했기 때문 
- TableInner `width -> min-width: 100%`로 수정: 언젠가 min-width에 대해 언급하셨던 적이 있는 것(?) 같아서 
- TableWithCount `align-items: center`로 수정: TableInnerWrapper를 가운데 정렬 해야 하는 상황이기 때문
- Count 추가: TableWithCount `align-items: center`으로 수정함에 따라 Count의 정렬 방식을 추가적으로 설정해줘야 했습니다
우연히 발견한 건데 아래처럼 창 너비를 확 줄이면 Content만 스크롤되고 Header는 스크롤이 안 되더라구요 
Content 부분을 `overflow-x: hidden` 처리하면 둘다 스크롤 안 되긴 하는데 그러면 잘리는 부분은 아예 볼 수조차 없는 문제가 있습니다.
나중에 반응형에서 손 보면 되는 것일까요?
그리고 ContentRow 아래 회색 줄도 잘리는 것 같은데.. 너비는 100%인데 내용이 그보다 넘쳐서 생기는 문제 같아요
> Impl Table horizontal scroll

- packages/web/src/app/clubs/page.tsx
It closes #634
동아리 목록에서 동아리 이름으로 검색 가능하도록 합니다.
- 영문은 대문자 소문자 관계 없게
- 한글은 검색어가 포함만 되면 다 뜨게
추가
- 검색 결과 나타나는 동아리가 없는 division은 아예 안 뜨게
- 없음
> Add search for /clubs

- packages/web/src/app/my/page.tsx
- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/executive/activity-certificate/components/ExecutiveAcfTable.tsx
- packages/web/src/features/my/components/MyClubTable.tsx
- packages/web/src/features/my/components/MyMemberTable.tsx
- packages/web/src/features/my/frames/MyRegisterFrame.tsx
- packages/web/src/features/my/services/_mock/mockMyRegister.ts
It closes #476 
행 클릭 시 다른 페이지로 라우팅하는 것 제외하고 모두 구현 완료
- Table 컴포넌트에 행 클릭 시 페이지로 이동하는 기능 추가 --> #638 
- Table 컴포넌트에 값이 없을 경우 보여지는 placeholder 텍스트 추가 --> #640
> Impl registration frame in my

- packages/web/src/features/landing/frames/MainPageMainFrame.tsx
It closes #627 
강조된 글씨의 font weight을 figma 기준으로 맞추고,
figma 기준으로 반응형 구현했습니다.
-360px : 'Clubs입니다' 줄바꿈 & sm 사이즈
361-720px : 줄바꿈 안 함 & sm 사이즈
721-960px : md 사이즈
961px- : lg 사이즈
- 없음
> 627 impl responsive mainslogan fix bug on font weight

- packages/web/src/common/components/Table.tsx
- packages/web/src/features/my/components/MyClubTable.tsx
- packages/web/src/features/my/components/MyMemberTable.tsx
It closes #640 
이미 placeholder 기능이 Table 컴포넌트에 존재(emptyMessage 옵션)해서 해당 부분을 표에 추가했습니다.
추가적으로 피그마와 스타일이 안 맞는 부분 수정했습니다.
- 없음
> Add placeholder to register table in /my

- packages/api/src/feature/club/repository/club.club-student-t.repository.ts
- packages/api/src/feature/club/repository/club.repository.ts
- packages/api/src/feature/club/service/club.service.ts
- packages/api/src/feature/rental/repository/rental.rental-order.repository.ts
- packages/interface/src/api/activity-certificate/endpoint/apiAcf002.ts
- packages/interface/src/api/club/endpoint/apiClb001.ts
- packages/interface/src/api/club/endpoint/apiClb002.ts
- packages/interface/src/api/club/endpoint/apiClb003.ts
- packages/interface/src/api/rental/endpoint/apiRnt004.ts
- packages/interface/src/api/user/endpoint/apiUsr001.ts
- packages/web/src/app/clubs/page.tsx
- packages/web/src/common/services/_mock/mockupUserProfile.ts
- packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
- packages/web/src/features/clubDetails/services/_mock/mockupClubDetail.ts
- packages/web/src/features/clubs/components/ClubCard.tsx
- packages/web/src/features/clubs/components/ClubListGrid.tsx
- packages/web/src/features/clubs/services/_mock/mockupClubData.ts
- packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
- packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
- packages/web/src/features/my/clubs/service/_mock/mockMyClubList.ts
- packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/index.tsx
- packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
@oRE-o : club의 name을 사용하는 repository를 전부 name_kr / name_en을 return하도록 바꾸었습니다.
@ChaeyeonAhn : club name을 참조하는 경우 club name_kr을 참조하도록 Frontend를 했습니다. 
It closes #652 
빌드가잘돼요!!!!!
필요하다면 Frontend에서 club name_kr / name_en을 구분해서 사용하는 UI를 개발하거나, 하는 그런 작업이 필요할 것 같습니다
> Implementing seperated club name (Korean/English)

- packages/web/src/common/services/getUserProfile.ts
- packages/web/src/features/activity-certificate/services/getUserClubs.ts
- packages/web/src/features/activity-certificate/services/useGetUserInfo.tsx
- packages/web/src/features/clubDetails/services/getClubDetail.ts
- packages/web/src/features/clubs/services/useGetClubsList.ts
- packages/web/src/features/common-space/service/postCommonSpaceUsageOrder.ts
- packages/web/src/features/manage-club/activity-report/services/useGetActivityReport.tsx
- packages/web/src/features/manage-club/activity-report/services/usePutActivityReport.tsx
- packages/web/src/features/manage-club/services/deleteChangeDelegateRequest.ts
- packages/web/src/features/manage-club/services/getChangeDelegateRequests.ts
- packages/web/src/features/manage-club/services/getClubDelegate.ts
- packages/web/src/features/manage-club/services/getDelegateCandidates.ts
- packages/web/src/features/manage-club/services/updateClubDelegate.ts
- packages/web/src/features/my/clubs/service/useGetMyClub.ts
- packages/web/src/features/my/services/getMyActivityCertificate.ts
- packages/web/src/features/my/services/getMyCommonSpace.ts
- packages/web/src/features/my/services/getMyDelegateRequest.ts
- packages/web/src/features/my/services/getMyPrinting.ts
- packages/web/src/features/my/services/getMyRentals.ts
- packages/web/src/features/my/services/patchMyDelegateRequest.ts
- packages/web/src/features/printing-business/service/postBusinessPrintingOrder.ts
- packages/web/src/features/rental-business/service/getAvailableRentals.ts
- packages/web/src/features/rental-business/service/postRentalOrder.ts
It closes #678 
- 제외 api에 포함된 Clb001, 002는 withauth로 되어있어서 axiosclient로 다시 변경
- 없음
> Fix AxiosClient to AxiosClientWithAuth in services

- packages/web/src/app/my/page.tsx
- packages/web/src/constants/changeRepresentative.ts
- packages/web/src/features/my/components/MyChangeRepresentative.tsx
It closes #529 
MyChangeRepresentative.tsx에 임시로 isNewRepresentative라는 boolean 변수를 달아서 두 경우 다 테스트할 수 있도록 해놨습니다
- 없음
> Fix representative change success component

- packages/web/src/app/manage-club/activity-report/[id]/page.tsx
- packages/web/src/features/manage-club/activity-report/_mock/mock.ts
It closes #608 
1. `packages/web/src/features/manage-club/activity-report/_mock/mock.ts` 에 mock data 선언
2. 해당 mock data로 내용 채우기 (신청 상태 및 지도교수 승인 부분 제외)
1. 활동 명단의 이름과 승인 관련 사항에 대해 백엔드와 협의
2. API 연결
1. '앞으로 진행할 내용'에 대하여 어떻게 생각하시나요?
2. mock data의 선언 및 사용 방법 등이 적절한가요?
- 없음
> impl mock data on manage-club/activity-report detail page

- packages/web/src/app/executive/register-club/page.tsx
- packages/web/src/common/components/ExecutiveRegistrationTable.tsx
- packages/web/src/common/components/RegisterMemberTable.tsx
- packages/web/src/common/components/Tag.tsx
- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/register-club/service/_mock/mockRegisterClub.ts
- packages/web/src/types/clubdetail.types.ts
- packages/web/src/types/divisions.types.ts
It closes #629 
집행부원이 동아리 등록 신청을 조회하는 페이지 UI를 mock data를 사용해서 만들었습니다.
1. Tag의 폭이 Figma 상으로 80px 고정인데, Tag 컴포넌트 정의 상 width가 fit-content로 되어 있습니다. 이 부분을 어떻게 구현하는 게 좋을지 궁금합니다.
2. 새로 만든 것들이 많은데, 경로나 이름 같은 것들을 적절하게 설정한 것일지 궁금합니다.
3. 집행부원만 접근 가능해야 하는데 이건 나중에 어떻게 작업해야 할지 궁금합니다.
- 없음
> feat: impl executive/register-club with mock data

- packages/web/src/app/register-club/page.tsx
- packages/web/src/features/register-club/service/_mock/mockMyRegistration.ts
It closes #716 
동아리 등록 신청 내역이 존재하는 경우, 동아리 등록 신청 창에서
1) 신청할 수 없음을 알리는 경고가 뜹니다. 신청 내역으로 연결되는 링크가 있습니다.
2) 신청 버튼이 비활성화 됩니다.
REG-012 API가 구현되지 않아, 우선 interface를 따르는 mock data로 UI 구현하였습니다.
1. 등록 정보를 가져와서 쓸 때, useEffect를 써야 하나 고민하다가 쓰지 않았는데 맞는 선택일까요?
2. 신청 내역으로 이동하는 링크를 누르면 `my/register-club/[id]`로 이동하는데, 이 자리에 REG-012에서 넘어오는 id를 그대로 사용하는 게 맞나요?
- API 연결
> handle existing club registration case (Mock Data)

- packages/api/src/feature/club/repository/club.club-student-t.repository.ts
- packages/api/src/feature/club/service/club.public.service.ts
- packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
회원 등록 신청을 생성하는 REG-007 / 008의 정책 변경을 완료했습니다.
본래 동아리 대표자만이 학생의 동아리 가입 신청을 수정 / 목록 열람 할 수 있었으나
대표자와 대의원, 즉 delegate인지 검사하는 로직으로 수정 완료했습니다.
2024.08.22 00:08 추가
REG-007에서 동아리 가입 신청이 "승인" 되면, 가입 신청 내부 신청자 학생을 동아리 멤버 명단에 추가합니다. (아직 미구현)
REG-007에서 동아리 가입 신청이 "반려" 되면, 가입 신청 내부 신청자 학생을 동아리 멤버 명단에서 제거합니다. (아직 미구현)
It closes #687 
- 없음
> revise member registration policy REG-007, 008

- packages/web/src/features/clubs/components/ClubListGrid.tsx
It closes #722 
foldablesectiontitle에 있는 접기랑 정렬 맞도록 수정
- 없음
> Remove right padding at /clubs

- packages/web/src/common/components/Header/index.tsx
- packages/web/src/common/components/NavTools/MobileNavItem.tsx
- packages/web/src/common/components/NavTools/NavSubItem.tsx
- packages/web/src/constants/nav.ts
- packages/web/src/constants/paths.ts
- packages/web/src/features/landing/frames/MainPageMainFrame.tsx
- packages/web/src/features/landing/frames/ServiceSectionFrame.tsx
- packages/web/src/features/manageClubTable/frames/ManageClubTableMainFrame.tsx
It closes #720 
1. 이번 배포에서 구현되지 않을 페이지에 대한 링크를 주석 처리했습니다.
2. 외부 링크로 연결되는 것에 대하여, 누르면 새 탭으로 외부 링크를 열도록 했습니다.
3. 집행부원으로 로그인한 경우에만 집행부 메뉴가 헤더에 보이도록 했습니다.
- 없음
> 720 Organize Header For Register Prod Release

- packages/web/src/common/components/FoldableSectionTitle.tsx
- packages/web/src/styles/globals.css
It closes #728 
Table Component는, 부모 안에 딱 맞는 width와 가로 위치를 가지는 것이 아니라, 100vw 너비와 (100vw - 100%)의 절반씩에 해당하는 대칭인 padding을 가지고 있습니다. (튀어나가서 스크롤할 영역까지 보이게 하기 위해서인 것으로 추정합니다)
그런데 FoldableSectionTitle 안에 있는 경우, 들여쓰기가 들어가면서 표가 배치되는 위치가 좌우대칭 위치가 아니게 됩니다. 이로 인해서 100vw의 너비지만 왼쪽 끝에 붙어있지 않은, 그래서 오른쪽으로 튀어나가는 거대한 Table이 전체 화면의 스크롤을 유발하게 됩니다.
1. width를 100%로 하는 수정 방안들 -> 튀어나간 영역이 보이지 않습니다
2. width를 100vw보다는 작게 한다 -> (좌우대칭이 아닌) 왼쪽, 오른쪽 끝의 특정 선 밖의 표가 잘려서 보입니다
@babycroc 님의 도움으로, main의 overflow-x를 hidden으로 처리하는 방법을 사용하게 되었습니다. globals.css를 수정하는 김에, min-width를 320px로 설정하는 것도 함께 했습니다. 다만 320px보다 좁은 화면에서 여전히 의도하지 않은 것으로 보이는 화면이 나타나는데, 장기적으로 100vw로 된 값들을 max(100vw, 320px)로 설정하는 등의 해결 방안이 필요해 보입니다.
- main의 min-width 320px 설정에 대응하는 수정 사항들
> Fix unintentional horizontal scroll

- packages/web/src/features/my/frames/MyClubFrame.tsx
It closes #761 
확인해보니까 모바일 말구 pc 브라우저에서도 똑같은 문제 있었는데 아무튼 둘다 고쳐졌어용
- 없음
> Fix align at /my club table

- packages/web/src/common/components/ExecutiveRegistrationTable.tsx
- packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
- packages/web/src/features/executive/register-club/services/useGetRegisterClub.ts
It closes #803
디비에 우연히 테스트 데이터가 없어서 응답으로 빈 리스트가 올 때 (items: []) 어떻게 처리할 건지 고민할 수 있게 되었는데요,
처음에는 자꾸 isError = true가 되다보니 AsyncBoundary에 html 덩어리로 Error 이렇게 뜨더라구요.
왜 `isError = true`인걸까 생각해보니 useGetRegisterClub.ts 안의 `return apiReg014.responseBodyMap[200].parse(data);` 
여기서 파싱하면서 `isError = true`가 되는 게 아닐까 싶었습니다. 
파싱을 빼고 `return data;` 이렇게만 하면 이 문제가 해결되기는 했으나, 파싱의 역할이 중요하기 때문에 parse 함수는 안 쓰면서 나름대로 오류 없는 형식의 데이터가 응답으로 오는지 확인하는 조건문을 달아두었습니다. 
이렇게 처리해도 되는지, 조건문은 적절한지 봐주시면 좋을 것 같습니다.
https://github.com/user-attachments/assets/d348d3ca-0c75-4d1c-aae2-4c18c1291211
- 없음
> /executive/register-club connect backend and page redirection

- packages/web/src/common/components/Header/_atomic/Login.tsx
- packages/web/src/common/components/Modal/AgreeModal.tsx
It closes #841 
1. 비로그인 클릭시 -> 로그인 해제되고, 다음 로그인에도 같은 모달 띄움
2. 체크박스 클릭 -> 확인 클릭시 -> 정상 로그인
- 없음
> feat: agree policy modal

- packages/web/src/features/manage-club/components/MembersTable.tsx
- packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
- packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
- packages/web/src/features/manage-club/members/frames/_mock/mockMembers.ts
- packages/web/src/features/manage-club/members/services/getClubMemberRegistration.ts
- packages/web/src/features/manage-club/members/services/patchClubMemberRegistration.ts
- packages/web/src/features/manage-club/services/_mock/mockManageClub.ts
It closes #759
(디비에 하마님으로 로그인 했을 때 대표자인 동아리가 없는데, 함부로 건드리면 안 될 것 같아서 디비로는 테스트를 못 해봤습니다)
목 데이터로 테스트할 때 쓰려고 `patchClubMemberRegistration.ts`에 `// console.log(data); Mock Mode 테스트 용` 이런 주석을 달아 놓았습니다. (목 모드로 테스트하실 때는 승인일 때는 enum 2, 반려일 때는 enum 3으로 직접 바꿔야 하는 것 같아요)
콘솔에 `{}` 이렇게 잘 뜨기는 합니다
그리고 변경사항이 /manage-club 페이지의 `MembersManageFrame.tsx`에도 영향을 미쳐서 여기도 API 연결했습니다.
await를 넣으니까 승인/반려 버튼을 누르면 테스트용 콘솔로그가 뜨고 나서 창이 닫히게 되었어요!
그리고 useEffect, useState 싹 정리했습니다!
피드백 덕분에 많이 배웠습니다 감사합니다ㅎㅎㅎ
> Connect backend for /manage-club/members

- packages/web/src/common/components/Modal/index.tsx
- packages/web/src/features/register-club/components/_atomic/CreateActivityReportModal.tsx
- packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
It closes #1015
`Modal/index.tsx` ModalProps 에 optional한 width prop을 추가했습니다.
모달에 width을 안 주면 `ModalContainer`의 width default 값이 `fit-content`로 되고, width를 주면 그 값으로 적용됩니다.
ModalScrollContainer의 경우 모달컨테이너의 자식 컴포넌트라서, `width: inherit;`을 추가했습니다. (ModalContainer는 너비가 100%인데 스크롤 범위는 작으면 이상해서..)
PastActivityReportModal에는 `width: 100%`로 주었습니다.
- 없음
> Add optional width prop to Modal 

- packages/api/src/feature/activity/activity.module.ts
- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.service.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.public.service.ts
- packages/interface/src/api/registration/endpoint/apiReg001.ts
- packages/interface/src/api/registration/endpoint/apiReg009.ts
- packages/interface/src/api/registration/utils/registrationTypeEnumChecker.ts
활보 생성 수정 시 인원 비어있으면 안됨
활보 삭제 기간 아님 → 별도 삭제 api 만들기
활보 수정시 활동인원 기간 체크 안함
활보 수정하면 집행부 승인 status and 지도교수 승인 status reset 되어야 함 (아직 안되는듯?)
등록 수정 시 지도교수 승인상태 초기화
가등록(신규)는 clubId가 존재하지 않음 (맞죠?). 생성 시에는 문제가 없는데 수정 시에 다음과 같은 에러가 떠욧
- 없음
> 1032 fix reg activity report

- packages/web/src/features/executive/register-member/[id]/_mock/mockClubMemberRegister.tsx
- packages/web/src/features/executive/register-member/[id]/services/calcRegisterInfo.tsx
- packages/web/src/features/executive/register-member/[id]/services/getRegisterMemberDetail.tsx
- packages/web/src/features/executive/register-member/components/RegisterInfoTable.tsx
- packages/web/src/features/executive/register-member/components/StatusInfoFrame.tsx
- packages/web/src/features/executive/register-member/components/TotalInfoFrame.tsx
- packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberDetailFrame.tsx
- packages/web/src/features/executive/register-member/services/getMemberRegistration.ts
It closes #822
dev db에 연결해서 REG020 테스트를 해보니 에러가 뜨는데, 그 원인으로는
db에 있는 이메일 끝에 캐리지 리턴(\r)이 있어서 parse를 못 통과하는 것으로 추정됩니다.. (예: `hippo0419@kaist.ac.kr\r`)
(apiReg020.ts에서 `email: z.string().trim().email(),` 로 수정해서 확인해보니 에러가 안 뜨는 걸로 보아 맞는 것 같아요)
이런 일이 있을 걸 대비해 
- .trim() 옵션을 추가하거나 
- 서비스 코드에서 parse를 빼고 그냥 `return data;` 하거나
할 수 있을 것 같은데 어떻게 생각하시는지 피드백 해주시면 감사하겠습니다
**스샷도 저 두 옵션 중 하나를 임의로 추가했을 때 찍은 거라 지금 푸시된 코드에는 반영이 안 되어 있어서,**
어떻게 할 지 피드백 받은 후에 반영하겠습니다.
- 없음
> Connect backend for /executive/register-member/[id]

- packages/web/src/app/credits/page.tsx
- packages/web/src/features/credits/credits.ts
/credits 페이지에 2024 가을 인원 추가, 기존 레이아웃 버그 픽스(최근학기 인원 외에는 카드들이 우측으로 24px 밀려있었음)
It closes #1056
before
after
- 타 참여인원 명단에 추가
> fix: /credits layout fix

- packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
REG-005에서 신청을 처리할 때, 해당 동아리가 이번 학기에 활동 중인지를 검사하는 로직이 추가되었습니다.
추가로 동아리가 활동중인지 검사하려면 일단 그 동아리가 존재하는 지 부터 확인해야할 것 같아서 그러한 로직도 추가했습니다.
It closes #1055 
이번학기에 활동중이지 않은 동아리에 요청을 넣으면 이런 에러를 반환 합니다.
- 없음
> feat: club available check logic in reg-005

- packages/api/src/feature/club/repository/club.club-student-t.repository.ts
- packages/api/src/feature/club/service/club.public.service.ts
club public service에 존재하는 removeStudentFromClub을 시행할 때 클럽 스튜던트 테이블에서는 사라지지만
해당 student가 동아리의 대표자 / 대의원일 경우 DB에서 대표자/대의원로 계속해서 남아있는 문제가 있었습니다
해당 문제를 고치기 위해, remove의 대상이 되는 학생의 ID를 통해 해당 학생이 대표자 / 대의원인지 확인하고, 만약 이것이 true이면
대표자/대의원인지 검사하는 로직을 추가합니다.
It closes #782 
- 없음
> fix: check isStudentDelegate while removing Student from Club

- packages/web/src/features/clubDetails/services/getClubDetail.ts
- packages/web/src/features/manage-club/components/MembersTable.tsx
- packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
- packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
- packages/web/src/features/manage-club/members/services/getClubMemberRegistration.ts
- packages/web/src/features/manage-club/members/services/patchClubMemberRegistration.ts
It closes #1087
대표자로 로그인하여 /manage-club 들어가면 동아리 등록 신청자 내역이 제대로 뜨지 않음 + 승인 반려 제대로 되게 고치기
***2줄 요약***
- MembersTable의 승**인 반려 버튼이 스크린샷처럼** 나타나는 게 맞는지
- patchClubMemberRegistration return data type이 **object 여야 하는데 string이어서 생기는 문제 근본적 해결은 못했음**
getClubDetail 조드 에러 : SPARCS TEST 동아리의 소개 문구가 db에 null이기 때문
getClubMemberRegistration 조드 에러 : email 끝에 \r 붙었기 때문
해결: 테스트 시에만 `return data`로 바꿔 해보고, 그대로 파싱을 남겨 놓았습니다
해결: 승인 상태 => 반려 버튼 나타나게 / 반려 상태 => 승인 버튼 나타나게 / 신청 상태 => 둘 다 나타나게 수정했습니다
`patchClubMemberRegistration` data type이 object 여야 하는데 string이어서 생기는 조드 에러 문제가 있습니다.
해결: `return data`로 수정. refetch를 받아와서 새로고침 실행하는 것으로 해결했습니다. (@wjeongchoi 🫶)
api를 까 봤는데도 거기서는 {}를 잘 주더라고요 왜 문제가 되는지 모르겠습니다 ㅠㅠ
(까본 것은 `member-registration.repository.ts>patchMemberRegistration`)
- 없음
> Fix MemberRegistration Error in MembersManageTable

- packages/web/src/app/meeting/[id]/page.tsx
- packages/web/src/features/meeting/components/MeetingAnnouncementFrame.tsx
- packages/web/src/features/meeting/constants/getEnumType.ts
- packages/web/src/features/meeting/constants/meetingTemplate.ts
- packages/web/src/features/meeting/services/_mock/mockupMeetingDetail.ts
- packages/web/src/features/meeting/services/useDeleteMeeting.ts
- packages/web/src/features/meeting/services/useGetMeetingDegree.ts
- packages/web/src/features/meeting/services/useGetMeetingDetail.ts
- packages/web/src/utils/Date/formatDate.ts
It closes #1100 
1. 공고 상세조회 페이지(meeting/1) 템플릿의 토큰 치환 작업 추가
2. 상세조회 페이지 api 연결(apiMee002)
3. 공고 삭제하기 api 연결(apiMee004)
4. 회의 차수 조회 api 연결(apiMee005)
1. 미팅 타입별로 조회 페이지 토큰 치환되는 부분 표시 잘 되는지 확인 (mockupMeetingDetail 데이터 변경하면서 확인)
2. 삭제하기 기능 잘 되는지 확인 
3. 목록으로 돌아가기, 삭제 후 목록으로 돌아가기 등 라우팅 처리 잘 되어있는지 확인
- 없음
> update meeting detail page, connect apiMee002, apiMee004, apiMee005

- packages/web/src/app/meeting/[id]/edit/page.tsx
- packages/web/src/app/meeting/[id]/page.tsx
- packages/web/src/app/meeting/announcement/create/page.tsx
- packages/web/src/common/components/Modal/ErrorModal.tsx
- packages/web/src/common/components/withAuthorization.tsx
- packages/web/src/features/meeting/components/MeetingAnnouncementForm.tsx
- packages/web/src/features/meeting/components/MeetingAnnouncementFrame.tsx
- packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
- packages/web/src/features/meeting/constants/meetingTemplate.ts
- packages/web/src/features/meeting/services/useCreateMeeting.ts
- packages/web/src/features/meeting/services/useUpdateMeeting.ts
- packages/web/src/utils/getSemester.ts
- packages/web/src/utils/getUserType.ts
It closes #1113 
**의결기구 공고** 의 마지막 pr입니다! 
- 피그마 링크: 
https://www.figma.com/design/gm0BeqvuY5dsA86XyRgEc3/%ED%95%99%EC%88%A0%ED%98%91%EB%A0%A5-02.-%5B%EB%8F%99%EC%97%B0%ED%98%91%EB%A0%A5%EC%82%AC%EC%97%85%5D?node-id=5903-56832
의결기구 > 공고 와 관련된 **모든 사항** 한번씩 확인 부탁드립니다. (페이지 ui, 라우팅, api 연결 등등 이상한 곳 없는지)
> connect api to meeting create page

- packages/web/src/app/meeting/page.tsx
- packages/web/src/features/meeting/components/MeetingNoticeItem.tsx
It closes #1143
회의록 목록을 바뀐 디자인대로 구현! [피그마](https://www.figma.com/design/gm0BeqvuY5dsA86XyRgEc3/%ED%95%99%EC%88%A0%ED%98%91%EB%A0%A5-02.-%5B%EB%8F%99%EC%97%B0%ED%98%91%EB%A0%A5%EC%82%AC%EC%97%85%5D?node-id=6356-6080&node-type=frame&m=dev)
- 없음
> Modify /meeting page

- packages/web/src/common/components/Info.tsx
- packages/web/src/common/components/Radio/index.tsx
- packages/web/src/features/printing-business/component/PrintingBusinessForm/_atomic/BinaryRadio.tsx
- packages/web/src/features/rental-business/components/Rentals/Vacuum.tsx
It closes #84 
- radio 위에 label 추가 가능하도록 수정
- info에 텍스트가 아닌 다른 것을 추가할 수 있도록 수정
- 없음
> Add label to radio & Add children to info

- packages/web/src/features/manage-club/members/components/AllMemberList.tsx
- packages/web/src/features/manage-club/members/frames/AllMemberListFrame.tsx
It closes #1154 
/manage-club/members 페이지의 무한로딩 현상 수정
AllMemberList 컴포넌트에서 검색창에 입력한 회원 목록을 필터링할 때 useEffect를 쓰게 해서 해결했습니다
- 없음
> Fix club member search filter

- packages/api/src/drizzle/schema/meeting.schema.ts
- packages/api/src/feature/meeting/announcement/announcement.controller.ts
- packages/api/src/feature/meeting/announcement/announcement.module.ts
- packages/api/src/feature/meeting/announcement/announcement.service.ts
- packages/api/src/feature/meeting/meeting.controller.ts
- packages/api/src/feature/meeting/meeting.module.ts
- packages/api/src/feature/meeting/meeting.repository.ts
- packages/api/src/feature/meeting/meeting.service.ts
- packages/interface/src/api/meeting/apiMee001.ts
- packages/interface/src/api/meeting/apiMee002.ts
- packages/interface/src/api/meeting/apiMee003.ts
- packages/web/src/features/meeting/services/_mock/mockupMeetingDetail.ts
It closes #1130 
현재 새로 작업이 된 Meeting 관련 Schema하고 이미 개발되어 있는 meeting controller / drizzle schema 사이에 차이가 꽤나 있었습니다
MEE001 - 004에 지원하는 기능들에 각각이 정상 작동하도록 리팩토링 / schema에 coulmn 추가 / 변경을 진행했습니다.
추가 ) MEE001은 이제 생성된 공고에 대한 id를 return 하도록 기능을 추가했습니다.
혹시 다른 문제가 발생하는 지 알려주시면 추가적으로 작업하겠습니다,
우선 가능한대로 API는 최신화를 시켜두어서 기능 작동 여부를 테스트해주시고 피드백 해주시면 감사하겠습니다..!
- 없음
> 1130 meeting announcement remaining backend issue list

- packages/api/src/feature/activity-certificate/controller/activity-certificate.controller.ts
- packages/api/src/feature/activity-certificate/service/activity-certificate.service.ts
- packages/api/src/feature/club/repository/club.repository.ts
- packages/interface/src/api/activity-certificate/endpoint/apiAcf002.ts
It closes #1181 
기존 반환 데이터: 
- {id: number, name_kr: string, name_en: string, startMonth: Date, endMonth: Date | null} 의 타입으로 반환하였음
- 예시: [{id: 1, name_kr: '동아리1', name_en: 'club1', startMonth: 2024.04.28, endMonth: 2024. 05.27}, {id: 1, name_kr: '동아리1', name_en: '동아리2', startMonth: 2024.05.28, endMonth: 2024. 06.27}, {id: 2, name_kr: '동아리2', name_en: 'club2', startMonth: 2024.09.01, endMonth: 2024. 10.27}]
수정 후 반환 데이터:
- {id: number, name_kr: string, name_en: string, dateRange: Array<{startMonth: Date, endMonth: Date | null}>} 의 타입으로 반환
- 예시: [{id: 1, name_kr: '동아리1', name_en: 'club1', startMonth: 2024.04.28, endMonth: 2024. 06.27}, {id: 2, name_kr: '동아리2', name_en: 'club2', startMonth: 2024.09.01, endMonth: 2024. 10.27}]
- 없음
> update apiAcf002 findClubActivities

- packages/api/src/feature/activity-certificate/controller/activity-certificate.controller.ts
- packages/api/src/feature/club/repository/club.repository.ts
It closes #1184 
1. acf002 > findClubActivities 함수에서 object assigning 과정에서 에러 발생!
알고보니 object가 null이거나 undefined인 경우에는 Object.assign 쓰면 안됨.. (사실 acc[id] = {} 이렇게 바로 하려다가 lint 에러 나길래 object.assign 한거라 다시 원래대로 돌려놓고 object 복사해서 사용하는 방법으로 lint 에러 해결함)
2. acf002 controller에 Student() annotation 붙일 때 studentId param을 user.studentId 가 아닌 user.id로 넘겨줘서 해당 부분 수정함
- 없음
> 1184 fix findclubactivities object assign issue

- packages/web/src/common/components/Forms/DateRangeInput.tsx
- packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
set min-width of DateRangeInput to 300px and resolve infinite update bug of date input in ActivityReportEditFrame
It closes #1162
- 없음
> fix: set min-width of DateRangeInput resolve infinite update

- packages/api/src/drizzle/schema/meeting.schema.ts
- packages/api/src/feature/meeting/meeting.repository.ts
- packages/api/src/feature/meeting/meeting.service.ts
It closes #1187
- 시트를 보면서 meeting schema 전반을 수정
- 안 쓰는 Enum table 삭제
- 사소하게 constraint 빠져있는 거 추가
- MeetingMapping 테이블 추가
<h3>질문</h3>
**updatedAt에 notNull을 붙여야 하는가에 대하여** 
- 시트 안의 다수 테이블`(Meeting, MeetingAnnouncement, MeetingAgenda 등)`의 createdAt, updatedAt column이 notNull로 설정 되어 있습니다. 그래서 notNull을 코드에 추가해보니 `meeting.repository.ts의 postExecutiveMeetingAnnouncement에서` 왜 updatedAt은 notNull인데 안 넣어줬어! 하는 식으로 에러가 떴습니다.
- 그래서 우선 코드에서 createdAt, updatedAt에서 notNull 조건을 뺐습니다.
- 기존 Meeting 테이블의 createdAt이 시트에서 notNull이지만 코드에서 defaultNow 값을 넣어주기 때문에 notNull constraint를 안 붙이신 것 같다고 보이는데, `그렇다면 updatedAt이 시트에서 notNull이라고해서 코드에서 defaultNow를 추가해야하나?` 수정도 안 했는데 meeting 테이블에 row 하나 생성하자마자 수정일이 들어가는 건 이상해 보입니다. 
- 따라서 이후 Task로 시트에서 다수 테이블의 updatedAt에서 notNull을 빼야 하지 않을까 하는 고민이 됩니다.
- (애초에 시트 고칠 때부터 고민했어야 …
> Modify meeting.schema.ts

- packages/api/src/drizzle/schema/meeting.schema.ts
Meeting mapping에서 PK 안 붙은 auto increment들 삭제합니다.
- 없음
> Remove autoincrement from positions in meeting mapping

- packages/interface/src/common/enum/user.enum.ts
- packages/web/src/common/components/Header/_atomic/Login.tsx
- packages/web/src/common/components/MyMenu/index.tsx
- packages/web/src/common/components/withAuthorization.tsx
- packages/web/src/utils/getUserType.ts
It closes #1195 
마이 메뉴에 유저 타입별 "학부생", "집행부원"이 보이지 않고 None으로 반환되는 이슈 수정
- 없음
> userType enum issue

- packages/api/src/drizzle/schema/meeting.schema.ts
MeetingMapping Table에 Content, vote와 같은 entity의 position은 nullable 해야 합니다.
왜냐하면 MeetingMapping Table row에 meeting과 meeting agenda의 관계만 나타낼 때도 있기 때문입니다.
그래서 스프레드 시트를 변경하게 되었습니다.
코드도 싱크 맞추려고 확인해보니,
오히려 entity position에는 notnull이 없어서 괜찮은데 Agenda Position은 notnull이 필요해서 요 부분을 수정했습니다.
pnpm generate도 문제가 없었고, 덤프는 따로 따지 않았습니다!
[스키마 스프레드시트](https://docs.google.com/spreadsheets/d/1REbeZHX53U3h_blcIkXra6rY3I4MDpg3LM7h80NqSH4/edit?gid=886338294#gid=886338294)
- 없음
> Verify NotNull in MeetingMapping position attributes

- packages/web/src/common/components/Tooltip.tsx
tooltip component를 만들었습니다.
It closes #1102
호버 X
호버O, 줄바꿈 X
호버O, 줄바꿈 O
- 없음
> Impl tooltip component

- packages/web/src/common/services/getSemesters.ts
- packages/web/src/features/clubDetails/components/RegisterInfo.tsx
- packages/web/src/features/clubs/components/ClubRegistrationButton.tsx
- packages/web/src/features/clubs/frames/ClubsStudentFrame.tsx
- packages/web/src/features/manage-club/components/MembersTable.tsx
- packages/web/src/features/manage-club/frames/MemberManageFrame.tsx
- packages/web/src/features/manage-club/frames/RegistrationManageFrame.tsx
- packages/web/src/features/manage-club/members/frames/RegisterMemberListFrame.tsx
- packages/web/src/features/my/frames/MyClubFrame.tsx
- packages/web/src/features/my/frames/ProfessorMyClubFrame.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
- packages/web/src/features/register-club/frames/RegisterClubFrame.tsx
- packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
- packages/web/src/utils/getSemesterNow.ts
It closes #1225 
학기 정보 가져오는 현재 학기 정보를 보여줘야 하는 화면에 SEM001 적용
어떤 api를 호출할 때 param으로 semesterId를 넣어야 하는 경우가 간혹 있는데(예: MemberManageFrame에서 CLB010 사용), 한번에 호출해서 처리하려고 하면 문제가 생기는 것을 발견함 (같은 파일에서 clubId 다른 api 통해서 가져다 쓰는 건 잘 됨) 이를 어떻게 해결할지
생각해본 방법
- 백엔드에서 semesterId 비우면 현재 학기로 처리하도록 설정하기
- 전역변수로 semester 정보 관리
- frame depth 하나 더 들어가서 쓰도록 수정
현재 학기 정보를 사용하는 화면이 생각보다는 적었는데, provider 이용해서 전역변수로 관리해야할지도 고민
- SEM001 적용 과정에서 ClubRegistrationButton과 RegisterInfo 코드가 매우 유사한 것을 발견함. 별도 이슈로 분리해서 수정해보면 좋을 것 같음.
> apply sem001

- packages/api/src/feature/meeting/meeting.repository.ts
It closes #1239
저번에 수정했던 apiMee005(공고에서 다음 회의 차수 불러오는)에서 api url만 next degree로 바꾸고 로직엔 +1 안 한거 발견함.
그래서 현재 다음 회의 차수를 불러오는 api이나 여전히 회의가 하나도 없으면 0을 반환함. 의도한 반환값: 1
- 없음
> update return value of selectExecutiveMeetingNextDegree function

- packages/web/package.json
- packages/web/src/stories/Checkbox.stories.tsx
- packages/web/src/stories/Radio.stories.tsx
- packages/web/src/stories/RadioOption.stories.tsx
- pnpm-lock.yaml
It closes #1246 
Radio, CheckboxOption, RadioOption에 대한 storybook 구현
#1245 를 보고 storybook/preview-api의 useArgs를 사용했습니다
https://github.com/user-attachments/assets/f9efcf90-b62d-400d-a513-18c59ba3e329
- 없음
> create story for radio and checkbox

- packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
- packages/web/src/features/my/components/ChangeRepresentativeModalContent.tsx
- packages/web/src/features/my/components/MyChangeRepresentative.tsx
It closes #1257 
BE 수정사항
- CLB011, 013:  3일 지난 요청 만료(get할 때 제외)되도록 수정 
-> 삭제는 하지 않고 제외만 되도록 했는데 삭제 필요한가요?
- CLB012: 승인/거절된 요청 남아있을 때 대표자 변경 신청->취소하면 이전 승인/거절 결과가 나타나는 문제 있어서 대표자 변경 취소할 때 이전에 남아있는 (3일 지나지 않은) 요청 삭제하도록 수정
추가된 조건 관련해서 API 문서에 파란색으로 수정해두었습니다. 리뷰할 때 같이 검토 부탁드립니다.
FE 수정사항
- 대의원 삭제할 때 Select 목록 업데이트 되지 않는 문제 수정
- 대표자 변경 요청 들어가있는 상태에서 대의원 삭제 버튼 disabled
- 대의원 비어있을 때 새로고침하면 계속 대의원 변경 api 호출되는 문제 수정
- 마이페이지에서 대표자 변경 승인/거절 모달 닫을 때 변경 요청 거절로 화면 바뀌는 문제 수정
나름 다양한 케이스에 대해 테스트하면서 오류 잡았는데 놓친 것이 있을 수 있으니 최대한 다양하게 테스트해주시면 감사하겠습니다
- 없음
> fix change representative

- packages/api/src/feature/activity/controller/activity.activity-term.controller.ts
- packages/api/src/feature/activity/controller/activity.controller.ts
- packages/api/src/feature/activity/service/activity.activity-term.service.ts
- packages/interface/src/api/activity/endpoint/apiAct005.ts
- packages/interface/src/api/activity/endpoint/apiAct006.ts
- packages/interface/src/api/activity/endpoint/apiAct009.ts
- packages/web/src/features/manage-club/activity-report/components/NewActivityReportList.tsx
- packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
- packages/web/src/features/manage-club/activity-report/services/useGetActivityReportListForATerm.tsx
- packages/web/src/features/manage-club/activity-report/services/useGetActivityTerms.tsx
- packages/web/src/features/manage-club/activity-report/services/useGetNewActivityReportList.tsx
- packages/web/src/features/manage-club/activity-report/services/useGetPastActivityReportList.tsx
- packages/web/src/features/manage-club/activity-report/types/activityReport.ts
- packages/web/src/features/register-club/components/ActivityReportFrame.tsx
- packages/web/src/features/register-club/components/ActivityReportList.tsx
- packages/web/src/features/register-club/types/registerClub.ts
apiAct005 (신규 활동보고서 목록 조회)
- 테스트 시 백엔드 코드 일부 수정해야 함
- 1. apiAct005 파일에서 requestBody 다음 부분을 requestQuery 내부로 이동 `clubId: z.coerce.number().int().min(1),`
- 2. activity.controller.ts 에서 다음과 같이 변경
- <img width="600" alt="image" src="https://github.com/user-attachments/assets/3bba0cde-a9ed-484b-9d03-49092db1e526" />
apiAct006 (과거 활동보고서 목록 조회)
- 테스트 시 백엔드 코드 수정해야 함
- 위와 같음 (apiAct006, apiAct009, activity.activity-term.controller, activity.activity-term.service 수정 필요)
- apiAct009가 과거 활동 기간 목록이 맞는지 모르겠음.. 일단 넣긴 했는데 데브에서 테스트했을 때 신규 활동보고서와 같은 기간이 밑에 추가됨 
- apiAct009에서의 year, name을 이런식으로 사용하는 것이 맞는지 모르겠음 `${term.year}년 ${term.name}학기` (name이 정확히 뭘 말하는건지 모르겠음)
It closes #1254
- 신규 활동 보고서
- 과거 활동 보고서
- 없음
> connect apiAct005, apiAct006

- packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
- packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
It closes #1270 
- 생성, 수정, 삭제 후 데이터 업데이트 안 되는 문제 수정 (delete는 router.replace로 해결, 생성, 수정은 window location href 이용해서 강제 새로고침) -> 혹시 더 좋은 방법이 있다면 알려주세요
- 눈에 보이는 console log 삭제
- 하드코딩된 텍스트 2024->2025 수정
- 없음
> Fix refetch problem with activity report

- packages/api/src/feature/funding/funding.controller.ts
- packages/api/src/feature/funding/funding.service.ts
- packages/interface/src/api/funding/endpoint/apiFnd005.ts
- packages/web/src/app/manage-club/funding/page.tsx
- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/manage-club/funding/components/NewFundingListSection.tsx
- packages/web/src/features/manage-club/funding/components/_atomic/NewFundingListTable.tsx
- packages/web/src/features/manage-club/funding/services/useGetNewFundingList.ts
- packages/web/src/features/manage-club/funding/types/funding.ts
- packages/web/src/features/manage-club/services/_mock/mockManageClub.ts
신규 지원금 신청 내역 조회 api 연결
It closes #1284 
데이터 생성하는 거 만들기 귀찮아서 현재 신청내역 데이터가 없는데 바로 post api 연결할게요.. 
요거는 mock:
요거는 현재 dev:
http://localhost:3000/manage-club/funding
- 없음
> connect apiFnd005

- packages/web/src/features/activity-report/components/PastActivityReportTable.tsx
- packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/activity-report/frames/ActivityReportMainFrame.tsx
- packages/web/src/features/activity-report/services/useGetActivityDeadline.ts
It closes #1324 
- 원래 react의 router push에 state로 데이터 전송하려 했는데 nextjs에서는 그게 안되는 것 같아서 로컬 스토리지로 틀었음
- 지도교수 화면은 계정이 없어서 확인 못함 아마 똑같은 로직이라 잘 될거 같긴 함
https://github.com/user-attachments/assets/8ffdb354-e9c5-4447-a676-e48349c4e0a4
- 없음
> 과거 활보 수정, 삭제, 승인 버튼 안 보이도록 변경

- packages/web/src/features/clubs/components/ClubCard.tsx
- packages/web/src/features/clubs/components/_atomic/ScrollingText.tsx
It closes #1352 
scrolltext는 쓰이진 않는데 남겨놓음
- 없음
> fix club name width with club card

- packages/api/src/app.module.ts
- packages/api/src/drizzle/schema/funding.schema.ts
- packages/api/src/feature/activity-certificate/activity-certificate.module.ts
- packages/api/src/feature/activity/activity.module.ts
- packages/api/src/feature/activity/repository/activity.repository.ts
- packages/api/src/feature/activity/service/activity.public.service.ts
- packages/api/src/feature/club/club.module.ts
- packages/api/src/feature/club/delegate/delegate.module.ts
- packages/api/src/feature/common-space/common-space.module.ts
- packages/api/src/feature/file/file.module.ts
- packages/api/src/feature/funding/funding.module.ts
- packages/api/src/feature/funding/model/funding.model.ts
- packages/api/src/feature/funding/repository/funding.comment.repository.ts
- packages/api/src/feature/funding/repository/funding.repository.ts
- packages/api/src/feature/funding/service/funding.service.ts
- packages/api/src/feature/promotional-printing/promotional-printing.module.ts
- packages/api/src/feature/registration/club-registration/club-registration.module.ts
- packages/api/src/feature/registration/member-registration/member-registration.module.ts
- packages/api/src/feature/user/repository/student.repository.ts
- packages/api/src/feature/user/service/user.public.service.ts
- packages/api/src/feature/user/service/user.service.ts
- packages/api/src/feature/user/user.module.ts
- packages/interface/src/api/funding/type/funding.type.ts
- packages/web/src/features/manage-club/funding/hooks/useCreateFunding.ts
- packages/web/src/features/manage-club/funding/hooks/useGetInitialFundingForm.ts
- packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
- packages/web/src/features/manage-club/funding/types/funding.ts
- packages/web/src/features/manage-club/services/_mock/mockFundingDetail.ts
현재 프론트에서는 택시, 전세버스, 콜밴, 비행기, 선박, 기타 의 경우에만 탑승자 명단 선택하도록 되어 있습니다. 신청할 때 철도를 선택하고 신청해서 탑승자가 없어야 하는데 상세조회에서 백에서 탑승자 명단을 보내줘서 백에서는 어떻게 돌아가고 있는지 궁금해요
교통비 증빙 관련 데이터 중 purpose 와 placeValidity가 각각 무엇을 말하는건지 궁금합니다. 프론트에선 하나의 필드로 되어 있는데 혹시 상황에 따라 다르게 데이터를 보내야 하는걸까요?
해당 계정에 지원금 신규 신청내역이 없는 경우 500 에러가 납니다
- 없음
> 1364 fix funding api bugs

- packages/web/src/common/components/List/ListItem.tsx
- packages/web/src/common/components/List/index.tsx
- packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
It closes #1342 
기존에 여러 구현 방식으로 만들어져 있던 bullet list와 number list를 하나의 컴포넌트로 통일합니다.
아래는 적용 예시입니다.
```
<List listType="bullet" gap={16}>
<ListItem>{`활동 장소: ${data.location}`}</ListItem>
<ListItem>{`활동 목적: ${data.purpose}`}</ListItem>
<ListItem>{`활동 내용: ${data.detail}`}</ListItem>
</List>
```
bullet point로도 사용할 수 있고, 시작 index (0 이상)를 정해서 number list로도 사용할 수 있습니다.
활동보고서 상세 보기 (packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx) 에 우선 적용해 두었으며, 추후 적용이 필요한 다른 페이지 리팩토링을 진행하고자 합니다.
1. List와 ListItem을 같은 폴더의 다른 파일로 분리해 봤는데, 매번 2개씩 import해야 한다는 단점이 있군요.. 어떻게 생각하시나요?
2. 위와 같은 구조로 바꾸면서, bullet 또는 숫자 뒤에 임의로 0.5em 만큼의 margin을 주도록 했는데 어때 보이시나요?
3. 이상하게 ListItem의 children 속에, <br />이 들어가 있는 것이 잘 적용이 안됩니다. <></>으로 감싸도 안되고, <div></div>로 감싸면 줄바꿈이 됩니다. 이 문제에 대해 어떻게 생각하시나요?
4. …
> feat: add List component

- packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
- packages/web/src/utils/Date/getKSTDate.ts
It closes #1406 
동연측 요청사항:
- 없음
> add a validation logic to funding expenditure date field

- packages/web/src/common/components/FileUpload.tsx
It closes #1404 
지원금 파일 업로드 되지 않는 이슈 발생
- 재현해보니 랜덤으로 가끔 파일이 업로드 되지 않음
- 특히 파일 추가 > 삭제 > 동일한 파일 다시 추가 했을 때에 조금 더 자주 파일 업로드 되지 않는 이슈가 생김
같은 파일 추가 시 onChange 함수가 제대로 트리거 되지 않아 발생할 수 있다고 생각되여 인풋 초기화하는 로직 추가함
- 없음
> fix: reset file input using ref to allow re-selection of the same file

- packages/web/src/common/components/ApproveReasonToast.tsx
- packages/web/src/common/components/PartialApproveReasonToast.tsx
- packages/web/src/common/components/RejectReasonToast.tsx
- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/manage-club/funding/constants/fundingProgressStatus.ts
- packages/web/src/features/manage-club/funding/detail/components/FundingStatusSection.tsx
- packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
- packages/web/src/features/manage-club/funding/services/useGetFunding.ts
- packages/web/src/features/manage-club/funding/services/useGetFundingDeadline.ts
- packages/web/src/features/manage-club/funding/services/useGetTermFundingList.ts
- packages/web/src/features/manage-club/services/_mock/mockManageClub.ts
It closes #1402
- 현재 지원금 집행부 관련 로직이 없어서 **목 모드**로 체크했습니다
- 없음
> add partial approve related logic in funding detail frame

- packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
- packages/api/src/feature/club/delegate/delegate.service.ts
- packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
- packages/web/src/features/manage-club/frames/_atomic/RepresentativeLoadFrame.tsx
> [Delegate] 대표자 변경 요청이 만료되지 않는 오류

- packages/api/src/feature/club/delegate/delegate.service.ts
대의원 아닌 사람이 manage-club/funding 같은 페이지에 아예 접속 자체가 안되도록 수정
- 없음
> fix: update delegate service response status to FORBIDDEN for empty results

- packages/web/src/common/components/Toast/index.tsx
- packages/web/src/features/manage-club/funding/detail/components/ExecutiveFundingReviewSection.tsx
It closes #1446 
- Toast 스크롤 할 때 contents가 제목 옆으로 보이지 않게 수정
- ExecutiveFundingReviewSection에서 화면 너비 좁아질 때 버튼 레이아웃 수정
1. API sheet: 
2. Figma: 
- 없음
- 없음
1. 집행부원 지원금 상세 페이지: http://localhost:3000/executive/funding/623
https://github.com/user-attachments/assets/abd40cce-d4e8-4fe5-9764-68f586501c2e
> fix funding detail layout

- packages/web/src/features/manage-club/funding/detail/components/TransportationEvidenceList.tsx
- packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
- packages/web/src/features/manage-club/funding/frames/AddEvidenceFrame.tsx
- packages/web/src/features/manage-club/funding/frames/FundingForm.tsx
It closes #1452 
- 교통비 탑승자 없어도 될 경우 필드 삭제
- 지출 목적 선택 안 했다가 활보로 증빙 불가 선택했을 때 필드 안 사라지는 에러 해결
- 이전 지원금이더라도 progress 보이도록 수정
1. API sheet: 
2. Figma: 
- 활보 증빙 불가 선택했을 때 체크되어있지 않던 체크박스가 체크되어 있는 문제가 있어서 FormController 코드 약간 수정했는데 확인 필요
- 없음
1. 지원금 상세조회 페이지: http://localhost:3000/executive/funding/105 (교통비 명단 삭제)
2. 지원금 상세조회 페이지: http://localhost:3000/manage-club/funding/623 (과거 활보, 이지윤 계정으로 로그인)
3. 지원금 작성 페이지: http://localhost:3000/manage-club/funding/create
> fix funding minor issues

- packages/api/src/drizzle/schema/registration.schema.ts
- packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
- packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
https://sparcs.slack.com/archives/C06LN70UX3L/p1739894981922079
- 작업요약1: Registration 이 semesterId 기반으로 관리되도록 post(Reg001)와 get(Reg012)를 수정하였습니다.
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
1. 동아리 상세조회 페이지: http://localhost:3000/register-club
> [TU-25] feat: manage registration and deadline with semester id

- packages/web/src/features/register-club/components/basic-info/BasicInformFrame.tsx
- packages/web/src/features/register-club/components/basic-info/ProvisionalBasicInformFrame.tsx
- packages/web/src/features/register-club/components/basic-info/_atomic/ClubNameField.tsx
- packages/web/src/features/register-club/constants/index.ts
- 동아리명 영문 무조건 입력 받도록 수정
- 재등록, 신규등록, 가등록(재)의 경우 동아리 선택하면 자동으로 동아리명 국문, 영문 필드 디폴트값 채워주기(영문은 정규식 체크하고 걸러서 입력)
- 동아리명 영문 입력 시 유효성 검증 추가
논의 스레드: https://sparcs.slack.com/archives/C06LN70UX3L/p1740080693959889
1. API sheet: 
2. Figma: 
- 없음
- 이번 학기 동아리 등록 기간 끝나고부턴 다시 원래대로 신규 동아리명 입력 받는걸로(체크박스도 되돌리고) 수정해야 함
1. 동아리 등록 페이지: http://localhost:3000/register-club/renewal
2. 혹은, 수정 페이지: http://localhost:3000/my/register-club/178/edit
> [TU-62] delete change club name checkbox and add validation for clubNameEn

- packages/web/src/common/components/Modal/RestoreDraftModal.tsx
- packages/web/src/constants/localStorage.ts
- packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
- packages/web/src/features/register-club/components/RegisterClubForm.tsx
- packages/web/src/features/register-club/components/activity-report/CreateActivityReportModal.tsx
- packages/web/src/features/register-club/components/activity-report/_atomic/ActivityReportForm.tsx
- packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
- 동아리 등록 신청페이지에 임시저장 기능 추가
- 동아리 신규등록 > 활보 작성 모달에도 임시저장 기능 추가
1. API sheet: 
2. Figma: 
- 지금 동아리등록이 폼이 하나라 그냥 하나의 객체에 임시저장 했는데 그래서 데이터가 가등록, 재등록, 신규등록 사이에 공유됨. 혹시 이게 문제가 된다면 객체 3개 만들어서 따로 임시저장 하겠음 @wjeongchoi 
- 없음
1. 동아리 등록 페이지: http://localhost:3000/register-club/promotional 
2. 활보 작성 모달
> [TU-24] add temporary storage to register club

- packages/api/src/feature/club/repository/club.repository.ts
https://www.notion.so/club-fetch-summary-1a2c25603b0b8083a505f009b8856407?pvs=4
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-70] Club Summary Fetch logic Fix

- packages/web/src/common/frames/HasClubRegistration.tsx
- packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
- packages/web/src/features/register-club/components/RegisterClubForm.tsx
- packages/web/src/features/register-club/components/basic-info/ProvisionalBasicInformFrame.tsx
- packages/web/src/features/register-club/constants/index.ts
- packages/web/src/features/register-club/frames/RegisterClubAuthFrame.tsx
- packages/web/src/features/register-club/frames/RegisterClubFrame.tsx
- packages/web/src/features/register-club/hooks/useGetAvailableRegistrationInfo.ts
- packages/web/src/features/register-club/services/useGetRegistrationAvailableClubs.ts
참고 스레드: https://sparcs.slack.com/archives/C06RTP91S3H/p1740129063238229
- 동아리 등록 페이지에서 타입별로 신청 가능한지 여부 판단하고 버튼 활성화 여부 결정하는 로직 수정
- 등록 페이지에서 버튼 클릭 후 신청 form 진입이 아니라, url로 진입 시에도 리라우팅 페이지 뜨게 추가함
- 동아리 신청 내역 상세조회에서 내가 신청한 것이 아니라도 대표자/대의원이면 url로 접근시 접근 가능. 
- 이 경우 수정, 삭제 버튼 안 보이게 막음
1. API sheet: 
2. Figma: 
- 없음
- 없음
1. 동아리 등록 페이지: http://localhost:3000/register-club
2. 상세조회에서 내가 신청한거 아니면 수정삭제 버튼 막음: http://localhost:3000/my/register-club/190
> 동아리 등록 페이지 신청내역 관련하여 버튼 활성화 여부 수정

- packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
- packages/web/src/features/activity-report/components/ActivityReportStatusSection.tsx
- packages/web/src/features/activity-report/components/ExecutiveActivityReportApprovalSection.tsx
- packages/web/src/features/activity-report/hooks/useGetActivityReportComments.ts
- packages/web/src/features/activity-report/types/activityReport.ts
- packages/web/src/features/activity-report/utils/filterComment.ts
- packages/web/src/features/executive/register-club/components/RegisterClubStatusSection.tsx
- packages/web/src/features/executive/register-club/frames/ClubRegisterApproveFrame.tsx
- packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
- packages/web/src/types/comment.ts
- 집행부원 동아리 등록 상세페이지에 comment toast 추가 (RegisterClubStatusSection 구현)
- 집행부원 동아리 등록 승인/반려 시 invalidateQuery 수정
- 프로필 전환 시 리다이렉트 하는 로직 삭제
1. API sheet: 
2. Figma: 
- activity-report 하위에 있던 Comment 타입을 common으로 이동
- 승인/반려 시 progress status는 바로 바뀌고 코멘트 목록도 업데이트 되는데, 토스트 색이 바로 안 변하는 문제가 있음. 활보/집행부 쪽과 동일한 로직인데 어디에서 문제가 생기는지 모르겠음 (시간 지나면 색 바뀜)
- 동아리 등록 상세 페이지 관련 frame 리팩토링
1. 동아리 등록 집행부 상세조회 페이지: http://localhost:3000/executive/register-club/167
2. 동아리 등록 집행부 목록 페이지 (승인/반려시 업데이트 확인): http://localhost:3000/executive/register-club
> [TU-72] 집행부원 상세페이지에 comment toast 추가

- packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
- packages/web/src/features/register-club/components/RegisterClubForm.tsx
- packages/web/src/features/register-club/components/basic-info/BasicInformFrame.tsx
- packages/web/src/features/register-club/components/basic-info/ProfessorInformFrame.tsx
- packages/web/src/features/register-club/components/basic-info/ProvisionalBasicInformFrame.tsx
- 동아리 등록 임시저장 가져올 때 트리거 한 번 날리는거 추가
- 지도교수 쪽 임시저장 시 데이터 리셋 되는 이슈 수정
- 가등록쪽 지도교수 데이터 있으면 checkbox true가 initial value가 되도록 수정
동연 제보 참고: https://www.notion.so/sparcs/1a3c25603b0b8042a3c6d5798779632f?pvs=4
1. API sheet: 
2. Figma: 
- 없음
- 없음
1. 동아리 등록 페이지: http://localhost:3000/register-club/renewal
> [TU-76] update register-club professor initial data trigger logic

- packages/web/src/features/manage-club/members/components/AllMemberList.tsx
- packages/web/src/features/manage-club/members/components/MemberSearchAndFilter.tsx
- 멤버 검색 및 필터링 기능 확인 시 문제 없었음 -> es hangul 검색 추가
- search and filter 부분 반응형 레이아웃 (모바일) 수정
1. API sheet: 
2. Figma: 
- 없음
- 없음
1. 회원 명단 페이지: http://localhost:3000/manage-club/members
> [TU-49] 전체 회원 명단 개선

- packages/api/src/drizzle/schema/club.schema.ts
- packages/api/src/drizzle/schema/registration.schema.ts
수문연의 등록이 영어 이름 길이로 안되는 이슈 해결
겸사겸사 club도 nameEn 100자로 변경
- 작업요약1
- 작업요약2
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-130] change registration and club name eng length to 100

- packages/web/src/common/components/Table.tsx
- packages/web/src/common/components/Table/TableCell.tsx
- packages/web/src/features/executive/register-member/components/RegisterInfoTable.tsx
- packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberDetailFrame.tsx
- packages/web/src/features/manage-club/frames/MemberManageFrame.tsx
- packages/web/src/features/manage-club/members/components/AllMemberList.tsx
- 테이블 정렬 기능이 관련 호출 메서드가 빠져있어서 추가함
- 대표자관리 쪽 테이블 정렬 기능 동작하도록 수정
- 집행부원 회원 등록 통계 데이터 표시 버그 수정
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-137] 테이블 정렬 이슈 및 집행부원 회원등록 통계 데이터 버그 수정

- packages/web/src/features/register-club/components/activity-report/PastActivityReportModal.tsx
활동보고서 모달에 활동보고서 페이지로 가는 버튼과 그 링크를 복사할 수 있는 버튼을 추가
1. API sheet: X
2. Figma: https://www.figma.com/design/gm0BeqvuY5dsA86XyRgEc3/Clubs?node-id=5232-68890&t=rfjxMf0ULRIYcCqL-0
- 없음
- 없음
1. 집행부원 동아리 신청 확인 페이지 (아래로 스크롤 후 활동보고서 하나 클릭) : http://localhost:3000/executive/register-club/285
> TU-167 "move to activity report page" button and "link copy" button to PastActivityReportModal

- packages/web/src/common/hooks/useGetDivisionType.ts
- packages/web/src/constants/tableTagList.ts
- packages/web/src/features/activity-report/components/executive/ChargedActivityModalTable.tsx
- packages/web/src/features/activity-report/components/executive/ExecutiveActivityClubTable.tsx
- packages/web/src/features/executive/funding/components/ChargedFundingModalTable.tsx
- packages/web/src/features/executive/funding/components/ExecutiveFundingClubTable.tsx
- packages/web/src/features/executive/register-member/components/RegisterMemberTable.tsx
- packages/web/src/features/manage-club/frames/ProfessorManageClubFrame/ClubInfoSection.tsx
- packages/web/src/features/my/components/MyClubProfTable.tsx
- packages/web/src/features/my/components/MyClubTable.tsx
- packages/web/src/features/my/components/MyMemberTable.tsx
- packages/web/src/types/clubdetail.types.ts
useGetDivisonType의 getDivisionTagColor와 getTagColorFromDivision이 중복 사용되기 때문에 useGetDivisonType의 getDivisionTagColor로 모든 사용을 통일하기 위해서 getTagColorFromDivision를 삭제하고 useGetDivisonType의 getDivisionTagColor를 tableTagList로 옮김 (usage들도 알맞게 수정함)
https://www.notion.so/sparcs/25-03-26-Clubs-1c2c25603b0b8072ad68c76411fc7424?p=1b4c25603b0b802eb60bf309605cab69&pm=s
- 없음
- 없음
1. 마이페이지 하단 테이블 (분과 태그 색상 사용된 곳들의 예시 중 하나) : http://localhost:3000/my
> [TU-119] division tag color 중복 사용 버그 해결

- packages/web/src/features/activity-report/services/useGetActivityAvailable.ts
- packages/web/src/features/manage-club/funding/services/useGetFundingDeadline.ts
- packages/web/src/lib/_axios/axiosMockInterceptor.ts
- packages/web/src/lib/axios.ts
- mock interceptor에서 계속 에러 걸려서 실패하던 로직 조금 수정했습니다
- mock 실행 시 mock response data를 콘솔에서 확인할 수 있도록 로거 추가했습니다
1. API sheet: 
2. Figma: 
- 없음
- 없음
프론트의 경우 리뷰가 필요한 화면 URL 목록:
> [TU-232] 프론트엔드 mock 모드 에러 수정

- packages/api/src/feature/activity/service/activity.service.new.ts
- packages/web/src/common/providers/AuthContext.tsx
- packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
지도교수 관련 오류 수정
1. stage에서 지도교수님이 활동보고서를 개별 승인 후, 목록으로 돌아가기 버튼을 클릭하면 로그아웃됩니다. 일괄 승인 시에는 문제가 발생하지 않습니다.~~
2. stage에서는 집행부가 승인을 하면 지도교수 승인란이 승인으로 변경되는 오류가 남아있는데, 해당 오류가 발생한 활동보고서를 지도교수님이 승인하실 수 없습니다.~~
3. stage에서 지도교수님이 승인하셔도 승인란이 대기로 남아있으며 승인버튼이 활상화되어 있습니다.~~
1. 목록으로 돌아가기 버튼 클릭 시 돌아가는 페이지의 링크가 잘못되어있었습니다. → 수정 완료
2. api로 리턴하는 값에 오타가 있어 승인 상태가 올바르게 반영되지 않습니다 → 수정 완료
https://www.notion.so/sparcs/stage-1ebc25603b0b80d58fa4ea10eaa116ea?pvs=4
> [TU-288] 지도교수 관련 오류 수정

- packages/api/src/feature/activity/service/activity.service.new.ts
- packages/web/src/features/activity-report/hooks/useGetActivityReportDetail.ts
view 에서 editedAt과 professorApprovedAt을 비교하도록 프론트 수정, update에서 professorApprovedAt을 수정하지 않도록 수정했습니다.
집행부나 다른 로직에서 잘 작동하는 지도 보아야 합니다.
선택적 지도교수에서도 잘 되는지도 테스트 필요합니다.
> [TU-244] 지도교수 승인과 수정 사이의 관계 해결

- packages/web/src/features/register-club/components/activity-report/EditActivityTermModal.tsx
- 활보 기간 입력 모달에서 기간이 5개 이상이 될 경우 UI가 깨지는 문제 해결
- 기간이 4개일 때 날짜 선택 overlay 일부가 잘리는 문제 해결
1. API sheet: 
2. Figma: 
- 없음
- 없음
AS-IS
https://github.com/user-attachments/assets/e7cd4adc-135b-4569-9d77-c42853f3467a
TO-BE
https://github.com/user-attachments/assets/a2ee5e5e-09dc-4843-8331-3b2ed6bdc9b0
1. 동아리 상세조회 페이지: http://localhost:3000/manage-club/activity-report/create
> [TU-263] 활보 기간 입력 모달 스크롤 수정

- packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
- packages/web/src/features/activity-report/hooks/useGetActivityReportDetail.ts
…or past activity
- 과거 활보 상세조회에서 수정, 삭제 버튼이 보이는 문제 해결(IsPastActivityReport를 체크하는 로직 확인 필요!)
- 지도교수 승인 후 대표자가 다시 수정했을 때에도 지도교수 승인 상태는 초기화되면 안됨 -> 해당 이슈 수정 완료
1. API sheet: 
2. Figma: 
- 없음
- 없음
프론트의 경우 리뷰가 필요한 화면 URL 목록:  
1. 활동 보고서 상세조회: http://localhost:3000/manage-club/activity-report/{id}
> [TU-246] 과거활보 수정삭제 버튼 삭제, 지도교수 승인 상태 초기화 로직 수정

- packages/web/src/features/activity-report/components/executive/ExecutiveCurrentActivityReportSection.tsx
- packages/web/src/features/activity-report/components/executive/ExecutivePastActivityReportSection.tsx
- 집행부원 활보 동아리별 상세 조회 페이지 마진을 디자인에 맞게 수정합니다
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-233] 집행부원 활보 동아리별 상세 조회 페이지 마진 수정

- packages/web/src/features/manage-club/components/ChangeRepresentativeInfo.tsx
- packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
- 지원금 신청 페이지 데이터 피커 날짜 제한 걸기(이번 지원금 기간: 2024.12.21~2025.06.13)
- 활보 운영위원회 회원들 조회 가능하게 열기 (운영위원회는 학생인데 집행부 페이지의 활보 목록만 조회 가능하게 열기.. 대신 승인 반려 버튼은 안되게 막기) --> 요건 일단 어떻게 할지 확인 중이라 아직 작업 전!
- TU-278에서 대표자 변경 관련 안내 메시지 추가한 것 커밋에 안 들어갔어서 그거 이 브랜치에 변경사항 추가함
1. API sheet: 
2. Figma: 
- 없음
- 운영위원회 활보 조회 부분 확인 중이라 아직 작업 전!
> [TU-279] 동아리 대표자 변경, 활보, 지원금 마이너한 수정사항들

- packages/web/src/app/executive/funding/deadline/page.tsx
- packages/web/src/features/executive/frames/ExecutiveDashboardFrame.tsx
- packages/web/src/features/executive/funding/components/FundingDeadlineFormModal.tsx
- packages/web/src/features/executive/funding/components/FundingDeadlineSection.tsx
- packages/web/src/features/executive/funding/components/FundingDeadlineSectionList.tsx
- packages/web/src/features/executive/funding/components/FundingDeadlineTable.tsx
- packages/web/src/features/executive/funding/hooks/useGetAllFundingDeadlines.ts
- packages/web/src/features/executive/funding/services/useCreateFundingDeadline.ts
- packages/web/src/features/executive/funding/services/useDeleteFundingDeadline.ts
- packages/web/src/features/executive/funding/services/useGetFundingDeadlines.ts
- packages/web/src/features/executive/services/useGetActivityDurations.ts
- 지원금 기간 관리하는 기능 집행부원 대시보드에 추가했습니다.
- 지원금은 활동기간에 따라 입력해야 해서 기존의 기간 관리 ui를 쓰기엔 무리가 있어 보여 새로 수정했습니다.
- 페이지를 만드는 걸로 수정했고 activityDuration 까지 테이블로 넣으려다 다대다 관계라 보기 불편할 것 같아 section으로 분리했습니다.
- 집행부원 대시보드에 지원금 기간 관리하기 바로가기 버튼 추가하는 김에 다른 항목도 추가했는데 다른 좋은 방안이 있다면 알려주세요
1. API sheet: https://clubs.stage.sparcs.org/api/docs/#/semester/get_executive_semesters_funding_deadlines
2. Figma: 
- 집행부원 대시보드 수정함
- 없음
1. 집행부원 대시보드: http://localhost:3000/executive
2. 지원금 기간 관리 페이지: http://localhost:3000/executive/funding/deadline
3. 지원금 기간 추가 모달
> [TU-305] 지원금 기간 관리 페이지 추가

- packages/web/src/features/register-club/components/activity-report/ActivityReportFrame.tsx
- packages/web/src/features/register-club/components/activity-report/ActivityReportList.tsx
- packages/web/src/features/register-club/components/activity-report/_atomic/SelectActivityTerm.tsx
- packages/web/src/features/register-club/services/useGetActivityReportsForPromotional.tsx
- 신규 동아리 등록의 활보 테이블에서 무한렌더링이 발생하고 있었음
- 아마 테이블 만들 때 data 할당하는 곳에 아래의 데이터 가공 로직도 들어가면서 렌더링이 계속 된게 아닌가 싶음.. 저걸 밖으로 꺼내서 메모이제션 하니까 된듯..? 그 외에 함수들 usecallback 빠진 곳도 추가함
`data: data.map(item => ({
...item,
durations: item.durations.map(duration => ({
startTerm: duration.startTerm!,
endTerm: duration.endTerm!,
})),
})),`
- 그리고 해당 api 쿼리 키에 clubId가 빠져있길래 그것도 추가함
- 활보 수정 모달 ui 레이아웃이 조금 이상하길래 수정했습니다
- 
1. API sheet: 
2. Figma: 
- 없음
- 없음
> [TU-237] 신규 동아리등록 무한 리렌더링 버그 수정
